// sigil-preview.tsx
// Generated by Sigil — do not edit manually

"use client";

import { RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useSigilPage } from "@/hooks/use-sigilpage";

export default function SigilPreview() {
  const { data: sigilPage, isLoading: sigilPageLoading } = useSigilPage();

  return (
    <div className="min-h-screen bg-background text-foreground font-sans">
    <div className="flex flex-col gap-4 p-4">
      <div className="flex flex-row gap-4 justify-between items-center">
        <h2 className="scroll-m-20 text-3xl font-semibold tracking-tight text-foreground">Preview</h2>
        <div className="flex flex-row gap-2">
          <Select>
            <SelectTrigger>
              <SelectValue placeholder="Select theme" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="default">Default (Dark)</SelectItem>
              <SelectItem value="light">Light</SelectItem>
            </SelectContent>
          </Select>
          <Select>
            <SelectTrigger>
              <SelectValue placeholder="Select overlay" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="page">Page</SelectItem>
              <SelectItem value="modal">Modal</SelectItem>
              <SelectItem value="sheet">Sheet</SelectItem>
            </SelectContent>
          </Select>
          <Button variant="secondary" onClick={() => fetch("/api/sigil/preview/refresh", { method: "POST" })}>
            <RefreshCw className="mr-2 h-4 w-4" />
            Refresh
          </Button>
        </div>
      </div>
      <div className="flex flex-col gap-0">
        <p className="text-sm text-muted-foreground">Preview renders here. Select a page and click Refresh.</p>
      </div>
    </div>
    </div>
  );
}
