// forge-deploy-create.tsx
// Generated by Sigil — do not edit manually

"use client";

import { useRouter } from "next/navigation";
import { Rocket } from "lucide-react";
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from "@/components/ui/breadcrumb";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { useDeployment } from "@/hooks/use-deployment";

export default function ForgeDeployCreate() {
  const router = useRouter();
  const { data: deployment, isLoading: deploymentLoading } = useDeployment();

  return (
    <div className="min-h-screen bg-background text-foreground font-sans">
    <div className="flex flex-col gap-6 p-6">
      <Breadcrumb>
        <BreadcrumbList>
          <BreadcrumbItem>
            <BreadcrumbLink href="/forge-deployments">Deployments</BreadcrumbLink>
          </BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>
            <BreadcrumbPage>New Deployment</BreadcrumbPage>
          </BreadcrumbItem>
        </BreadcrumbList>
      </Breadcrumb>
      <h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight text-foreground">New Deployment</h1>
      <Card>
        <CardHeader>
          <CardTitle>Deployment Configuration</CardTitle>
          <CardDescription>Configure and deploy your application.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex flex-col gap-4">
            <div className="flex flex-col gap-1.5">
              <Input id="deploy-name" type="text" placeholder="my-app-production" required />
            </div>
            <div className="flex flex-col gap-1.5">
              <Input id="deploy-branch" type="text" placeholder="main" />
            </div>
            <RadioGroup defaultValue="production">
              <div className="flex items-center gap-2">
                <RadioGroupItem value="production" id="production" />
                <Label htmlFor="production">Production</Label>
              </div>
              <div className="flex items-center gap-2">
                <RadioGroupItem value="staging" id="staging" />
                <Label htmlFor="staging">Staging</Label>
              </div>
              <div className="flex items-center gap-2">
                <RadioGroupItem value="preview" id="preview" />
                <Label htmlFor="preview">Preview</Label>
              </div>
            </RadioGroup>
            <div data-component="textarea" id="deploy-notes">
            </div>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardHeader>
          <CardTitle>Build Settings</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex flex-col gap-4">
            <div className="flex flex-col gap-1.5">
              <Input id="build-command" type="text" placeholder="npm run build" />
            </div>
            <div className="flex flex-col gap-1.5">
              <Input id="output-dir" type="text" placeholder=".next" />
            </div>
            <div data-component="checkbox" id="install-deps">
            </div>
            <div data-component="checkbox" id="clean-build">
            </div>
          </div>
        </CardContent>
      </Card>
      <div className="flex flex-row gap-2 justify-end">
        <Button variant="ghost" onClick={() => router.push("/forge-deployments")}>Cancel</Button>
        <Button variant="default" onClick={() => fetch("/api/deployments", { method: "POST" })}>
          <Rocket className="mr-2 h-4 w-4" />
          Deploy
        </Button>
      </div>
    </div>
    </div>
  );
}
