// tailwind.sigil.cjs — generated by Sigil, do not edit
module.exports = {
  theme: {
    extend: {
      colors: {
        sigil: {
          accent: 'rgb(var(--sigil-accent) / <alpha-value>)',
          'accent-hover': 'rgb(var(--sigil-accent-hover) / <alpha-value>)',
          background: 'rgb(var(--sigil-background) / <alpha-value>)',
          border: 'rgb(var(--sigil-border) / <alpha-value>)',
          danger: 'rgb(var(--sigil-danger) / <alpha-value>)',
          'danger-hover': 'rgb(var(--sigil-danger-hover) / <alpha-value>)',
          info: 'rgb(var(--sigil-info) / <alpha-value>)',
          success: 'rgb(var(--sigil-success) / <alpha-value>)',
          surface: 'rgb(var(--sigil-surface) / <alpha-value>)',
          'surface-2': 'rgb(var(--sigil-surface-2) / <alpha-value>)',
          text: 'rgb(var(--sigil-text) / <alpha-value>)',
          'text-muted': 'rgb(var(--sigil-text-muted) / <alpha-value>)',
          warning: 'rgb(var(--sigil-warning) / <alpha-value>)',
        },
      },
      fontFamily: {
        sans: ['var(--sigil-font-sans)'],
        mono: ['var(--sigil-font-mono)'],
      },
      borderRadius: {
        'sigil-lg': 'var(--sigil-lg)',
        'sigil-md': 'var(--sigil-md)',
        'sigil-sm': 'var(--sigil-sm)',
        'sigil-xl': 'var(--sigil-xl)',
      },
    },
  },
};
