// forge-jobs.tsx
// Generated by Sigil — do not edit manually

"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { Loader2, Plus, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { DataTable } from "@/components/data-table";
import { useScheduledJob } from "@/hooks/use-scheduledjob";

export default function ForgeJobs() {
  const router = useRouter();
  const [searchScheduledJob, setSearchScheduledJob] = useState("");

  const { data: scheduledJob, isLoading: scheduledJobLoading } = useScheduledJob();

  if (scheduledJobLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-6 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight text-foreground">Scheduled Jobs</h1>
        <Button variant="default" onClick={() => router.push("/jobs")}>
          <Plus className="mr-2 h-4 w-4" />
          New Job
        </Button>
      </div>
      <div className="relative">
        <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
        <Input type="search" placeholder="Search jobs..." className="w-full pl-9 [&::-webkit-search-cancel-button]:hidden [&::-webkit-search-decoration]:hidden" value={searchScheduledJob} onChange={(e) => setSearchScheduledJob(e.target.value)} />
      </div>
      <Card className="border-0 shadow-none ring-0">
        <CardContent>
          <DataTable
            data={(scheduledJob ?? []).filter((item) => {
              if (!searchScheduledJob) return true;
              const q = searchScheduledJob.toLowerCase();
              return Object.values(item).some((v) => String(v).toLowerCase().includes(q));
            })}
            columns={[
              { accessorKey: "status", header: "Status" },
              { accessorKey: "name", header: "Name" },
              { accessorKey: "schedule", header: "Schedule" },
              { accessorKey: "runtime", header: "Runtime" },
              { accessorKey: "lastRun", header: "Last Run" },
              { accessorKey: "nextRun", header: "Next Run" },
              { accessorKey: "successRate", header: "Success Rate" },
            ]}
            emptyMessage="No matching results found."
          />
        </CardContent>
      </Card>
    </div>
    </>
  );
}
