// forge-integrations.tsx
// Generated by Sigil — do not edit manually

"use client";

import { useRouter } from "next/navigation";
import { Loader2, Plug } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import { useIntegration } from "@/hooks/use-integration";

export default function ForgeIntegrations() {
  const router = useRouter();
  const { data: integration, isLoading: integrationLoading } = useIntegration();

  if (integrationLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-6 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <h1 className="text-2xl font-semibold tracking-tight text-foreground">Integrations</h1>
        <Button variant="default" onClick={() => router.push("/integrations")}>
          <Plug className="mr-2 h-4 w-4" />
          Add Integration
        </Button>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {(integration ?? []).map((item: NonNullable<typeof integration>[number]) => (
          <div key={String(item.provider ?? "")}>
            <Card>
              <CardHeader>
                <CardTitle>{String(item.name ?? "")}</CardTitle>
                <CardDescription>{String(item.provider ?? "")}</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex flex-row gap-4 justify-between items-center">
                  <Badge variant="outline" className="border-emerald-500/30 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">{String(item.status ?? "")}</Badge>
                  <p className="text-sm text-muted-foreground">{String(item.connectedAt ?? "")}</p>
                </div>
                <Separator />
                <Dialog>
                  <DialogTrigger render={<Button variant="outline" />}>
                    Configure
                  </DialogTrigger>
                  <DialogContent>
                    <DialogHeader>
                      <DialogTitle>Integration Settings</DialogTitle>
                      <DialogDescription>Update the configuration for this integration.</DialogDescription>
                    </DialogHeader>
                      <div className="flex flex-col gap-4">
                        <div className="flex flex-col gap-1.5">
                          <Label htmlFor="input-enter api key...">API Key</Label>
                          <Input id="input-enter api key..." type="password" placeholder="Enter API key..." />
                        </div>
                        <div className="flex flex-col gap-1.5">
                          <Label htmlFor="input-https://...">Webhook URL</Label>
                          <Input id="input-https://..." type="text" placeholder="https://..." />
                        </div>
                        <Button variant="default">Save Configuration</Button>
                      </div>
                  </DialogContent>
                </Dialog>
              </CardContent>
            </Card>
          </div>
        ))}
      </div>
    </div>
    </>
  );
}
