// forge-integrations.tsx
// Generated by Sigil — do not edit manually

"use client";

import { useRouter } from "next/navigation";
import { Loader2, Plug } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { useIntegration } from "@/hooks/use-integration";

export default function ForgeIntegrations() {
  const router = useRouter();
  const { data: integration, isLoading: integrationLoading } = useIntegration();

  if (integrationLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-6 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight text-foreground">Integrations</h1>
        <Button variant="default" onClick={() => router.push("/integrations")}>
          <Plug className="mr-2 h-4 w-4" />
          Add Integration
        </Button>
      </div>
      <div className="grid grid-cols-3 gap-4">
        {integration.map((item) => (
          <div key={item.name}>
            <Card>
              <CardHeader>
                <CardTitle>{item.name}</CardTitle>
                <CardDescription>{item.provider}</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex flex-row gap-4 justify-between items-center">
                  <Badge variant="outline" className="border-emerald-500/30 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">{item.status}</Badge>
                  <p className="text-base text-muted-foreground">{item.connectedAt}</p>
                </div>
              </CardContent>
            </Card>
          </div>
        ))}
      </div>
    </div>
    </>
  );
}
