// se-dimensions.tsx
// Generated by Sigil — do not edit manually

"use client";

import { useState } from "react";
import { toast } from "sonner";
import { postItem, updateItem, deleteItem } from "@/lib/api";
import { Loader2, Plus, Search } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Toaster } from "@/components/ui/sonner";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { DataTable } from "@/components/data-table";
import { useDimension } from "@/hooks/use-dimension";
import { useLens } from "@/hooks/use-lens";
import type { Dimension } from "@/types/dimension";
import type { Lens } from "@/types/lens";

export default function SeDimensions() {
  const [searchDimension, setSearchDimension] = useState("");
  const [modalOpen, setModalOpen] = useState(false);
  const [sheetDim, setSheetDim] = useState<Dimension | null>(null);
  const [searchLens, setSearchLens] = useState("");
  const [modalOpen2, setModalOpen2] = useState(false);
  const [sheetLens, setSheetLens] = useState<Lens | null>(null);
  // Dimension form
  const [dimName, setDimName] = useState("");
  const [dimCategory, setDimCategory] = useState("");
  const [dimWeight, setDimWeight] = useState("");
  const [dimDescription, setDimDescription] = useState("");
  // Lens form
  const [lensName, setLensName] = useState("");
  const [lensDescription, setLensDescription] = useState("");
  // Dimension edit
  const [editingDim, setEditingDim] = useState(false);
  const [editDimName, setEditDimName] = useState("");
  const [editDimCategory, setEditDimCategory] = useState("");
  const [editDimWeight, setEditDimWeight] = useState("");
  const [editDimDescription, setEditDimDescription] = useState("");
  // Lens edit
  const [editingLens, setEditingLens] = useState(false);
  const [editLensName, setEditLensName] = useState("");
  const [editLensDescription, setEditLensDescription] = useState("");

  const { data: dimension, isLoading: dimensionLoading, refetch: refetchDimensions } = useDimension();
  const { data: lens, isLoading: lensLoading, refetch: refetchLenses } = useLens();

  const handleSaveDimension = async () => {
    try {
      await postItem("dimensions", { name: dimName, category: dimCategory, weight: Number(dimWeight) || 1, description: dimDescription });
      toast.success("Dimension created");
      setModalOpen(false);
      setDimName(""); setDimCategory(""); setDimWeight(""); setDimDescription("");
      refetchDimensions();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to create dimension");
    }
  };

  const handleSaveLens = async () => {
    try {
      await postItem("lenses", { name: lensName, description: lensDescription });
      toast.success("Lens created");
      setModalOpen2(false);
      setLensName(""); setLensDescription("");
      refetchLenses();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to create lens");
    }
  };

  const startEditingDim = () => {
    if (!sheetDim) return;
    setEditDimName(sheetDim.name ?? "");
    setEditDimCategory(String(sheetDim.category ?? ""));
    setEditDimWeight(String(sheetDim.weight ?? ""));
    setEditDimDescription(String(sheetDim.description ?? ""));
    setEditingDim(true);
  };

  const handleUpdateDim = async () => {
    if (!sheetDim) return;
    try {
      await updateItem("dimensions", (sheetDim as { id: string }).id, { name: editDimName, category: editDimCategory, weight: Number(editDimWeight) || 1, description: editDimDescription });
      toast.success("Dimension updated");
      setEditingDim(false);
      setSheetDim(null);
      refetchDimensions();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to update dimension");
    }
  };

  const handleDeleteDim = async () => {
    if (!sheetDim) return;
    try {
      await deleteItem("dimensions", (sheetDim as { id: string }).id);
      toast.success("Dimension deleted");
      setSheetDim(null);
      refetchDimensions();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to delete dimension");
    }
  };

  const startEditingLens = () => {
    if (!sheetLens) return;
    setEditLensName(sheetLens.name ?? "");
    setEditLensDescription(String(sheetLens.description ?? ""));
    setEditingLens(true);
  };

  const handleUpdateLens = async () => {
    if (!sheetLens) return;
    try {
      await updateItem("lenses", (sheetLens as { id: string }).id, { name: editLensName, description: editLensDescription });
      toast.success("Lens updated");
      setEditingLens(false);
      setSheetLens(null);
      refetchLenses();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to update lens");
    }
  };

  const handleDeleteLens = async () => {
    if (!sheetLens) return;
    try {
      await deleteItem("lenses", (sheetLens as { id: string }).id);
      toast.success("Lens deleted");
      setSheetLens(null);
      refetchLenses();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to delete lens");
    }
  };

  if (dimensionLoading || lensLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-5 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <div className="flex flex-col gap-1">
          <h1 className="text-2xl font-semibold tracking-tight text-foreground">Dimensions & Lenses</h1>
          <p className="text-sm text-muted-foreground">Configure the scoring system — dimensions are axes, lenses reweight them</p>
        </div>
      </div>
      <Tabs defaultValue="dimensions">
        <TabsList>
          <TabsTrigger value="dimensions">Dimensions</TabsTrigger>
          <TabsTrigger value="lenses">Lenses</TabsTrigger>
        </TabsList>
        <TabsContent value="dimensions">
          <div className="flex flex-col gap-4">
            <div className="flex flex-row gap-4 justify-between items-center">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                <Input type="search" placeholder="Search dimensions..." className="w-full pl-9 [&::-webkit-search-cancel-button]:hidden [&::-webkit-search-decoration]:hidden" value={searchDimension} onChange={(e) => setSearchDimension(e.target.value)} />
              </div>
              <Dialog open={modalOpen} onOpenChange={setModalOpen}>
                <DialogTrigger render={<Button variant="default" />}>
                  <Plus className="mr-2 h-4 w-4" />
                  Add Dimension
                </DialogTrigger>
                <DialogContent>
                  <DialogHeader>
                    <DialogTitle>Add Dimension</DialogTitle>
                  </DialogHeader>
                  <div className="flex flex-col gap-4 py-4">
                    <div className="flex flex-col gap-1.5">
                      <Label htmlFor="name">Name</Label>
                      <Input id="name" name="name" type="text" placeholder="e.g., Error Handling" required value={dimName} onChange={(e) => setDimName(e.target.value)} />
                    </div>
                    <div className="flex flex-col gap-1.5">
                      <Label htmlFor="category">Category</Label>
                      <Select name="category" value={dimCategory} onValueChange={(v) => v && setDimCategory(v)}>
                        <SelectTrigger>
                          <SelectValue placeholder="Select..." />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="code-quality">Code Quality</SelectItem>
                          <SelectItem value="architecture">Architecture</SelectItem>
                          <SelectItem value="community">Community</SelectItem>
                          <SelectItem value="operations">Operations</SelectItem>
                          <SelectItem value="documentation">Documentation</SelectItem>
                          <SelectItem value="security">Security</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                    <div className="flex flex-col gap-1.5">
                      <Label htmlFor="weight">Default Weight</Label>
                      <Input id="weight" name="weight" type="number" placeholder="" value={dimWeight} onChange={(e) => setDimWeight(e.target.value)} />
                    </div>
                    <div className="flex flex-col gap-1.5">
                      <Label htmlFor="description">Description</Label>
                      <Textarea id="description" name="description" placeholder="" rows={2} value={dimDescription} onChange={(e) => setDimDescription(e.target.value)} />
                    </div>
                  </div>
                  <DialogFooter>
                    <Button variant="outline" onClick={() => setModalOpen(false)}>Cancel</Button>
                    <Button onClick={handleSaveDimension}>Save</Button>
                  </DialogFooter>
                </DialogContent>
              </Dialog>
            </div>
            <Card>
              <CardHeader>
                <CardTitle>Scoring Dimensions</CardTitle>
                <CardDescription>18 axes across 6 categories — each dimension has a default weight</CardDescription>
              </CardHeader>
              <CardContent>
                <DataTable
                  data={(dimension ?? [])
                    .filter((item) => {
                      if (!searchDimension) return true;
                      const q = searchDimension.toLowerCase();
                      return Object.values(item).some((v) => String(v).toLowerCase().includes(q));
                    })}
                  columns={[
                    { accessorKey: "name", header: "Name" },
                    { accessorKey: "category", header: "Category" },
                    { accessorKey: "weight", header: "Weight" },
                    { accessorKey: "description", header: "Description" },
                  ]}
                  emptyMessage="No matching results found."
                  onRowClick={(row) => setSheetDim(row as Dimension)}
                />
              </CardContent>
            </Card>
          </div>
        </TabsContent>
        <TabsContent value="lenses">
          <div className="flex flex-col gap-4">
            <div className="flex flex-row gap-4 justify-between items-center">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                <Input type="search" placeholder="Search lenses..." className="w-full pl-9 [&::-webkit-search-cancel-button]:hidden [&::-webkit-search-decoration]:hidden" value={searchLens} onChange={(e) => setSearchLens(e.target.value)} />
              </div>
              <Dialog open={modalOpen2} onOpenChange={setModalOpen2}>
                <DialogTrigger render={<Button variant="default" />}>
                  <Plus className="mr-2 h-4 w-4" />
                  Create Lens
                </DialogTrigger>
                <DialogContent>
                  <DialogHeader>
                    <DialogTitle>Create Lens</DialogTitle>
                  </DialogHeader>
                  <div className="flex flex-col gap-4 py-4">
                    <div className="flex flex-col gap-1.5">
                      <Label htmlFor="name">Name</Label>
                      <Input id="name" name="name" type="text" placeholder="e.g., DevOps Focus" required value={lensName} onChange={(e) => setLensName(e.target.value)} />
                    </div>
                    <div className="flex flex-col gap-1.5">
                      <Label htmlFor="description">Description</Label>
                      <Textarea id="description" name="description" placeholder="" rows={2} value={lensDescription} onChange={(e) => setLensDescription(e.target.value)} />
                    </div>
                  </div>
                  <DialogFooter>
                    <Button variant="outline" onClick={() => setModalOpen2(false)}>Cancel</Button>
                    <Button onClick={handleSaveLens}>Save</Button>
                  </DialogFooter>
                </DialogContent>
              </Dialog>
            </div>
            <Card>
              <CardHeader>
                <CardTitle>Scoring Lenses</CardTitle>
                <CardDescription>Lenses reweight dimensions for different perspectives — same data, different views</CardDescription>
              </CardHeader>
              <CardContent>
                <DataTable
                  data={(lens ?? [])
                    .filter((item) => {
                      if (!searchLens) return true;
                      const q = searchLens.toLowerCase();
                      return Object.values(item).some((v) => String(v).toLowerCase().includes(q));
                    })}
                  columns={[
                    { accessorKey: "name", header: "Name" },
                    { accessorKey: "dimension_count", header: "Dimensions" },
                    { accessorKey: "description", header: "Description" },
                  ]}
                  emptyMessage="No matching results found."
                  onRowClick={(row) => setSheetLens(row as Lens)}
                />
              </CardContent>
            </Card>
          </div>
        </TabsContent>
      </Tabs>
    </div>
    <Sheet open={!!sheetDim} onOpenChange={(open) => { if (!open) { setSheetDim(null); setEditingDim(false); } }}>
      <SheetContent side="right">
        <SheetHeader>
          <SheetTitle>{sheetDim?.name}</SheetTitle>
        </SheetHeader>
        {sheetDim && !editingDim && (
          <div className="flex flex-col gap-4 px-4 pt-4">
            <div className="flex flex-row gap-2">
              <Badge variant="secondary">{sheetDim.category}</Badge>
              <Badge variant="outline">Weight: {String(sheetDim.weight ?? 1)}</Badge>
            </div>
            <Separator />
            <div className="flex flex-col gap-1">
              <span className="text-xs text-muted-foreground uppercase tracking-wider">Description</span>
              <p className="text-sm text-muted-foreground leading-relaxed">{sheetDim.description}</p>
            </div>
            <Separator />
            <div className="flex flex-row gap-2">
              <Button variant="outline" size="sm" onClick={startEditingDim}>Edit</Button>
              <AlertDialog>
                <AlertDialogTrigger render={<Button variant="destructive" size="sm" />}>Delete</AlertDialogTrigger>
                <AlertDialogContent>
                  <AlertDialogHeader>
                    <AlertDialogTitle>Delete dimension?</AlertDialogTitle>
                    <AlertDialogDescription>This action cannot be undone. This will permanently delete the dimension.</AlertDialogDescription>
                  </AlertDialogHeader>
                  <AlertDialogFooter>
                    <AlertDialogCancel>Cancel</AlertDialogCancel>
                    <AlertDialogAction onClick={handleDeleteDim}>Delete</AlertDialogAction>
                  </AlertDialogFooter>
                </AlertDialogContent>
              </AlertDialog>
            </div>
          </div>
        )}
        {sheetDim && editingDim && (
          <div className="flex flex-col gap-4 px-4 pt-4">
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="edit-dim-name">Name</Label>
              <Input id="edit-dim-name" type="text" value={editDimName} onChange={(e) => setEditDimName(e.target.value)} />
            </div>
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="edit-dim-category">Category</Label>
              <Select value={editDimCategory} onValueChange={(v) => v && setEditDimCategory(v)}>
                <SelectTrigger>
                  <SelectValue placeholder="Select..." />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="code-quality">Code Quality</SelectItem>
                  <SelectItem value="architecture">Architecture</SelectItem>
                  <SelectItem value="community">Community</SelectItem>
                  <SelectItem value="operations">Operations</SelectItem>
                  <SelectItem value="documentation">Documentation</SelectItem>
                  <SelectItem value="security">Security</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="edit-dim-weight">Weight</Label>
              <Input id="edit-dim-weight" type="number" value={editDimWeight} onChange={(e) => setEditDimWeight(e.target.value)} />
            </div>
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="edit-dim-description">Description</Label>
              <Textarea id="edit-dim-description" rows={2} value={editDimDescription} onChange={(e) => setEditDimDescription(e.target.value)} />
            </div>
            <div className="flex flex-row gap-2 justify-end">
              <Button variant="outline" onClick={() => setEditingDim(false)}>Cancel</Button>
              <Button onClick={handleUpdateDim}>Save</Button>
            </div>
          </div>
        )}
      </SheetContent>
    </Sheet>
    <Sheet open={!!sheetLens} onOpenChange={(open) => { if (!open) { setSheetLens(null); setEditingLens(false); } }}>
      <SheetContent side="right">
        <SheetHeader>
          <SheetTitle>{sheetLens?.name}</SheetTitle>
        </SheetHeader>
        {sheetLens && !editingLens && (
          <div className="flex flex-col gap-4 px-4 pt-4">
            <Badge variant="outline">{String(sheetLens.dimension_count ?? 0)} dimensions</Badge>
            <Separator />
            <div className="flex flex-col gap-1">
              <span className="text-xs text-muted-foreground uppercase tracking-wider">Description</span>
              <p className="text-sm text-muted-foreground leading-relaxed">{sheetLens.description}</p>
            </div>
            <Separator />
            <div className="flex flex-row gap-2">
              <Button variant="outline" size="sm" onClick={startEditingLens}>Edit</Button>
              <AlertDialog>
                <AlertDialogTrigger render={<Button variant="destructive" size="sm" />}>Delete</AlertDialogTrigger>
                <AlertDialogContent>
                  <AlertDialogHeader>
                    <AlertDialogTitle>Delete lens?</AlertDialogTitle>
                    <AlertDialogDescription>This action cannot be undone. This will permanently delete the lens.</AlertDialogDescription>
                  </AlertDialogHeader>
                  <AlertDialogFooter>
                    <AlertDialogCancel>Cancel</AlertDialogCancel>
                    <AlertDialogAction onClick={handleDeleteLens}>Delete</AlertDialogAction>
                  </AlertDialogFooter>
                </AlertDialogContent>
              </AlertDialog>
            </div>
          </div>
        )}
        {sheetLens && editingLens && (
          <div className="flex flex-col gap-4 px-4 pt-4">
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="edit-lens-name">Name</Label>
              <Input id="edit-lens-name" type="text" value={editLensName} onChange={(e) => setEditLensName(e.target.value)} />
            </div>
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="edit-lens-description">Description</Label>
              <Textarea id="edit-lens-description" rows={2} value={editLensDescription} onChange={(e) => setEditLensDescription(e.target.value)} />
            </div>
            <div className="flex flex-row gap-2 justify-end">
              <Button variant="outline" onClick={() => setEditingLens(false)}>Cancel</Button>
              <Button onClick={handleUpdateLens}>Save</Button>
            </div>
          </div>
        )}
      </SheetContent>
    </Sheet>
    <Toaster />
    </>
  );
}
