// se-dimensions.tsx
// Generated by Sigil — do not edit manually

"use client";

import { useState } from "react";
import { toast } from "sonner";
import { Loader2, Plus, Search } from "lucide-react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Toaster } from "@/components/ui/sonner";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { DataTable } from "@/components/data-table";
import { useDimension } from "@/hooks/use-dimension";
import { useLens } from "@/hooks/use-lens";
import { deleteItem, postItem } from "@/lib/api";
import { Lens } from "@/types/lens";

export default function SeDimensions() {
  const [searchDimension, setSearchDimension] = useState("");
  const [modalOpen, setModalOpen] = useState(false);
  const [formName, setFormName] = useState("");
  const [formCategory, setFormCategory] = useState("");
  const [formWeight, setFormWeight] = useState("");
  const [formDescription, setFormDescription] = useState("");
    const handleCreateDimension = async () => {
    try {
      await postItem("dimensions", {
        name: formName,
        category: formCategory,
        weight: formWeight,
        description: formDescription,
      });
      toast.success("Dimension created");
      setModalOpen(false);
      setFormName("");
      setFormCategory("");
      setFormWeight("");
      setFormDescription("");
      refetchDimension();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to create dimension");
    }
  };


  const [searchLens, setSearchLens] = useState("");
  const [modalOpen2, setModalOpen2] = useState(false);
  const [formName2, setFormName2] = useState("");
  const [formDescription2, setFormDescription2] = useState("");
    const handleCreateLens2 = async () => {
    try {
      await postItem("lenses", {
        name: formName2,
        description: formDescription2,
      });
      toast.success("Lens created");
      setModalOpen2(false);
      setFormName("");
      setFormCategory("");
      setFormWeight("");
      setFormDescription("");
      setFormName2("");
      setFormDescription2("");
      refetchLens();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to create lens");
    }
  };


  const [sheetItem, setSheetItem] = useState<Lens | null>(null);
    const handleDelete = async () => {
    if (!sheetItem) return;
    try {
      await deleteItem("lenses", (sheetItem as { id: string }).id);
      toast.success("Lens deleted");
      setSheetItem(null);
      refetchLens();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to delete lens");
    }
  };



  const { data: dimension, isLoading: dimensionLoading, refetch: refetchDimension } = useDimension();
  const { data: lens, isLoading: lensLoading, refetch: refetchLens } = useLens();

  if (dimensionLoading || lensLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-5 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <div className="flex flex-col gap-1">
          <h1 className="text-2xl font-semibold tracking-tight text-foreground">Dimensions & Lenses</h1>
          <p className="text-sm text-muted-foreground">Configure the scoring system — dimensions are axes, lenses reweight them</p>
        </div>
      </div>
      <Tabs defaultValue="dimensions">
        <TabsList>
          <TabsTrigger value="dimensions">Dimensions</TabsTrigger>
          <TabsTrigger value="lenses">Lenses</TabsTrigger>
        </TabsList>
        <TabsContent value="dimensions">
          <div className="flex flex-col gap-4">
            <div className="flex flex-row gap-4 justify-between items-center">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                <Input type="search" placeholder="Search dimensions..." className="w-full pl-9 [&::-webkit-search-cancel-button]:hidden [&::-webkit-search-decoration]:hidden" value={searchDimension} onChange={(e) => setSearchDimension(e.target.value)} />
              </div>
              <Dialog open={modalOpen} onOpenChange={setModalOpen}>
                <DialogTrigger render={<Button variant="default" />}>
                  <Plus className="mr-2 h-4 w-4" />
                  Add Dimension
                </DialogTrigger>
                <DialogContent>
                  <DialogHeader>
                    <DialogTitle>Add Dimension</DialogTitle>
                  </DialogHeader>
                  <div className="flex flex-col gap-4 py-4">
                    <div className="flex flex-col gap-1.5">
                      <Label htmlFor="name">Name</Label>
                      <Input id="name" type="text" placeholder="e.g., Error Handling" value={formName} onChange={(e) => setFormName(e.target.value)} />
                    </div>
                    <div className="flex flex-col gap-1.5">
                      <Label htmlFor="category">Category</Label>
                      <Select value={formCategory} onValueChange={(v) => v && setFormCategory(v)}>
                        <SelectTrigger>
                          <SelectValue placeholder="Select..." />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="code-quality">Code Quality</SelectItem>
                          <SelectItem value="architecture">Architecture</SelectItem>
                          <SelectItem value="community">Community</SelectItem>
                          <SelectItem value="operations">Operations</SelectItem>
                          <SelectItem value="documentation">Documentation</SelectItem>
                          <SelectItem value="security">Security</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                    <div className="flex flex-col gap-1.5">
                      <Label htmlFor="weight">Default Weight</Label>
                      <Input id="weight" type="number" placeholder="" value={formWeight} onChange={(e) => setFormWeight(e.target.value)} />
                    </div>
                    <div className="flex flex-col gap-1.5">
                      <Label htmlFor="description">Description</Label>
                      <Textarea id="description" placeholder="" rows={2} value={formDescription} onChange={(e) => setFormDescription(e.target.value)} />
                    </div>
                  </div>
                  <DialogFooter>
                    <Button variant="outline" onClick={() => setModalOpen(false)}>Cancel</Button>
                    <Button onClick={handleCreateDimension}>Save</Button>
                  </DialogFooter>
                </DialogContent>
              </Dialog>
            </div>
            <Card>
              <CardHeader>
                <CardTitle>Scoring Dimensions</CardTitle>
                <CardDescription>18 axes across 6 categories — each dimension has a default weight</CardDescription>
              </CardHeader>
              <CardContent>
                <DataTable
                  data={(dimension ?? [])
                    .filter((item) => {
                      if (!searchDimension) return true;
                      const q = searchDimension.toLowerCase();
                      return Object.values(item).some((v) => String(v).toLowerCase().includes(q));
                    })}
                  columns={[
                    { accessorKey: "name", header: "Name" },
                    { accessorKey: "category", header: "Category" },
                    { accessorKey: "weight", header: "Weight" },
                    { accessorKey: "description", header: "Description" },
                  ]}
                  emptyMessage="No matching results found."
                />
              </CardContent>
            </Card>
          </div>
        </TabsContent>
        <TabsContent value="lenses">
          <div className="flex flex-col gap-4">
            <div className="flex flex-row gap-4 justify-between items-center">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                <Input type="search" placeholder="Search lenses..." className="w-full pl-9 [&::-webkit-search-cancel-button]:hidden [&::-webkit-search-decoration]:hidden" value={searchLens} onChange={(e) => setSearchLens(e.target.value)} />
              </div>
              <Dialog open={modalOpen2} onOpenChange={setModalOpen2}>
                <DialogTrigger render={<Button variant="default" />}>
                  <Plus className="mr-2 h-4 w-4" />
                  Create Lens
                </DialogTrigger>
                <DialogContent>
                  <DialogHeader>
                    <DialogTitle>Create Lens</DialogTitle>
                  </DialogHeader>
                  <div className="flex flex-col gap-4 py-4">
                    <div className="flex flex-col gap-1.5">
                      <Label htmlFor="name">Name</Label>
                      <Input id="name" type="text" placeholder="e.g., DevOps Focus" value={formName2} onChange={(e) => setFormName2(e.target.value)} />
                    </div>
                    <div className="flex flex-col gap-1.5">
                      <Label htmlFor="description">Description</Label>
                      <Textarea id="description" placeholder="" rows={2} value={formDescription2} onChange={(e) => setFormDescription2(e.target.value)} />
                    </div>
                  </div>
                  <DialogFooter>
                    <Button variant="outline" onClick={() => setModalOpen2(false)}>Cancel</Button>
                    <Button onClick={handleCreateLens2}>Save</Button>
                  </DialogFooter>
                </DialogContent>
              </Dialog>
            </div>
            <Card>
              <CardHeader>
                <CardTitle>Scoring Lenses</CardTitle>
                <CardDescription>Lenses reweight dimensions for different perspectives — same data, different views</CardDescription>
              </CardHeader>
              <CardContent>
                <DataTable
                  data={(lens ?? [])
                    .filter((item) => {
                      if (!searchLens) return true;
                      const q = searchLens.toLowerCase();
                      return Object.values(item).some((v) => String(v).toLowerCase().includes(q));
                    })}
                  columns={[
                    { accessorKey: "name", header: "Name" },
                    { accessorKey: "dimension_count", header: "Dimensions" },
                    { accessorKey: "description", header: "Description" },
                  ]}
                  emptyMessage="No matching results found."
                  onRowClick={(row) => setSheetItem(row as Lens)}
                />
              </CardContent>
            </Card>
          </div>
        </TabsContent>
      </Tabs>
    </div>
    <Sheet open={!!sheetItem} onOpenChange={(open) => { if (!open) { setSheetItem(null); } }}>
      <SheetContent side="right">
        <SheetHeader>
          <SheetTitle>{(sheetItem as unknown as Record<string, unknown>)?.name as string}</SheetTitle>
        </SheetHeader>
        {sheetItem && (
          <div className="flex flex-col gap-4 px-4 pt-4">
            <div className="flex flex-row gap-2">
              <AlertDialog>
                <AlertDialogTrigger render={<Button variant="destructive" size="sm" />}>Delete</AlertDialogTrigger>
                <AlertDialogContent>
                  <AlertDialogHeader>
                    <AlertDialogTitle>Delete lens?</AlertDialogTitle>
                    <AlertDialogDescription>This action cannot be undone.</AlertDialogDescription>
                  </AlertDialogHeader>
                  <AlertDialogFooter>
                    <AlertDialogCancel>Cancel</AlertDialogCancel>
                    <AlertDialogAction onClick={handleDelete}>Delete</AlertDialogAction>
                  </AlertDialogFooter>
                </AlertDialogContent>
              </AlertDialog>
            </div>
            <div>
              <div className="text-xs text-muted-foreground">Name</div>
              <div className="text-sm">{String((sheetItem as unknown as Record<string, unknown>)?.name ?? "")}</div>
            </div>
            <div>
              <div className="text-xs text-muted-foreground">Description</div>
              <div className="text-sm">{String((sheetItem as unknown as Record<string, unknown>)?.description ?? "")}</div>
            </div>
          </div>
        )}
      </SheetContent>
    </Sheet>
    <Toaster />
    </>
  );
}
