// sigil-datasources.tsx
// Generated by Sigil — do not edit manually

"use client";

import { Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DataTable } from "@/components/data-table";
import { useSigilDataSource } from "@/hooks/use-sigildatasource";

export default function SigilDatasources() {
  const { data: sigilDataSource, isLoading: sigilDataSourceLoading } = useSigilDataSource();

  return (
    <div className="min-h-screen bg-background text-foreground font-sans">
    <div className="flex flex-col gap-6 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight text-foreground">DataSources</h1>
        <Button variant="default">
          <Plus className="mr-2 h-4 w-4" />
          New DataSource
        </Button>
      </div>
      <DataTable
        data={sigilDataSource ?? []}
        columns={[
          { accessorKey: "alias", header: "Alias" },
          { accessorKey: "description", header: "Description" },
          { accessorKey: "field_count", header: "Fields" },
          { accessorKey: "capabilities", header: "Capabilities" },
        ]}
      />
    </div>
    </div>
  );
}
