// hooks/use-sse.ts
// Generated by Sigil — do not edit manually
import { useEffect, useRef, useCallback } from "react";

interface SSEOptions {
  onMessage?: (event: MessageEvent) => void;
  onError?: (error: Event) => void;
  onOpen?: () => void;
}

export function useSSE(url: string | null, options: SSEOptions) {
  const eventSourceRef = useRef<EventSource | null>(null);
  const optionsRef = useRef(options);
  optionsRef.current = options;

  const connect = useCallback(() => {
    if (!url) return;
    const source = new EventSource(url);
    source.onmessage = (event) => optionsRef.current.onMessage?.(event);
    source.onerror = (error) => optionsRef.current.onError?.(error);
    source.onopen = () => optionsRef.current.onOpen?.();
    eventSourceRef.current = source;
  }, [url]);

  const disconnect = useCallback(() => {
    eventSourceRef.current?.close();
    eventSourceRef.current = null;
  }, []);

  useEffect(() => {
    connect();
    return () => disconnect();
  }, [connect, disconnect]);

  return { connect, disconnect };
}
