package reactshadcn

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/chrispian/sigil/internal/config"
	"github.com/chrispian/sigil/internal/renderer"
)

// navItem represents a navigation entry extracted from the shell page.
type navItem struct {
	Label string
	Icon  string
	Href  string
}

// navGroup represents a group of nav items separated by separators.
type navGroup struct {
	Items []navItem
}

// renderLayout generates a layout.tsx for a module from the shell page + app config.
func renderLayout(ctx *renderer.LayoutContext) ([]renderer.OutputFile, error) {
	if ctx == nil || ctx.Shell == nil || ctx.Module == nil {
		return nil, nil
	}

	shell := ctx.Shell
	app := ctx.AppConfig
	mod := ctx.Module
	features := app.Features
	if features == nil {
		features = &config.AppFeatures{}
	}

	// Extract nav groups from the shell page's nav-menu components.
	groups := extractNavGroups(&shell.Layout, mod.ID)

	// Collect all nav items flat (for command palette).
	var allNavItems []navItem
	for _, g := range groups {
		allNavItems = append(allNavItems, g.Items...)
	}

	// Collect unique lucide icon names.
	iconSet := map[string]bool{}
	for _, item := range allNavItems {
		if item.Icon != "" {
			iconSet[item.Icon] = true
		}
	}
	// Brand icon from shell.
	brandIcon, brandTitle := extractBrand(&shell.Layout)
	if brandIcon != "" {
		iconSet[brandIcon] = true
	}
	// Feature icons.
	if features.MobileSidebar {
		iconSet["menu"] = true
	}
	if features.CommandPalette {
		iconSet["search"] = true
	}
	if features.ThemeToggle {
		iconSet["sun"] = true
		iconSet["moon"] = true
	}
	// Actions icons.
	for _, a := range app.Actions {
		if a.Icon != "" {
			iconSet[a.Icon] = true
		}
	}
	// Plus icon for actions dropdown.
	if len(app.Actions) > 0 {
		iconSet["plus"] = true
	}

	var buf bytes.Buffer

	// ── Imports ──
	buf.WriteString("// Generated by Sigil — do not edit manually\n")
	buf.WriteString("\"use client\";\n\n")
	buf.WriteString("import { useEffect, useState } from \"react\";\n")
	buf.WriteString("import { usePathname, useRouter } from \"next/navigation\";\n")
	buf.WriteString("import Link from \"next/link\";\n")

	// Lucide icons.
	var iconImports []string
	for icon := range iconSet {
		iconImports = append(iconImports, lucideComponentName(icon))
	}
	// Sort for deterministic output.
	sortStrings(iconImports)
	buf.WriteString("import {\n")
	for _, name := range iconImports {
		fmt.Fprintf(&buf, "  %s,\n", name)
	}
	buf.WriteString("} from \"lucide-react\";\n")

	// next-themes.
	if features.ThemeToggle {
		buf.WriteString("import { useTheme } from \"next-themes\";\n")
	}

	// shadcn components.
	buf.WriteString("import { Button } from \"@/components/ui/button\";\n")
	if features.CommandPalette {
		buf.WriteString("import {\n  CommandDialog,\n  CommandEmpty,\n  CommandGroup,\n  CommandInput,\n  CommandItem,\n  CommandList,\n} from \"@/components/ui/command\";\n")
	}
	if len(app.Actions) > 0 {
		buf.WriteString("import {\n  DropdownMenu,\n  DropdownMenuContent,\n  DropdownMenuItem,\n  DropdownMenuTrigger,\n} from \"@/components/ui/dropdown-menu\";\n")
	}
	// Check if any provider needs Select in topbar
	hasTopbarSelect := false
	for _, p := range app.Providers {
		if p.Position == "topbar" && p.UIType == "select" {
			hasTopbarSelect = true
			break
		}
	}
	if hasTopbarSelect {
		buf.WriteString("import {\n  Select,\n  SelectContent,\n  SelectItem,\n  SelectTrigger,\n  SelectValue,\n} from \"@/components/ui/select\";\n")
	}
	buf.WriteString("import { Separator } from \"@/components/ui/separator\";\n")
	if features.MobileSidebar {
		buf.WriteString("import {\n  Sheet,\n  SheetContent,\n  SheetHeader,\n  SheetTitle,\n} from \"@/components/ui/sheet\";\n")
	}
	buf.WriteString("import { Toaster } from \"@/components/ui/sonner\";\n")
	buf.WriteString("\n")

	// ── navItems ──
	buf.WriteString("// ── Navigation ────────────────────────────────────────────\n\n")
	buf.WriteString("const navItems = [\n")
	for _, item := range allNavItems {
		fmt.Fprintf(&buf, "  { label: %q, href: %q, icon: %s },\n",
			item.Label, item.Href, lucideComponentName(item.Icon))
	}
	buf.WriteString("];\n\n")

	// ── NavItem component ──
	buf.WriteString(`function NavItem({
  item,
  pathname,
  onClick,
}: {
  item: (typeof navItems)[number];
  pathname: string;
  onClick?: () => void;
}) {
  const Icon = item.icon;
  const isActive = pathname === item.href || pathname.startsWith(item.href + "/");
  return (
    <Link
      href={item.href}
      onClick={onClick}
      className={` + "`" + `flex items-center gap-2.5 rounded-md px-3 py-2 text-sm font-medium transition-colors ${
        isActive
          ? "bg-primary/10 text-primary"
          : "text-muted-foreground hover:bg-accent hover:text-accent-foreground"
      }` + "`" + `}
    >
      <Icon className="h-4 w-4" />
      {item.label}
    </Link>
  );
}

`)

	// ── SidebarContent ──
	brandIconComp := lucideComponentName(brandIcon)
	if brandIcon == "" {
		brandIconComp = lucideComponentName("hexagon")
		iconSet["hexagon"] = true
	}
	if brandTitle == "" {
		brandTitle = app.Name
	}

	buf.WriteString("function SidebarContent({\n  pathname,\n  onNavigate,\n}: {\n  pathname: string;\n  onNavigate?: () => void;\n}) {\n")
	buf.WriteString("  return (\n")
	buf.WriteString("    <div className=\"flex flex-col gap-2 p-4 flex-1\">\n")

	// Brand.
	fmt.Fprintf(&buf, "      <Link href=%q className=\"flex items-center gap-2 py-1\" onClick={onNavigate}>\n",
		allNavItems[0].Href)
	fmt.Fprintf(&buf, "        <%s className=\"h-5 w-5 text-primary\" />\n", brandIconComp)
	fmt.Fprintf(&buf, "        <span className=\"text-lg font-semibold tracking-tight\">%s</span>\n", brandTitle)
	buf.WriteString("      </Link>\n")
	buf.WriteString("      <Separator />\n")

	// Nav groups separated by separators.
	for i, g := range groups {
		buf.WriteString("      <nav className=\"flex flex-col gap-0.5\">\n")
		buf.WriteString("        {navItems")
		// Filter to this group's items by index range.
		startIdx := 0
		for gi := 0; gi < i; gi++ {
			startIdx += len(groups[gi].Items)
		}
		endIdx := startIdx + len(g.Items)
		fmt.Fprintf(&buf, ".slice(%d, %d)", startIdx, endIdx)
		buf.WriteString(".map((item) => (\n")
		buf.WriteString("          <NavItem key={item.href} item={item} pathname={pathname} onClick={onNavigate} />\n")
		buf.WriteString("        ))}\n")
		buf.WriteString("      </nav>\n")
		if i < len(groups)-1 {
			buf.WriteString("      <Separator />\n")
		}
	}

	buf.WriteString("      <div className=\"flex-1\" />\n")
	buf.WriteString("    </div>\n")
	buf.WriteString("  );\n}\n\n")

	// ── Layout export ──
	layoutName := pascalCase(mod.ID) + "Layout"
	shellName := pascalCase(mod.ID) + "Shell"

	// Import providers
	for _, p := range app.Providers {
		providerName := pascalCase(p.ID) + "Provider"
		hookName := "use" + pascalCase(p.ID) + "Context"
		fileName := toKebabCase(p.ID) + "-context"
		fmt.Fprintf(&buf, "import { %s, %s } from \"@/lib/%s\";\n", providerName, hookName, fileName)
	}
	if len(app.Providers) > 0 {
		buf.WriteString("\n")
	}

	fmt.Fprintf(&buf, "export default function %s({ children }: { children: React.ReactNode }) {\n", layoutName)
	// Wrap children in providers
	if len(app.Providers) > 0 {
		buf.WriteString("  return (\n")
		indent := "    "
		for _, p := range app.Providers {
			providerName := pascalCase(p.ID) + "Provider"
			fmt.Fprintf(&buf, "%s<%s>\n", indent, providerName)
			indent += "  "
		}
		fmt.Fprintf(&buf, "%s<%s>{children}</%s>\n", indent, shellName, shellName)
		for i := len(app.Providers) - 1; i >= 0; i-- {
			indent = indent[:len(indent)-2]
			providerName := pascalCase(app.Providers[i].ID) + "Provider"
			fmt.Fprintf(&buf, "%s</%s>\n", indent, providerName)
		}
		buf.WriteString("  );\n}\n\n")
	} else {
		fmt.Fprintf(&buf, "  return (\n    <%s>{children}</%s>\n  );\n}\n\n", shellName, shellName)
	}

	// ── Shell component ──
	fmt.Fprintf(&buf, "function %s({ children }: { children: React.ReactNode }) {\n", shellName)
	buf.WriteString("  const pathname = usePathname();\n")
	buf.WriteString("  const router = useRouter();\n")
	if features.ThemeToggle {
		buf.WriteString("  const { theme, setTheme } = useTheme();\n")
	}
	if features.MobileSidebar {
		buf.WriteString("  const [mobileOpen, setMobileOpen] = useState(false);\n")
	}
	if features.CommandPalette {
		buf.WriteString("  const [cmdOpen, setCmdOpen] = useState(false);\n")
	}
	// Provider context hooks
	for _, p := range app.Providers {
		if p.Position == "topbar" {
			hookName := "use" + pascalCase(p.ID) + "Context"
			varName := toCamelCase(p.ID) + "Ctx"
			fmt.Fprintf(&buf, "  const %s = %s();\n", varName, hookName)
		}
	}

	// Keyboard shortcuts.
	if features.CommandPalette {
		buf.WriteString(`
  useEffect(() => {
    function onKeyDown(e: KeyboardEvent) {
      if (e.key === "k" && (e.metaKey || e.ctrlKey)) {
        e.preventDefault();
        setCmdOpen((prev) => !prev);
      }
    }
    document.addEventListener("keydown", onKeyDown);
    return () => document.removeEventListener("keydown", onKeyDown);
  }, []);
`)
	}

	buf.WriteString("\n  return (\n    <>\n")
	buf.WriteString("      <div className=\"flex h-screen bg-background text-foreground font-sans\">\n")

	// Desktop sidebar.
	buf.WriteString("        {/* Desktop Sidebar */}\n")
	buf.WriteString("        <aside className=\"hidden md:flex w-[220px] shrink-0 border-r border-border overflow-y-auto bg-muted/20 flex-col\">\n")
	buf.WriteString("          <SidebarContent pathname={pathname} />\n")
	buf.WriteString("        </aside>\n\n")

	// Mobile sidebar.
	if features.MobileSidebar {
		buf.WriteString("        {/* Mobile Sidebar */}\n")
		buf.WriteString("        <Sheet open={mobileOpen} onOpenChange={setMobileOpen}>\n")
		buf.WriteString("          <SheetContent side=\"left\" className=\"w-[220px] p-0\">\n")
		buf.WriteString("            <SheetHeader className=\"sr-only\">\n")
		buf.WriteString("              <SheetTitle>Navigation</SheetTitle>\n")
		buf.WriteString("            </SheetHeader>\n")
		buf.WriteString("            <SidebarContent pathname={pathname} onNavigate={() => setMobileOpen(false)} />\n")
		buf.WriteString("          </SheetContent>\n")
		buf.WriteString("        </Sheet>\n\n")
	}

	// Main content area.
	buf.WriteString("        {/* Main */}\n")
	buf.WriteString("        <div className=\"flex-1 flex flex-col overflow-hidden\">\n")

	// Topbar.
	buf.WriteString("          {/* Topbar */}\n")
	buf.WriteString("          <div className=\"flex items-center justify-between px-4 py-2 border-b border-border\">\n")
	buf.WriteString("            <div className=\"flex items-center gap-3\">\n")

	if features.MobileSidebar {
		buf.WriteString("              <Button\n                variant=\"ghost\"\n                size=\"icon\"\n                className=\"md:hidden\"\n                onClick={() => setMobileOpen(true)}\n              >\n                <Menu className=\"h-4 w-4\" />\n              </Button>\n")
	}

	if features.CommandPalette {
		buf.WriteString(`              <button
                type="button"
                className="relative flex items-center w-56 rounded-md border border-input bg-transparent px-3 py-1.5 text-sm text-muted-foreground hover:bg-accent transition-colors"
                onClick={() => setCmdOpen(true)}
              >
                <Search className="mr-2 h-3.5 w-3.5" />
                <span className="flex-1 text-left text-xs">Search...</span>
                <kbd className="ml-auto pointer-events-none hidden h-5 select-none items-center gap-1 rounded border bg-muted px-1.5 font-mono text-[10px] font-medium opacity-100 sm:flex">
                  <span className="text-xs">⌘</span>K
                </kbd>
              </button>
`)
	}

	buf.WriteString("            </div>\n")
	buf.WriteString("            <div className=\"flex items-center gap-2\">\n")

	// Provider UI elements in topbar (e.g., lens selector)
	for _, p := range app.Providers {
		if p.Position == "topbar" && p.UIType == "select" {
			hookName := "use" + pascalCase(p.ID) + "Context"

			_ = p.Placeholder // placeholder may be used in future

			buf.WriteString("              <div className=\"flex items-center gap-2\">\n")
			fmt.Fprintf(&buf, "                <span className=\"text-[10px] uppercase tracking-wider text-muted-foreground hidden lg:block\">%s</span>\n", pascalCase(p.ID))
			fmt.Fprintf(&buf, "                <Select value={%sCtx.current%sId} onValueChange={(v) => v && %sCtx.set%sId(v)}>\n",
				toCamelCase(p.ID), pascalCase(p.ID), toCamelCase(p.ID), pascalCase(p.ID))
			buf.WriteString("                  <SelectTrigger className=\"h-8 w-[150px] text-xs\">\n")
			buf.WriteString("                    <SelectValue />\n")
			buf.WriteString("                  </SelectTrigger>\n")
			buf.WriteString("                  <SelectContent>\n")
			fmt.Fprintf(&buf, "                    {%sCtx.%s.map((item) => (\n",
				toCamelCase(p.ID), pluralize(toCamelCase(p.Datasource)))
			fmt.Fprintf(&buf, "                      <SelectItem key={String(item.%s)} value={String(item.%s)}>\n",
				p.TrackField, p.TrackField)
			fmt.Fprintf(&buf, "                        {String(item.%s)}\n", p.LabelField)
			buf.WriteString("                      </SelectItem>\n")
			buf.WriteString("                    ))}\n")
			buf.WriteString("                  </SelectContent>\n")
			buf.WriteString("                </Select>\n")
			buf.WriteString("              </div>\n")

			_ = hookName // used in provider import already
		}
	}

	// Theme toggle.
	if features.ThemeToggle {
		buf.WriteString("              <Separator orientation=\"vertical\" className=\"h-6\" />\n")
		buf.WriteString(`              <Button
                variant="ghost"
                size="icon"
                className="h-8 w-8"
                onClick={() => setTheme(theme === "dark" ? "light" : "dark")}
              >
                <Sun className="h-3.5 w-3.5 rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />
                <Moon className="absolute h-3.5 w-3.5 rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />
                <span className="sr-only">Toggle theme</span>
              </Button>
`)
	}

	// Actions dropdown.
	if len(app.Actions) > 0 {
		buf.WriteString("              <DropdownMenu>\n")
		buf.WriteString("                <DropdownMenuTrigger className=\"inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium h-8 w-8 hover:bg-accent hover:text-accent-foreground\">\n")
		buf.WriteString("                  <Plus className=\"h-4 w-4\" />\n")
		buf.WriteString("                </DropdownMenuTrigger>\n")
		buf.WriteString("                <DropdownMenuContent align=\"end\">\n")
		for _, action := range app.Actions {
			href := actionHref(action, mod.ID)
			iconComp := lucideComponentName(action.Icon)
			fmt.Fprintf(&buf, "                  <DropdownMenuItem onSelect={() => router.push(%q)}>\n", href)
			fmt.Fprintf(&buf, "                    <%s className=\"mr-2 h-4 w-4\" />\n", iconComp)
			fmt.Fprintf(&buf, "                    %s\n", action.Label)
			buf.WriteString("                  </DropdownMenuItem>\n")
		}
		buf.WriteString("                </DropdownMenuContent>\n")
		buf.WriteString("              </DropdownMenu>\n")
	}

	buf.WriteString("            </div>\n")
	buf.WriteString("          </div>\n\n")

	// Page content.
	buf.WriteString("          {/* Page content */}\n")
	buf.WriteString("          <main className=\"flex-1 overflow-y-auto\">\n")
	buf.WriteString("            {children}\n")
	buf.WriteString("          </main>\n")
	buf.WriteString("        </div>\n\n")

	// Command palette.
	if features.CommandPalette {
		buf.WriteString("        {/* Command Palette */}\n")
		buf.WriteString("        <CommandDialog open={cmdOpen} onOpenChange={setCmdOpen}>\n")
		buf.WriteString("          <CommandInput placeholder=\"Search...\" />\n")
		buf.WriteString("          <CommandList>\n")
		buf.WriteString("            <CommandEmpty>No results found.</CommandEmpty>\n")
		buf.WriteString("            <CommandGroup heading=\"Navigation\">\n")
		buf.WriteString("              {navItems.map((item) => {\n")
		buf.WriteString("                const Icon = item.icon;\n")
		buf.WriteString("                return (\n")
		buf.WriteString("                  <CommandItem\n")
		buf.WriteString("                    key={item.href}\n")
		buf.WriteString("                    onSelect={() => {\n")
		buf.WriteString("                      router.push(item.href);\n")
		buf.WriteString("                      setCmdOpen(false);\n")
		buf.WriteString("                    }}\n")
		buf.WriteString("                  >\n")
		buf.WriteString("                    <Icon className=\"mr-2 h-4 w-4\" />\n")
		buf.WriteString("                    {item.label}\n")
		buf.WriteString("                  </CommandItem>\n")
		buf.WriteString("                );\n")
		buf.WriteString("              })}\n")
		buf.WriteString("            </CommandGroup>\n")
		if len(app.Actions) > 0 {
			buf.WriteString("            <CommandGroup heading=\"Quick Actions\">\n")
			for _, action := range app.Actions {
				href := actionHref(action, mod.ID)
				iconComp := lucideComponentName(action.Icon)
				fmt.Fprintf(&buf, "              <CommandItem onSelect={() => { router.push(%q); setCmdOpen(false); }}>\n", href)
				fmt.Fprintf(&buf, "                <%s className=\"mr-2 h-4 w-4\" />\n", iconComp)
				fmt.Fprintf(&buf, "                %s\n", action.Label)
				buf.WriteString("              </CommandItem>\n")
			}
			buf.WriteString("            </CommandGroup>\n")
		}
		buf.WriteString("          </CommandList>\n")
		buf.WriteString("        </CommandDialog>\n\n")
	}

	buf.WriteString("        <Toaster />\n")
	buf.WriteString("      </div>\n")
	buf.WriteString("    </>\n")
	buf.WriteString("  );\n}\n")

	routeGroup := mod.RouteGroup
	if routeGroup == "" {
		routeGroup = fmt.Sprintf("(%s)", mod.ID)
	}

	return []renderer.OutputFile{
		{Path: fmt.Sprintf("app/%s/layout.tsx", routeGroup), Content: buf.Bytes()},
	}, nil
}

// extractNavGroups walks the shell page component tree and finds all nav-menu
// components, grouping them by separator boundaries in the parent.
func extractNavGroups(root *config.Component, module string) []navGroup {
	var groups []navGroup
	findNavMenus(root, module, &groups)
	if len(groups) == 0 {
		// Fallback: single group with all nav-menus found.
		var items []navItem
		collectAllNavItems(root, module, &items)
		if len(items) > 0 {
			groups = append(groups, navGroup{Items: items})
		}
	}
	return groups
}

// findNavMenus looks for nav-menu components within rows/columns containers,
// respecting separator boundaries to create groups.
func findNavMenus(c *config.Component, module string, groups *[]navGroup) {
	if c.Type == "nav-menu" {
		items := extractNavItemsFromMenu(c, module)
		if len(items) > 0 {
			*groups = append(*groups, navGroup{Items: items})
		}
		return
	}
	// For containers, recurse into children.
	for i := range c.Children {
		findNavMenus(&c.Children[i], module, groups)
	}
}

// collectAllNavItems is a fallback that finds all nav items in the tree.
func collectAllNavItems(c *config.Component, module string, items *[]navItem) {
	if c.Type == "nav-menu" {
		extracted := extractNavItemsFromMenu(c, module)
		*items = append(*items, extracted...)
		return
	}
	for i := range c.Children {
		collectAllNavItems(&c.Children[i], module, items)
	}
}

// extractNavItemsFromMenu extracts nav items from a nav-menu component's props.
func extractNavItemsFromMenu(c *config.Component, module string) []navItem {
	itemsProp, ok := c.Props["items"]
	if !ok {
		return nil
	}
	itemsList, ok := itemsProp.([]interface{})
	if !ok {
		return nil
	}
	var items []navItem
	for _, raw := range itemsList {
		m, ok := raw.(map[string]interface{})
		if !ok {
			continue
		}
		label, _ := m["label"].(string)
		page, _ := m["page"].(string)
		icon, _ := m["icon"].(string)
		if label == "" || page == "" {
			continue
		}
		items = append(items, navItem{
			Label: label,
			Icon:  icon,
			Href:  pageRoute(page, module),
		})
	}
	return items
}

// extractBrand finds the brand section (icon + heading) from the shell layout.
func extractBrand(root *config.Component) (icon, title string) {
	return findBrand(root)
}

func findBrand(c *config.Component) (string, string) {
	// Look for a component with id "brand" or a heading inside the first sidebar child.
	if c.ID == "brand" {
		for _, child := range c.Children {
			if child.Type == "icon" {
				if name, ok := child.Props["name"].(string); ok {
					icon := name
					// Look for sibling heading.
					for _, sibling := range c.Children {
						if sibling.Type == "heading" {
							if text, ok := sibling.Props["text"].(string); ok {
								return icon, text
							}
						}
					}
					return icon, ""
				}
			}
		}
	}
	for i := range c.Children {
		icon, title := findBrand(&c.Children[i])
		if icon != "" || title != "" {
			return icon, title
		}
	}
	return "", ""
}

// actionHref builds a route path for an app action.
func actionHref(action config.AppAction, module string) string {
	href := pageRoute(action.Page, module)
	if action.Query != "" {
		href += "?" + action.Query
	}
	return href
}

// lucideComponentName converts a kebab-case icon name to PascalCase lucide component name.
func lucideComponentName(name string) string {
	if name == "" {
		return "Circle"
	}
	parts := strings.Split(name, "-")
	var result strings.Builder
	for _, part := range parts {
		if len(part) > 0 {
			result.WriteString(strings.ToUpper(part[:1]))
			result.WriteString(part[1:])
		}
	}
	return result.String()
}

// pascalCase converts a kebab/snake-case string to PascalCase.
func pascalCase(s string) string {
	s = strings.ReplaceAll(s, "_", "-")
	parts := strings.Split(s, "-")
	var result strings.Builder
	for _, part := range parts {
		if len(part) > 0 {
			result.WriteString(strings.ToUpper(part[:1]))
			result.WriteString(part[1:])
		}
	}
	return result.String()
}

// sortStrings sorts a string slice in place.
func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j] < s[j-1]; j-- {
			s[j], s[j-1] = s[j-1], s[j]
		}
	}
}
