package reactshadcn

import (
	"bytes"
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/chrispian/sigil/internal/config"
	"github.com/chrispian/sigil/internal/renderer"
)

// renderPage generates a React TSX component file for a page.
func renderPage(ctx *renderer.RenderContext) ([]renderer.OutputFile, error) {
	page := ctx.Page
	fileName := toKebabCase(page.ID) + ".tsx"
	funcName := toPascalCase(page.ID)

	imports := newImportTracker()
	var bodyBuf bytes.Buffer
	renderComponent(&bodyBuf, &page.Layout, 2, imports, ctx)

	// Pre-register datasource hook imports (must happen before imports.String())
	hasParams := false
	for _, dsRef := range page.DataSources {
		hookModule := fmt.Sprintf("@/hooks/use-%s", toKebabCase(dsRef.Alias))
		if len(dsRef.Params) > 0 {
			// Detail page: import the ById variant
			hookName := "use" + toPascalCase(dsRef.Alias) + "ById"
			imports.addLocal(hookName, hookModule)
			hasParams = true
		} else {
			hookName := "use" + toPascalCase(dsRef.Alias)
			imports.addLocal(hookName, hookModule)
		}
	}
	if hasParams {
		imports.addReact("useParams", "next/navigation")
	}

	var buf bytes.Buffer
	buf.WriteString(fmt.Sprintf("// %s.tsx\n", toKebabCase(page.ID)))
	buf.WriteString("// Generated by Sigil — do not edit manually\n\n")
	buf.WriteString("\"use client\";\n\n")

	// Write imports
	buf.WriteString(imports.String())
	buf.WriteString("\n")

	// Component function
	buf.WriteString(fmt.Sprintf("export default function %s() {\n", funcName))

	// Router hook (if any navigate actions were used)
	if imports.hasReact("useRouter") {
		buf.WriteString("  const router = useRouter();\n")
	}

	// Params hook (if any datasource uses params)
	if hasParams {
		buf.WriteString("  const params = useParams();\n")
	}

	// DataSource hooks
	for _, dsRef := range page.DataSources {
		varName := toCamelCase(dsRef.Alias)
		if len(dsRef.Params) > 0 {
			// Detail page: use ById variant with first param
			hookName := "use" + toPascalCase(dsRef.Alias) + "ById"
			// Get the first param key (typically "id")
			var paramKey string
			for k := range dsRef.Params {
				paramKey = k
				break
			}
			buf.WriteString(fmt.Sprintf("  const { data: %s, isLoading: %sLoading } = %s(params.%s as string);\n", varName, varName, hookName, paramKey))
		} else {
			hookName := "use" + toPascalCase(dsRef.Alias)
			buf.WriteString(fmt.Sprintf("  const { data: %s, isLoading: %sLoading } = %s();\n", varName, varName, hookName))
		}
	}
	if len(page.DataSources) > 0 || imports.hasReact("useRouter") {
		buf.WriteString("\n")
	}

	buf.WriteString("  return (\n")
	buf.WriteString("    <div className=\"min-h-screen bg-background text-foreground font-sans\">\n")
	buf.Write(bodyBuf.Bytes())
	buf.WriteString("    </div>\n")
	buf.WriteString("  );\n")
	buf.WriteString("}\n")

	return []renderer.OutputFile{
		{Path: "pages/" + fileName, Content: buf.Bytes()},
	}, nil
}

func renderComponent(buf *bytes.Buffer, c *config.Component, depth int, imports *importTracker, ctx *renderer.RenderContext) {
	indent := strings.Repeat("  ", depth)

	switch c.Type {
	case "rows":
		gap := getPropString(c.Props, "gap", "4")
		padding := getPropString(c.Props, "padding", "0")
		align := getPropString(c.Props, "align", "")
		classes := fmt.Sprintf("flex flex-col gap-%s", gap)
		if padding != "0" {
			classes += fmt.Sprintf(" p-%s", padding)
		}
		if align == "center" {
			classes += " items-center"
		}
		fmt.Fprintf(buf, "%s<div className=%q>\n", indent, classes)
		for i := range c.Children {
			renderComponent(buf, &c.Children[i], depth+1, imports, ctx)
		}
		fmt.Fprintf(buf, "%s</div>\n", indent)

	case "columns":
		gap := getPropString(c.Props, "gap", "4")
		justify := getPropString(c.Props, "justify", "")
		align := getPropString(c.Props, "align", "")
		classes := fmt.Sprintf("flex flex-row gap-%s", gap)
		if justify == "between" {
			classes += " justify-between"
		} else if justify == "center" {
			classes += " justify-center"
		} else if justify == "end" {
			classes += " justify-end"
		}
		if align == "center" {
			classes += " items-center"
		}
		fmt.Fprintf(buf, "%s<div className=%q>\n", indent, classes)
		for i := range c.Children {
			renderComponent(buf, &c.Children[i], depth+1, imports, ctx)
		}
		fmt.Fprintf(buf, "%s</div>\n", indent)

	case "grid":
		cols := getPropString(c.Props, "columns", "3")
		colsMd := getPropString(c.Props, "columns_md", "")
		colsSm := getPropString(c.Props, "columns_sm", "")
		gap := getPropString(c.Props, "gap", "4")
		classes := fmt.Sprintf("grid grid-cols-%s gap-%s", cols, gap)
		if colsMd != "" {
			classes = fmt.Sprintf("grid grid-cols-%s md:grid-cols-%s gap-%s", colsMd, cols, gap)
		}
		if colsSm != "" {
			if colsMd != "" {
				classes = fmt.Sprintf("grid grid-cols-%s sm:grid-cols-%s md:grid-cols-%s gap-%s", colsSm, colsMd, cols, gap)
			} else {
				classes = fmt.Sprintf("grid grid-cols-%s md:grid-cols-%s gap-%s", colsSm, cols, gap)
			}
		}
		fmt.Fprintf(buf, "%s<div className=%q>\n", indent, classes)

		// If children use {{item.*}} template vars and a datasource is specified,
		// wrap the first child in a .map() iteration over the datasource array.
		dsAlias := getPropString(c.Props, "datasource", "")
		if dsAlias != "" && len(c.Children) > 0 && containsItemVars(&c.Children[0]) {
			varName := toCamelCase(dsAlias)
			keyField := getItemKeyField(&c.Children[0])
			fmt.Fprintf(buf, "%s  {%s.map((item) => (\n", indent, varName)
			fmt.Fprintf(buf, "%s    <div key={item.%s}>\n", indent, keyField)
			renderComponent(buf, &c.Children[0], depth+3, imports, ctx)
			fmt.Fprintf(buf, "%s    </div>\n", indent)
			fmt.Fprintf(buf, "%s  ))}\n", indent)
		} else {
			for i := range c.Children {
				renderComponent(buf, &c.Children[i], depth+1, imports, ctx)
			}
		}
		fmt.Fprintf(buf, "%s</div>\n", indent)

	case "heading":
		level := getPropString(c.Props, "level", "2")
		text := getPropString(c.Props, "text", "")
		tag := "h" + level
		classes := headingClasses(level)
		text = interpolateTemplateVars(text)
		fmt.Fprintf(buf, "%s<%s className=%q>%s</%s>\n", indent, tag, classes, text, tag)

	case "text":
		content := getPropString(c.Props, "text", "")
		muted := getPropBool(c.Props, "muted")
		classes := "text-base"
		if muted {
			classes = "text-sm text-muted-foreground"
		}
		content = interpolateTemplateVars(content)
		content = escapeJSXText(content)
		fmt.Fprintf(buf, "%s<p className=%q>%s</p>\n", indent, classes, content)

	case "button":
		imports.addShadcn("Button", "@/components/ui/button")
		label := getPropString(c.Props, "label", "Button")
		variant := getPropString(c.Props, "variant", "default")
		icon := getPropString(c.Props, "icon", "")
		disabled := getPropBool(c.Props, "disabled")

		// Map sigil variants to shadcn variants
		shadcnVariant := mapButtonVariant(variant)
		attrs := fmt.Sprintf("variant=%q", shadcnVariant)
		if disabled {
			attrs += " disabled"
		}
		attrs += renderReactActions(c.Actions, imports)

		if icon != "" {
			iconComp := lucideIconName(icon)
			imports.addLucide(iconComp)
			fmt.Fprintf(buf, "%s<Button %s>\n", indent, attrs)
			fmt.Fprintf(buf, "%s  <%s className=\"mr-2 h-4 w-4\" />\n", indent, iconComp)
			fmt.Fprintf(buf, "%s  %s\n", indent, label)
			fmt.Fprintf(buf, "%s</Button>\n", indent)
		} else {
			fmt.Fprintf(buf, "%s<Button %s>%s</Button>\n", indent, attrs, label)
		}

	case "badge":
		imports.addShadcn("Badge", "@/components/ui/badge")
		text := getPropString(c.Props, "text", "")
		variant := getPropString(c.Props, "variant", "default")
		text = interpolateTemplateVars(text)
		shadcnVariant, extraClass := mapBadgeVariant(variant)
		if extraClass != "" {
			fmt.Fprintf(buf, "%s<Badge variant=%q className=%q>%s</Badge>\n", indent, shadcnVariant, extraClass, text)
		} else {
			fmt.Fprintf(buf, "%s<Badge variant=%q>%s</Badge>\n", indent, shadcnVariant, text)
		}

	case "input":
		imports.addShadcn("Input", "@/components/ui/input")
		imports.addShadcn("Label", "@/components/ui/label")
		placeholder := getPropString(c.Props, "placeholder", "")
		inputType := getPropString(c.Props, "type", "text")
		required := getPropBool(c.Props, "required")
		id := c.ID
		if id == "" {
			id = "input-" + placeholder
		}
		reqAttr := ""
		if required {
			reqAttr = " required"
		}
		fmt.Fprintf(buf, "%s<div className=\"flex flex-col gap-1.5\">\n", indent)
		fmt.Fprintf(buf, "%s  <Input id=%q type=%q placeholder=%q%s />\n", indent, id, inputType, placeholder, reqAttr)
		fmt.Fprintf(buf, "%s</div>\n", indent)

	case "select":
		imports.addShadcn("Select", "@/components/ui/select")
		imports.addShadcn("SelectContent", "@/components/ui/select")
		imports.addShadcn("SelectItem", "@/components/ui/select")
		imports.addShadcn("SelectTrigger", "@/components/ui/select")
		imports.addShadcn("SelectValue", "@/components/ui/select")
		placeholder := getPropString(c.Props, "placeholder", "Select...")
		fmt.Fprintf(buf, "%s<Select>\n", indent)
		fmt.Fprintf(buf, "%s  <SelectTrigger>\n", indent)
		fmt.Fprintf(buf, "%s    <SelectValue placeholder=%q />\n", indent, placeholder)
		fmt.Fprintf(buf, "%s  </SelectTrigger>\n", indent)
		fmt.Fprintf(buf, "%s  <SelectContent>\n", indent)
		if opts, ok := c.Props["options"]; ok {
			if optSlice, ok := opts.([]interface{}); ok {
				for _, opt := range optSlice {
					if om, ok := opt.(map[string]interface{}); ok {
						val := fmt.Sprintf("%v", om["value"])
						lab := fmt.Sprintf("%v", om["label"])
						fmt.Fprintf(buf, "%s    <SelectItem value=%q>%s</SelectItem>\n", indent, val, lab)
					}
				}
			}
		}
		fmt.Fprintf(buf, "%s  </SelectContent>\n", indent)
		fmt.Fprintf(buf, "%s</Select>\n", indent)

	case "search-bar":
		imports.addShadcn("Input", "@/components/ui/input")
		imports.addLucide("Search")
		placeholder := getPropString(c.Props, "placeholder", "Search...")
		variant := getPropString(c.Props, "variant", "default")
		inputClasses := "w-full pl-9 [&::-webkit-search-cancel-button]:hidden [&::-webkit-search-decoration]:hidden"
		if variant == "ghost" {
			inputClasses = "w-full pl-9 border-0 shadow-none focus-visible:ring-0 [&::-webkit-search-cancel-button]:hidden [&::-webkit-search-decoration]:hidden"
		}
		fmt.Fprintf(buf, "%s<div className=\"relative\">\n", indent)
		fmt.Fprintf(buf, "%s  <Search className=\"absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground\" />\n", indent)
		fmt.Fprintf(buf, "%s  <Input type=\"search\" placeholder=%q className=%q />\n", indent, placeholder, inputClasses)
		fmt.Fprintf(buf, "%s</div>\n", indent)

	case "data-table":
		imports.addLocal("DataTable", "@/components/data-table")
		renderReactDataTable(buf, c, indent, imports, ctx)

	case "form":
		renderReactForm(buf, c, indent, depth, imports)

	case "modal":
		imports.addShadcn("Dialog", "@/components/ui/dialog")
		imports.addShadcn("DialogContent", "@/components/ui/dialog")
		imports.addShadcn("DialogHeader", "@/components/ui/dialog")
		imports.addShadcn("DialogTitle", "@/components/ui/dialog")
		title := getPropString(c.Props, "title", "")
		fmt.Fprintf(buf, "%s<Dialog>\n", indent)
		fmt.Fprintf(buf, "%s  <DialogContent>\n", indent)
		if title != "" {
			fmt.Fprintf(buf, "%s    <DialogHeader>\n", indent)
			fmt.Fprintf(buf, "%s      <DialogTitle>%s</DialogTitle>\n", indent, title)
			fmt.Fprintf(buf, "%s    </DialogHeader>\n", indent)
		}
		for i := range c.Children {
			renderComponent(buf, &c.Children[i], depth+2, imports, ctx)
		}
		fmt.Fprintf(buf, "%s  </DialogContent>\n", indent)
		fmt.Fprintf(buf, "%s</Dialog>\n", indent)

	case "sheet":
		imports.addShadcn("Sheet", "@/components/ui/sheet")
		imports.addShadcn("SheetContent", "@/components/ui/sheet")
		imports.addShadcn("SheetHeader", "@/components/ui/sheet")
		imports.addShadcn("SheetTitle", "@/components/ui/sheet")
		title := getPropString(c.Props, "title", "")
		side := getPropString(c.Props, "side", "right")
		fmt.Fprintf(buf, "%s<Sheet>\n", indent)
		fmt.Fprintf(buf, "%s  <SheetContent side=%q>\n", indent, side)
		if title != "" {
			fmt.Fprintf(buf, "%s    <SheetHeader>\n", indent)
			fmt.Fprintf(buf, "%s      <SheetTitle>%s</SheetTitle>\n", indent, title)
			fmt.Fprintf(buf, "%s    </SheetHeader>\n", indent)
		}
		for i := range c.Children {
			renderComponent(buf, &c.Children[i], depth+2, imports, ctx)
		}
		fmt.Fprintf(buf, "%s  </SheetContent>\n", indent)
		fmt.Fprintf(buf, "%s</Sheet>\n", indent)

	case "tabs":
		imports.addShadcn("Tabs", "@/components/ui/tabs")
		imports.addShadcn("TabsContent", "@/components/ui/tabs")
		imports.addShadcn("TabsList", "@/components/ui/tabs")
		imports.addShadcn("TabsTrigger", "@/components/ui/tabs")
		defaultTab := getPropString(c.Props, "defaultTab", "")
		if defaultTab == "" && len(c.Children) > 0 {
			defaultTab = getPropString(c.Children[0].Props, "value", c.Children[0].ID)
		}
		fmt.Fprintf(buf, "%s<Tabs defaultValue=%q>\n", indent, defaultTab)
		fmt.Fprintf(buf, "%s  <TabsList>\n", indent)
		for _, child := range c.Children {
			tabValue := getPropString(child.Props, "value", child.ID)
			label := getPropString(child.Props, "label", child.ID)
			fmt.Fprintf(buf, "%s    <TabsTrigger value=%q>%s</TabsTrigger>\n", indent, tabValue, label)
		}
		fmt.Fprintf(buf, "%s  </TabsList>\n", indent)
		for i := range c.Children {
			child := &c.Children[i]
			tabValue := getPropString(child.Props, "value", child.ID)
			fmt.Fprintf(buf, "%s  <TabsContent value=%q>\n", indent, tabValue)
			for j := range child.Children {
				renderComponent(buf, &child.Children[j], depth+2, imports, ctx)
			}
			fmt.Fprintf(buf, "%s  </TabsContent>\n", indent)
		}
		fmt.Fprintf(buf, "%s</Tabs>\n", indent)

	case "separator":
		imports.addShadcn("Separator", "@/components/ui/separator")
		fmt.Fprintf(buf, "%s<Separator />\n", indent)

	case "progress":
		imports.addShadcn("Progress", "@/components/ui/progress")
		value := getPropString(c.Props, "value", "0")
		fmt.Fprintf(buf, "%s<Progress value={%s} />\n", indent, value)

	case "avatar":
		imports.addShadcn("Avatar", "@/components/ui/avatar")
		imports.addShadcn("AvatarImage", "@/components/ui/avatar")
		imports.addShadcn("AvatarFallback", "@/components/ui/avatar")
		src := getPropString(c.Props, "src", "")
		alt := getPropString(c.Props, "alt", "")
		fallback := "?"
		if alt != "" && !strings.Contains(alt, "{{") && len(alt) >= 2 {
			fallback = strings.ToUpper(alt[:2])
		} else if strings.Contains(alt, "{{") {
			fallback = "?"
		}
		altOut := interpolateTemplateVars(alt)
		fmt.Fprintf(buf, "%s<Avatar>\n", indent)
		if strings.Contains(alt, "{{") {
			fmt.Fprintf(buf, "%s  <AvatarImage src=%q alt={%s} />\n", indent, src, strings.Trim(altOut, "{}"))
		} else {
			fmt.Fprintf(buf, "%s  <AvatarImage src=%q alt=%q />\n", indent, src, alt)
		}
		fmt.Fprintf(buf, "%s  <AvatarFallback>%s</AvatarFallback>\n", indent, fallback)
		fmt.Fprintf(buf, "%s</Avatar>\n", indent)

	case "alert":
		imports.addShadcn("Alert", "@/components/ui/alert")
		imports.addShadcn("AlertDescription", "@/components/ui/alert")
		message := getPropString(c.Props, "message", "")
		variant := getPropString(c.Props, "variant", "default")
		shadcnVariant := "default"
		if variant == "danger" || variant == "error" {
			shadcnVariant = "destructive"
		}
		fmt.Fprintf(buf, "%s<Alert variant=%q>\n", indent, shadcnVariant)
		fmt.Fprintf(buf, "%s  <AlertDescription>%s</AlertDescription>\n", indent, message)
		fmt.Fprintf(buf, "%s</Alert>\n", indent)

	case "icon":
		name := getPropString(c.Props, "name", "circle")
		iconComp := lucideIconName(name)
		imports.addLucide(iconComp)
		sizeClass := mapIconSize(getPropString(c.Props, "size", "md"))
		fmt.Fprintf(buf, "%s<%s className=%q />\n", indent, iconComp, sizeClass)

	case "label":
		imports.addShadcn("Label", "@/components/ui/label")
		text := getPropString(c.Props, "text", "")
		fmt.Fprintf(buf, "%s<Label>%s</Label>\n", indent, text)

	case "spacer":
		size := getPropString(c.Props, "size", "4")
		fmt.Fprintf(buf, "%s<div className=\"h-%s\" />\n", indent, size)

	case "card":
		imports.addShadcn("Card", "@/components/ui/card")
		imports.addShadcn("CardContent", "@/components/ui/card")
		imports.addShadcn("CardDescription", "@/components/ui/card")
		imports.addShadcn("CardFooter", "@/components/ui/card")
		imports.addShadcn("CardHeader", "@/components/ui/card")
		imports.addShadcn("CardTitle", "@/components/ui/card")
		title := interpolateTemplateVars(getPropString(c.Props, "title", ""))
		description := interpolateTemplateVars(getPropString(c.Props, "description", ""))
		border := getPropString(c.Props, "border", "true")
		if border == "false" {
			fmt.Fprintf(buf, "%s<Card className=\"border-0 shadow-none ring-0\">\n", indent)
		} else {
			fmt.Fprintf(buf, "%s<Card>\n", indent)
		}
		if title != "" || description != "" {
			fmt.Fprintf(buf, "%s  <CardHeader>\n", indent)
			if title != "" {
				fmt.Fprintf(buf, "%s    <CardTitle>%s</CardTitle>\n", indent, title)
			}
			if description != "" {
				fmt.Fprintf(buf, "%s    <CardDescription>%s</CardDescription>\n", indent, description)
			}
			fmt.Fprintf(buf, "%s  </CardHeader>\n", indent)
		}
		fmt.Fprintf(buf, "%s  <CardContent>\n", indent)
		for i := range c.Children {
			renderComponent(buf, &c.Children[i], depth+2, imports, ctx)
		}
		fmt.Fprintf(buf, "%s  </CardContent>\n", indent)
		fmt.Fprintf(buf, "%s</Card>\n", indent)

	case "switch":
		imports.addShadcn("Switch", "@/components/ui/switch")
		imports.addShadcn("Label", "@/components/ui/label")
		label := getPropString(c.Props, "label", "Toggle")
		disabled := getPropBool(c.Props, "disabled")
		defaultChecked := getPropBool(c.Props, "default")
		id := c.ID
		if id == "" {
			id = "switch-" + toKebabCase(label)
		}
		disabledAttr := ""
		if disabled {
			disabledAttr = " disabled"
		}
		defaultAttr := ""
		if defaultChecked {
			defaultAttr = " defaultChecked"
		}
		fmt.Fprintf(buf, "%s<div className=\"flex items-center space-x-2\">\n", indent)
		fmt.Fprintf(buf, "%s  <Switch id=%q%s%s />\n", indent, id, defaultAttr, disabledAttr)
		fmt.Fprintf(buf, "%s  <Label htmlFor=%q>%s</Label>\n", indent, id, label)
		fmt.Fprintf(buf, "%s</div>\n", indent)

	case "dropdown-menu":
		imports.addShadcn("DropdownMenu", "@/components/ui/dropdown-menu")
		imports.addShadcn("DropdownMenuContent", "@/components/ui/dropdown-menu")
		imports.addShadcn("DropdownMenuItem", "@/components/ui/dropdown-menu")
		imports.addShadcn("DropdownMenuTrigger", "@/components/ui/dropdown-menu")
		trigger := getPropString(c.Props, "trigger", "Open")
		fmt.Fprintf(buf, "%s<DropdownMenu>\n", indent)
		fmt.Fprintf(buf, "%s  <DropdownMenuTrigger className=\"inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium h-9 px-3 hover:bg-accent hover:text-accent-foreground\">%s</DropdownMenuTrigger>\n", indent, trigger)
		fmt.Fprintf(buf, "%s  <DropdownMenuContent>\n", indent)
		if items, ok := c.Props["items"]; ok {
			if itemSlice, ok := items.([]interface{}); ok {
				for _, item := range itemSlice {
					if im, ok := item.(map[string]interface{}); ok {
						if sep, ok := im["separator"]; ok && sep == true {
							imports.addShadcn("DropdownMenuSeparator", "@/components/ui/dropdown-menu")
							fmt.Fprintf(buf, "%s    <DropdownMenuSeparator />\n", indent)
							continue
						}
						label := fmt.Sprintf("%v", im["label"])
						icon := ""
						if iconVal, ok := im["icon"]; ok {
							icon = fmt.Sprintf("%v", iconVal)
						}
						if icon != "" {
							iconComp := lucideIconName(icon)
							imports.addLucide(iconComp)
							fmt.Fprintf(buf, "%s    <DropdownMenuItem>\n", indent)
							fmt.Fprintf(buf, "%s      <%s className=\"mr-2 h-4 w-4\" />\n", indent, iconComp)
							fmt.Fprintf(buf, "%s      %s\n", indent, label)
							fmt.Fprintf(buf, "%s    </DropdownMenuItem>\n", indent)
						} else {
							fmt.Fprintf(buf, "%s    <DropdownMenuItem>%s</DropdownMenuItem>\n", indent, label)
						}
					}
				}
			}
		}
		fmt.Fprintf(buf, "%s  </DropdownMenuContent>\n", indent)
		fmt.Fprintf(buf, "%s</DropdownMenu>\n", indent)

	case "accordion":
		imports.addShadcn("Accordion", "@/components/ui/accordion")
		imports.addShadcn("AccordionContent", "@/components/ui/accordion")
		imports.addShadcn("AccordionItem", "@/components/ui/accordion")
		imports.addShadcn("AccordionTrigger", "@/components/ui/accordion")
		fmt.Fprintf(buf, "%s<Accordion className=\"w-full\">\n", indent)
		for i := range c.Children {
			renderComponent(buf, &c.Children[i], depth+1, imports, ctx)
		}
		fmt.Fprintf(buf, "%s</Accordion>\n", indent)

	case "accordion-item":
		value := getPropString(c.Props, "value", c.ID)
		title := getPropString(c.Props, "title", "Section")
		fmt.Fprintf(buf, "%s<AccordionItem value=%q>\n", indent, value)
		fmt.Fprintf(buf, "%s  <AccordionTrigger>%s</AccordionTrigger>\n", indent, title)
		fmt.Fprintf(buf, "%s  <AccordionContent>\n", indent)
		for i := range c.Children {
			renderComponent(buf, &c.Children[i], depth+2, imports, ctx)
		}
		fmt.Fprintf(buf, "%s  </AccordionContent>\n", indent)
		fmt.Fprintf(buf, "%s</AccordionItem>\n", indent)

	case "combobox":
		imports.addLocal("Combobox", "@/components/combobox")
		placeholder := getPropString(c.Props, "placeholder", "Select...")
		searchPlaceholder := getPropString(c.Props, "searchPlaceholder", "Search...")
		emptyMessage := getPropString(c.Props, "emptyMessage", "No results found.")
		fmt.Fprintf(buf, "%s<Combobox\n", indent)
		fmt.Fprintf(buf, "%s  placeholder=%q\n", indent, placeholder)
		fmt.Fprintf(buf, "%s  searchPlaceholder=%q\n", indent, searchPlaceholder)
		fmt.Fprintf(buf, "%s  emptyMessage=%q\n", indent, emptyMessage)
		fmt.Fprintf(buf, "%s  options={[\n", indent)
		if opts, ok := c.Props["options"]; ok {
			if optSlice, ok := opts.([]interface{}); ok {
				for _, opt := range optSlice {
					if om, ok := opt.(map[string]interface{}); ok {
						val := fmt.Sprintf("%v", om["value"])
						lab := fmt.Sprintf("%v", om["label"])
						fmt.Fprintf(buf, "%s    { value: %q, label: %q },\n", indent, val, lab)
					}
				}
			}
		}
		fmt.Fprintf(buf, "%s  ]}\n", indent)
		fmt.Fprintf(buf, "%s/>\n", indent)

	case "tooltip":
		imports.addShadcn("Tooltip", "@/components/ui/tooltip")
		imports.addShadcn("TooltipContent", "@/components/ui/tooltip")
		imports.addShadcn("TooltipProvider", "@/components/ui/tooltip")
		imports.addShadcn("TooltipTrigger", "@/components/ui/tooltip")
		content := getPropString(c.Props, "content", "")
		side := getPropString(c.Props, "side", "top")
		fmt.Fprintf(buf, "%s<TooltipProvider>\n", indent)
		fmt.Fprintf(buf, "%s  <Tooltip>\n", indent)
		fmt.Fprintf(buf, "%s    <TooltipTrigger render={<span />}>\n", indent)
		if len(c.Children) > 0 {
			renderComponent(buf, &c.Children[0], depth+3, imports, ctx)
		}
		fmt.Fprintf(buf, "%s    </TooltipTrigger>\n", indent)
		fmt.Fprintf(buf, "%s    <TooltipContent side=%q>\n", indent, side)
		fmt.Fprintf(buf, "%s      <p>%s</p>\n", indent, content)
		fmt.Fprintf(buf, "%s    </TooltipContent>\n", indent)
		fmt.Fprintf(buf, "%s  </Tooltip>\n", indent)
		fmt.Fprintf(buf, "%s</TooltipProvider>\n", indent)

	case "sidebar":
		width := getPropString(c.Props, "width", "256px")
		idAttr := ""
		if c.ID != "" {
			idAttr = fmt.Sprintf(" id=%q", c.ID)
		}
		fmt.Fprintf(buf, "%s<div className=\"flex h-screen\"%s>\n", indent, idAttr)
		fmt.Fprintf(buf, "%s  <aside className=\"w-[%s] shrink-0 border-r border-border overflow-y-auto bg-muted/30\">\n", indent, width)
		if len(c.Children) > 0 {
			renderComponent(buf, &c.Children[0], depth+2, imports, ctx)
		}
		fmt.Fprintf(buf, "%s  </aside>\n", indent)
		fmt.Fprintf(buf, "%s  <main className=\"flex-1 overflow-y-auto\">\n", indent)
		if len(c.Children) > 1 {
			renderComponent(buf, &c.Children[1], depth+2, imports, ctx)
		}
		fmt.Fprintf(buf, "%s  </main>\n", indent)
		fmt.Fprintf(buf, "%s</div>\n", indent)

	case "nav-menu":
		idAttr := ""
		if c.ID != "" {
			idAttr = fmt.Sprintf(" id=%q", c.ID)
		}
		fmt.Fprintf(buf, "%s<nav className=\"flex flex-col gap-1\"%s>\n", indent, idAttr)
		if items, ok := c.Props["items"]; ok {
			if itemSlice, ok := items.([]interface{}); ok {
				for _, item := range itemSlice {
					if im, ok := item.(map[string]interface{}); ok {
						label := fmt.Sprintf("%v", im["label"])
						page := ""
						if p, ok := im["page"]; ok {
							page = fmt.Sprintf("%v", p)
						}
						icon := ""
						if ic, ok := im["icon"]; ok {
							icon = fmt.Sprintf("%v", ic)
						}
						href := "#"
						if page != "" {
							href = "/pages/" + page
						}
						if icon != "" {
							iconPascal := toPascalCase(icon)
							imports.addLucide(iconPascal)
							fmt.Fprintf(buf, "%s  <a href=%q className=\"flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium text-muted-foreground hover:bg-accent hover:text-accent-foreground transition-colors\">\n", indent, href)
							fmt.Fprintf(buf, "%s    <%s className=\"h-4 w-4\" />\n", indent, iconPascal)
							fmt.Fprintf(buf, "%s    %s\n", indent, label)
							fmt.Fprintf(buf, "%s  </a>\n", indent)
						} else {
							fmt.Fprintf(buf, "%s  <a href=%q className=\"flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium text-muted-foreground hover:bg-accent hover:text-accent-foreground transition-colors\">\n", indent, href)
							fmt.Fprintf(buf, "%s    %s\n", indent, label)
							fmt.Fprintf(buf, "%s  </a>\n", indent)
						}
					}
				}
			}
		}
		fmt.Fprintf(buf, "%s</nav>\n", indent)

	case "command-palette":
		imports.addShadcn("CommandDialog", "@/components/ui/command")
		imports.addShadcn("CommandInput", "@/components/ui/command")
		imports.addShadcn("CommandList", "@/components/ui/command")
		imports.addShadcn("CommandEmpty", "@/components/ui/command")
		imports.addShadcn("CommandGroup", "@/components/ui/command")
		imports.addShadcn("CommandItem", "@/components/ui/command")
		placeholder := getPropString(c.Props, "placeholder", "Type a command or search...")
		emptyMessage := getPropString(c.Props, "emptyMessage", "No results found.")
		fmt.Fprintf(buf, "%s<CommandDialog>\n", indent)
		fmt.Fprintf(buf, "%s  <CommandInput placeholder=%q />\n", indent, placeholder)
		fmt.Fprintf(buf, "%s  <CommandList>\n", indent)
		fmt.Fprintf(buf, "%s    <CommandEmpty>%s</CommandEmpty>\n", indent, emptyMessage)
		// Render groups from children
		for i := range c.Children {
			renderComponent(buf, &c.Children[i], depth+2, imports, ctx)
		}
		fmt.Fprintf(buf, "%s  </CommandList>\n", indent)
		fmt.Fprintf(buf, "%s</CommandDialog>\n", indent)

	case "command-group":
		imports.addShadcn("CommandGroup", "@/components/ui/command")
		imports.addShadcn("CommandItem", "@/components/ui/command")
		heading := getPropString(c.Props, "heading", "")
		fmt.Fprintf(buf, "%s<CommandGroup heading=%q>\n", indent, heading)
		if items, ok := c.Props["items"]; ok {
			if itemSlice, ok := items.([]interface{}); ok {
				for _, item := range itemSlice {
					if im, ok := item.(map[string]interface{}); ok {
						label := fmt.Sprintf("%v", im["label"])
						icon := ""
						if iconVal, ok := im["icon"]; ok {
							icon = fmt.Sprintf("%v", iconVal)
						}
						if icon != "" {
							iconComp := lucideIconName(icon)
							imports.addLucide(iconComp)
							fmt.Fprintf(buf, "%s  <CommandItem>\n", indent)
							fmt.Fprintf(buf, "%s    <%s className=\"mr-2 h-4 w-4\" />\n", indent, iconComp)
							fmt.Fprintf(buf, "%s    %s\n", indent, label)
							fmt.Fprintf(buf, "%s  </CommandItem>\n", indent)
						} else {
							fmt.Fprintf(buf, "%s  <CommandItem>%s</CommandItem>\n", indent, label)
						}
					}
				}
			}
		}
		fmt.Fprintf(buf, "%s</CommandGroup>\n", indent)

	case "dialog":
		imports.addShadcn("Dialog", "@/components/ui/dialog")
		imports.addShadcn("DialogContent", "@/components/ui/dialog")
		imports.addShadcn("DialogDescription", "@/components/ui/dialog")
		imports.addShadcn("DialogHeader", "@/components/ui/dialog")
		imports.addShadcn("DialogTitle", "@/components/ui/dialog")
		imports.addShadcn("DialogTrigger", "@/components/ui/dialog")
		title := getPropString(c.Props, "title", "")
		description := getPropString(c.Props, "description", "")
		triggerLabel := getPropString(c.Props, "trigger", "Open")
		triggerVariant := getPropString(c.Props, "triggerVariant", "default")
		imports.addShadcn("Button", "@/components/ui/button")
		fmt.Fprintf(buf, "%s<Dialog>\n", indent)
		fmt.Fprintf(buf, "%s  <DialogTrigger render={<Button variant=%q />}>\n", indent, triggerVariant)
		fmt.Fprintf(buf, "%s    %s\n", indent, triggerLabel)
		fmt.Fprintf(buf, "%s  </DialogTrigger>\n", indent)
		fmt.Fprintf(buf, "%s  <DialogContent>\n", indent)
		if title != "" || description != "" {
			fmt.Fprintf(buf, "%s    <DialogHeader>\n", indent)
			if title != "" {
				fmt.Fprintf(buf, "%s      <DialogTitle>%s</DialogTitle>\n", indent, title)
			}
			if description != "" {
				fmt.Fprintf(buf, "%s      <DialogDescription>%s</DialogDescription>\n", indent, description)
			}
			fmt.Fprintf(buf, "%s    </DialogHeader>\n", indent)
		}
		for i := range c.Children {
			renderComponent(buf, &c.Children[i], depth+3, imports, ctx)
		}
		fmt.Fprintf(buf, "%s  </DialogContent>\n", indent)
		fmt.Fprintf(buf, "%s</Dialog>\n", indent)

	case "radio-group":
		imports.addShadcn("RadioGroup", "@/components/ui/radio-group")
		imports.addShadcn("RadioGroupItem", "@/components/ui/radio-group")
		imports.addShadcn("Label", "@/components/ui/label")
		defaultValue := getPropString(c.Props, "defaultValue", "")
		fmt.Fprintf(buf, "%s<RadioGroup defaultValue=%q>\n", indent, defaultValue)
		if opts, ok := c.Props["options"]; ok {
			if optSlice, ok := opts.([]interface{}); ok {
				for _, opt := range optSlice {
					if om, ok := opt.(map[string]interface{}); ok {
						val := fmt.Sprintf("%v", om["value"])
						lab := fmt.Sprintf("%v", om["label"])
						fmt.Fprintf(buf, "%s  <div className=\"flex items-center gap-2\">\n", indent)
						fmt.Fprintf(buf, "%s    <RadioGroupItem value=%q id=%q />\n", indent, val, val)
						fmt.Fprintf(buf, "%s    <Label htmlFor=%q>%s</Label>\n", indent, val, lab)
						fmt.Fprintf(buf, "%s  </div>\n", indent)
					}
				}
			}
		}
		fmt.Fprintf(buf, "%s</RadioGroup>\n", indent)

	case "breadcrumb":
		imports.addShadcn("Breadcrumb", "@/components/ui/breadcrumb")
		imports.addShadcn("BreadcrumbItem", "@/components/ui/breadcrumb")
		imports.addShadcn("BreadcrumbLink", "@/components/ui/breadcrumb")
		imports.addShadcn("BreadcrumbList", "@/components/ui/breadcrumb")
		imports.addShadcn("BreadcrumbPage", "@/components/ui/breadcrumb")
		imports.addShadcn("BreadcrumbSeparator", "@/components/ui/breadcrumb")
		fmt.Fprintf(buf, "%s<Breadcrumb>\n", indent)
		fmt.Fprintf(buf, "%s  <BreadcrumbList>\n", indent)
		if items, ok := c.Props["items"]; ok {
			if itemSlice, ok := items.([]interface{}); ok {
				for i, item := range itemSlice {
					if im, ok := item.(map[string]interface{}); ok {
						label := interpolateTemplateVars(fmt.Sprintf("%v", im["label"]))
						href := ""
						if h, ok := im["href"]; ok {
							href = fmt.Sprintf("%v", h)
						}
						isLast := i == len(itemSlice)-1
						fmt.Fprintf(buf, "%s    <BreadcrumbItem>\n", indent)
						if isLast {
							fmt.Fprintf(buf, "%s      <BreadcrumbPage>%s</BreadcrumbPage>\n", indent, label)
						} else {
							fmt.Fprintf(buf, "%s      <BreadcrumbLink href=%q>%s</BreadcrumbLink>\n", indent, href, label)
						}
						fmt.Fprintf(buf, "%s    </BreadcrumbItem>\n", indent)
						if !isLast {
							fmt.Fprintf(buf, "%s    <BreadcrumbSeparator />\n", indent)
						}
					}
				}
			}
		}
		fmt.Fprintf(buf, "%s  </BreadcrumbList>\n", indent)
		fmt.Fprintf(buf, "%s</Breadcrumb>\n", indent)

	case "popover":
		imports.addShadcn("Popover", "@/components/ui/popover")
		imports.addShadcn("PopoverContent", "@/components/ui/popover")
		imports.addShadcn("PopoverTrigger", "@/components/ui/popover")
		triggerLabel := interpolateTemplateVars(getPropString(c.Props, "trigger", "Info"))
		side := getPropString(c.Props, "side", "bottom")
		fmt.Fprintf(buf, "%s<Popover>\n", indent)
		fmt.Fprintf(buf, "%s  <PopoverTrigger>%s</PopoverTrigger>\n", indent, triggerLabel)
		fmt.Fprintf(buf, "%s  <PopoverContent side=%q>\n", indent, side)
		for i := range c.Children {
			renderComponent(buf, &c.Children[i], depth+2, imports, ctx)
		}
		fmt.Fprintf(buf, "%s  </PopoverContent>\n", indent)
		fmt.Fprintf(buf, "%s</Popover>\n", indent)

	case "collapsible":
		imports.addShadcn("Collapsible", "@/components/ui/collapsible")
		imports.addShadcn("CollapsibleContent", "@/components/ui/collapsible")
		imports.addShadcn("CollapsibleTrigger", "@/components/ui/collapsible")
		imports.addLucide("ChevronsUpDown")
		title := getPropString(c.Props, "title", "Toggle")
		fmt.Fprintf(buf, "%s<Collapsible>\n", indent)
		fmt.Fprintf(buf, "%s  <div className=\"flex items-center justify-between\">\n", indent)
		fmt.Fprintf(buf, "%s    <h4 className=\"text-sm font-semibold\">%s</h4>\n", indent, title)
		fmt.Fprintf(buf, "%s    <CollapsibleTrigger>\n", indent)
		fmt.Fprintf(buf, "%s      <ChevronsUpDown className=\"h-4 w-4\" />\n", indent)
		fmt.Fprintf(buf, "%s    </CollapsibleTrigger>\n", indent)
		fmt.Fprintf(buf, "%s  </div>\n", indent)
		fmt.Fprintf(buf, "%s  <CollapsibleContent>\n", indent)
		for i := range c.Children {
			renderComponent(buf, &c.Children[i], depth+2, imports, ctx)
		}
		fmt.Fprintf(buf, "%s  </CollapsibleContent>\n", indent)
		fmt.Fprintf(buf, "%s</Collapsible>\n", indent)

	case "toggle-group":
		imports.addShadcn("ToggleGroup", "@/components/ui/toggle-group")
		imports.addShadcn("ToggleGroupItem", "@/components/ui/toggle-group")
		variant := getPropString(c.Props, "variant", "outline")
		fmt.Fprintf(buf, "%s<ToggleGroup variant=%q>\n", indent, variant)
		if opts, ok := c.Props["options"]; ok {
			if optSlice, ok := opts.([]interface{}); ok {
				for _, opt := range optSlice {
					if om, ok := opt.(map[string]interface{}); ok {
						val := fmt.Sprintf("%v", om["value"])
						lab := fmt.Sprintf("%v", om["label"])
						fmt.Fprintf(buf, "%s  <ToggleGroupItem value=%q>%s</ToggleGroupItem>\n", indent, val, lab)
					}
				}
			}
		}
		fmt.Fprintf(buf, "%s</ToggleGroup>\n", indent)

	default:
		idAttr := ""
		if c.ID != "" {
			idAttr = fmt.Sprintf(" id=%q", c.ID)
		}
		fmt.Fprintf(buf, "%s<div data-component=%q%s>\n", indent, c.Type, idAttr)
		for i := range c.Children {
			renderComponent(buf, &c.Children[i], depth+1, imports, ctx)
		}
		fmt.Fprintf(buf, "%s</div>\n", indent)
	}
}

func renderReactDataTable(buf *bytes.Buffer, c *config.Component, indent string, imports *importTracker, ctx *renderer.RenderContext) {
	datasource := getPropString(c.Props, "datasource", "")

	// Build column definitions
	fmt.Fprintf(buf, "%s<DataTable\n", indent)
	if datasource != "" {
		varName := toCamelCase(datasource)
		fmt.Fprintf(buf, "%s  data={%s ?? []}\n", indent, varName)
	} else {
		fmt.Fprintf(buf, "%s  data={[]}\n", indent)
	}

	// Columns
	fmt.Fprintf(buf, "%s  columns={[\n", indent)
	if cols, ok := c.Props["columns"]; ok {
		if colSlice, ok := cols.([]interface{}); ok {
			for _, col := range colSlice {
				if colMap, ok := col.(map[string]interface{}); ok {
					field := fmt.Sprintf("%v", colMap["field"])
					label := fmt.Sprintf("%v", colMap["label"])
					fmt.Fprintf(buf, "%s    { accessorKey: %q, header: %q },\n", indent, field, label)
				}
			}
		}
	}
	fmt.Fprintf(buf, "%s  ]}\n", indent)
	fmt.Fprintf(buf, "%s/>\n", indent)
}

func renderReactForm(buf *bytes.Buffer, c *config.Component, indent string, depth int, imports *importTracker) {
	imports.addShadcn("Button", "@/components/ui/button")
	imports.addShadcn("Input", "@/components/ui/input")
	imports.addShadcn("Label", "@/components/ui/label")

	actions := renderReactActions(c.Actions, imports)
	fmt.Fprintf(buf, "%s<form className=\"flex flex-col gap-4 max-w-lg\"%s>\n", indent, actions)

	if fields, ok := c.Props["fields"]; ok {
		if fieldSlice, ok := fields.([]interface{}); ok {
			for _, f := range fieldSlice {
				if fm, ok := f.(map[string]interface{}); ok {
					name := fmt.Sprintf("%v", fm["name"])
					label := fmt.Sprintf("%v", fm["label"])
					fieldType := fmt.Sprintf("%v", fm["type"])
					placeholder := ""
					if p, ok := fm["placeholder"]; ok {
						placeholder = fmt.Sprintf("%v", p)
					}
					required := false
					if r, ok := fm["required"]; ok {
						required, _ = r.(bool)
					}

					reqAttr := ""
					if required {
						reqAttr = " required"
					}

					fmt.Fprintf(buf, "%s  <div className=\"flex flex-col gap-1.5\">\n", indent)
					fmt.Fprintf(buf, "%s    <Label htmlFor=%q>%s</Label>\n", indent, name, label)

					switch fieldType {
					case "textarea":
						imports.addShadcn("Textarea", "@/components/ui/textarea")
						rows := "3"
						if r, ok := fm["rows"]; ok {
							rows = fmt.Sprintf("%v", r)
						}
						fmt.Fprintf(buf, "%s    <Textarea id=%q name=%q placeholder=%q rows={%s}%s />\n",
							indent, name, name, placeholder, rows, reqAttr)
					case "select":
						imports.addShadcn("Select", "@/components/ui/select")
						imports.addShadcn("SelectContent", "@/components/ui/select")
						imports.addShadcn("SelectItem", "@/components/ui/select")
						imports.addShadcn("SelectTrigger", "@/components/ui/select")
						imports.addShadcn("SelectValue", "@/components/ui/select")
						fmt.Fprintf(buf, "%s    <Select name=%q>\n", indent, name)
						fmt.Fprintf(buf, "%s      <SelectTrigger>\n", indent)
						fmt.Fprintf(buf, "%s        <SelectValue placeholder=\"Select...\" />\n", indent)
						fmt.Fprintf(buf, "%s      </SelectTrigger>\n", indent)
						fmt.Fprintf(buf, "%s      <SelectContent>\n", indent)
						if opts, ok := fm["options"]; ok {
							if optSlice, ok := opts.([]interface{}); ok {
								for _, opt := range optSlice {
									if om, ok := opt.(map[string]interface{}); ok {
										val := fmt.Sprintf("%v", om["value"])
										lab := fmt.Sprintf("%v", om["label"])
										fmt.Fprintf(buf, "%s        <SelectItem value=%q>%s</SelectItem>\n", indent, val, lab)
									}
								}
							}
						}
						fmt.Fprintf(buf, "%s      </SelectContent>\n", indent)
						fmt.Fprintf(buf, "%s    </Select>\n", indent)
					case "checkbox":
						imports.addShadcn("Checkbox", "@/components/ui/checkbox")
						fmt.Fprintf(buf, "%s    <Checkbox id=%q />\n", indent, name)
					default:
						fmt.Fprintf(buf, "%s    <Input id=%q name=%q type=%q placeholder=%q%s />\n",
							indent, name, name, fieldType, placeholder, reqAttr)
					}

					fmt.Fprintf(buf, "%s  </div>\n", indent)
				}
			}
		}
	}

	// Submit button
	submitLabel := "Submit"
	if submit, ok := c.Props["submit"]; ok {
		if sm, ok := submit.(map[string]interface{}); ok {
			if l, ok := sm["label"]; ok {
				submitLabel = fmt.Sprintf("%v", l)
			}
		}
	}
	fmt.Fprintf(buf, "%s  <Button type=\"submit\">%s</Button>\n", indent, submitLabel)
	fmt.Fprintf(buf, "%s</form>\n", indent)
}

func renderReactActions(actions map[string]config.Action, imports *importTracker) string {
	if len(actions) == 0 {
		return ""
	}

	var attrs []string
	for _, action := range actions {
		switch action.Type {
		case "navigate":
			imports.addReact("useRouter", "next/navigation")
			if action.URL != "" {
				url := interpolateActionURL(action.URL)
				attrs = append(attrs, fmt.Sprintf(` onClick={() => router.push(%s)}`, url))
			} else if action.Page != "" {
				attrs = append(attrs, fmt.Sprintf(` onClick={() => router.push("/%s")}`, action.Page))
			}
		case "http":
			method := strings.ToUpper(action.Method)
			if method == "" {
				method = "POST"
			}
			url := interpolateActionURL(action.URL)
			attrs = append(attrs, fmt.Sprintf(` onClick={() => fetch(%s, { method: %q })}`, url, method))
		case "filter":
			// Filter emits a custom event with datasource + field + value for filtering
			ds := action.Datasource
			field := action.Field
			if ds != "" && field != "" {
				attrs = append(attrs, fmt.Sprintf(` onChange={(e) => window.dispatchEvent(new CustomEvent("filter:%s", { detail: { field: %q, value: e.target.value } }))}`, strings.ToLower(ds), field))
			}
		case "create":
			// Create navigates to a create page or opens a modal
			imports.addReact("useRouter", "next/navigation")
			if action.Page != "" {
				attrs = append(attrs, fmt.Sprintf(` onClick={() => router.push("/%s/new")}`, action.Page))
			} else if action.URL != "" {
				url := interpolateActionURL(action.URL)
				attrs = append(attrs, fmt.Sprintf(` onClick={() => router.push(%s)}`, url))
			}
		case "emit":
			if action.Event != "" {
				attrs = append(attrs, fmt.Sprintf(` onClick={() => window.dispatchEvent(new CustomEvent(%q))}`, action.Event))
			} else if action.Datasource != "" && action.Field != "" {
				// emit with datasource/field acts as a filter event
				attrs = append(attrs, fmt.Sprintf(` onChange={(e) => window.dispatchEvent(new CustomEvent("filter:%s", { detail: { field: %q, value: e.target.value } }))}`, strings.ToLower(action.Datasource), action.Field))
			}
		case "confirm":
			if action.Message != "" {
				attrs = append(attrs, fmt.Sprintf(` onClick={() => { if (window.confirm(%q)) { /* action */ } }}`, action.Message))
			}
		case "close":
			attrs = append(attrs, ` onClick={() => setOpen(false)}`)
		}
	}
	return strings.Join(attrs, "")
}

// importTracker collects and deduplicates imports for a TSX file.
type importTracker struct {
	// module -> set of named imports
	shadcn map[string]map[string]bool
	lucide map[string]bool
	react  map[string]map[string]bool
	local  map[string]map[string]bool
}

func newImportTracker() *importTracker {
	return &importTracker{
		shadcn: map[string]map[string]bool{},
		lucide: map[string]bool{},
		react:  map[string]map[string]bool{},
		local:  map[string]map[string]bool{},
	}
}

func (t *importTracker) addShadcn(name, module string) {
	if t.shadcn[module] == nil {
		t.shadcn[module] = map[string]bool{}
	}
	t.shadcn[module][name] = true
}

func (t *importTracker) addLucide(name string) {
	t.lucide[name] = true
}

func (t *importTracker) addReact(name, module string) {
	if t.react[module] == nil {
		t.react[module] = map[string]bool{}
	}
	t.react[module][name] = true
}

func (t *importTracker) hasReact(name string) bool {
	for _, names := range t.react {
		if names[name] {
			return true
		}
	}
	return false
}

func (t *importTracker) addLocal(name, module string) {
	if t.local[module] == nil {
		t.local[module] = map[string]bool{}
	}
	t.local[module][name] = true
}

func (t *importTracker) String() string {
	var buf bytes.Buffer

	// React/framework imports
	writeImportGroup(&buf, t.react)

	// Lucide icons
	if len(t.lucide) > 0 {
		names := sortedBoolKeys(t.lucide)
		buf.WriteString(fmt.Sprintf("import { %s } from \"lucide-react\";\n", strings.Join(names, ", ")))
	}

	// shadcn imports
	writeImportGroup(&buf, t.shadcn)

	// Local imports
	writeImportGroup(&buf, t.local)

	return buf.String()
}

func writeImportGroup(buf *bytes.Buffer, group map[string]map[string]bool) {
	if len(group) == 0 {
		return
	}
	modules := make([]string, 0, len(group))
	for m := range group {
		modules = append(modules, m)
	}
	sort.Strings(modules)
	for _, mod := range modules {
		names := sortedBoolKeys(group[mod])
		buf.WriteString(fmt.Sprintf("import { %s } from %q;\n", strings.Join(names, ", "), mod))
	}
}

func sortedBoolKeys(m map[string]bool) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// interpolateTemplateVars converts Sigil template variables in a string to JSX expressions.
// Patterns:
//   - {{data.Alias.field}} → alias?.field  (camelCase alias with optional chaining)
//   - {{param.field}}      → params.field
//
// If the entire string is a single template variable, returns a JSX expression like {expr}.
// If the string mixes static text and template variables, returns a JSX template literal like {`text ${expr}`}.
func interpolateTemplateVars(s string) string {
	if !strings.Contains(s, "{{") {
		return s
	}

	dataRe := regexp.MustCompile(`\{\{data\.([A-Za-z_][A-Za-z0-9_]*)\.([A-Za-z_][A-Za-z0-9_]*)\}\}`)
	paramRe := regexp.MustCompile(`\{\{param\.([A-Za-z_][A-Za-z0-9_]*)\}\}`)
	itemRe := regexp.MustCompile(`\{\{item\.([A-Za-z_][A-Za-z0-9_]*)\}\}`)

	// Check if the entire string is a single template variable
	singleDataMatch := dataRe.FindStringSubmatch(s)
	if singleDataMatch != nil && singleDataMatch[0] == s {
		alias := toCamelCase(singleDataMatch[1])
		field := singleDataMatch[2]
		return "{" + alias + "?." + field + "}"
	}
	singleParamMatch := paramRe.FindStringSubmatch(s)
	if singleParamMatch != nil && singleParamMatch[0] == s {
		return "{params." + singleParamMatch[1] + "}"
	}
	singleItemMatch := itemRe.FindStringSubmatch(s)
	if singleItemMatch != nil && singleItemMatch[0] == s {
		return "{item." + singleItemMatch[1] + "}"
	}

	// Mixed content: replace all template vars and wrap in a template literal
	result := s
	result = dataRe.ReplaceAllStringFunc(result, func(match string) string {
		parts := dataRe.FindStringSubmatch(match)
		alias := toCamelCase(parts[1])
		field := parts[2]
		return "${" + alias + "?." + field + "}"
	})
	result = paramRe.ReplaceAllStringFunc(result, func(match string) string {
		parts := paramRe.FindStringSubmatch(match)
		return "${params." + parts[1] + "}"
	})
	result = itemRe.ReplaceAllStringFunc(result, func(match string) string {
		parts := itemRe.FindStringSubmatch(match)
		return "${item." + parts[1] + "}"
	})
	return "{`" + result + "`}"
}

// containsItemVars recursively checks whether a component tree contains any
// {{item.*}} template variables, indicating it should be rendered inside a
// datasource .map() iteration.
func containsItemVars(c *config.Component) bool {
	for _, v := range c.Props {
		if s, ok := v.(string); ok && strings.Contains(s, "{{item.") {
			return true
		}
	}
	for i := range c.Children {
		if containsItemVars(&c.Children[i]) {
			return true
		}
	}
	return false
}

// getItemKeyField extracts the first {{item.*}} field name from a component
// tree, to be used as the key prop in a .map() call. Falls back to "id".
func getItemKeyField(c *config.Component) string {
	re := regexp.MustCompile(`\{\{item\.([A-Za-z_][A-Za-z0-9_]*)\}\}`)
	for _, v := range c.Props {
		if s, ok := v.(string); ok {
			if m := re.FindStringSubmatch(s); m != nil {
				return m[1]
			}
		}
	}
	for i := range c.Children {
		if f := getItemKeyField(&c.Children[i]); f != "id" {
			return f
		}
	}
	return "id"
}

// Helper functions

func getPropString(props map[string]interface{}, key, defaultVal string) string {
	if v, ok := props[key]; ok {
		return fmt.Sprintf("%v", v)
	}
	return defaultVal
}

func getPropBool(props map[string]interface{}, key string) bool {
	if v, ok := props[key]; ok {
		if b, ok := v.(bool); ok {
			return b
		}
	}
	return false
}

func headingClasses(level string) string {
	switch level {
	case "1":
		return "scroll-m-20 text-4xl font-extrabold tracking-tight text-foreground"
	case "2":
		return "scroll-m-20 text-3xl font-semibold tracking-tight text-foreground"
	case "3":
		return "scroll-m-20 text-2xl font-semibold tracking-tight text-foreground"
	case "4":
		return "scroll-m-20 text-xl font-semibold tracking-tight text-foreground"
	default:
		return "scroll-m-20 text-3xl font-semibold tracking-tight text-foreground"
	}
}

func mapButtonVariant(variant string) string {
	switch variant {
	case "primary":
		return "default"
	case "secondary":
		return "secondary"
	case "destructive":
		return "destructive"
	case "outline":
		return "outline"
	case "ghost":
		return "ghost"
	default:
		return "default"
	}
}

// mapIconSize maps Sigil icon size names (or pixel values) to Tailwind size classes.
func mapIconSize(size string) string {
	switch size {
	case "xs":
		return "h-3 w-3"
	case "sm":
		return "h-4 w-4"
	case "md", "":
		return "h-5 w-5"
	case "lg":
		return "h-6 w-6"
	case "xl":
		return "h-8 w-8"
	default:
		// Accept pixel values like "16" or "20" — convert to nearest Tailwind size
		return fmt.Sprintf("h-[%spx] w-[%spx]", size, size)
	}
}

// interpolateActionURL converts template vars in action URLs to JS template literals.
// e.g. "/api/deployments/{{param.id}}" → "`/api/deployments/${params.id}`"
// Returns a raw JS expression (no JSX {} wrapper) suitable for use inside onClick handlers.
func interpolateActionURL(url string) string {
	if !strings.Contains(url, "{{") {
		return fmt.Sprintf("%q", url)
	}
	paramRe := regexp.MustCompile(`\{\{param\.([A-Za-z_][A-Za-z0-9_]*)\}\}`)
	dataRe := regexp.MustCompile(`\{\{data\.([A-Za-z_][A-Za-z0-9_]*)\.([A-Za-z_][A-Za-z0-9_]*)\}\}`)
	itemRe := regexp.MustCompile(`\{\{item\.([A-Za-z_][A-Za-z0-9_]*)\}\}`)

	result := url
	result = paramRe.ReplaceAllString(result, "${params.$1}")
	result = dataRe.ReplaceAllStringFunc(result, func(match string) string {
		parts := dataRe.FindStringSubmatch(match)
		alias := toCamelCase(parts[1])
		return "${" + alias + "?." + parts[2] + "}"
	})
	result = itemRe.ReplaceAllString(result, "${item.$1}")
	return "`" + result + "`"
}

// escapeJSXText escapes characters that are special in JSX but should render
// as literal text. Skips content that's already a JSX expression ({...} or {`...`}).
func escapeJSXText(s string) string {
	if strings.HasPrefix(s, "{") {
		return s // already a JSX expression, don't double-escape
	}
	replacer := strings.NewReplacer(
		"<", "{\"<\"}",
		">", "{\">\"}",
	)
	return replacer.Replace(s)
}

// mapBadgeVariant maps Sigil semantic badge variants to a shadcn base variant
// plus an optional Tailwind className for semantic color. This preserves visual
// distinction between success/warning/info instead of collapsing them.
func mapBadgeVariant(variant string) (shadcnVariant, className string) {
	switch variant {
	case "success":
		return "outline", "border-emerald-500/30 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400"
	case "warning":
		return "outline", "border-amber-500/30 bg-amber-500/10 text-amber-600 dark:text-amber-400"
	case "danger", "error":
		return "destructive", ""
	case "info":
		return "outline", "border-blue-500/30 bg-blue-500/10 text-blue-600 dark:text-blue-400"
	default:
		return variant, ""
	}
}

func toKebabCase(s string) string {
	return strings.ReplaceAll(strings.ToLower(s), "_", "-")
}

// lucideIconName maps Sigil icon names to their Lucide React export names.
// Only icons that differ from a simple PascalCase conversion need to be listed.
var lucideIconAliases = map[string]string{
	"refresh":     "RefreshCw",
	"delete":      "Trash2",
	"edit":        "Pencil",
	"close":       "X",
	"add":         "Plus",
	"remove":      "Minus",
	"arrow-left":  "ArrowLeft",
	"arrow-right": "ArrowRight",
}

func lucideIconName(name string) string {
	if alias, ok := lucideIconAliases[name]; ok {
		return alias
	}
	return toPascalCase(name)
}

func toPascalCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '-' || r == '_' || r == ' '
	})
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func toCamelCase(s string) string {
	pascal := toPascalCase(s)
	if len(pascal) == 0 {
		return pascal
	}
	return strings.ToLower(pascal[:1]) + pascal[1:]
}
