package reactshadcn

import (
	"fmt"
	"strings"

	"github.com/chrispian/sigil/internal/config"
	"github.com/chrispian/sigil/internal/renderer"
)

// pluralize adds an "s" to a word, handling common English patterns.
func pluralize(s string) string {
	if strings.HasSuffix(s, "s") || strings.HasSuffix(s, "sh") || strings.HasSuffix(s, "ch") || strings.HasSuffix(s, "x") || strings.HasSuffix(s, "z") {
		return s + "es"
	}
	if strings.HasSuffix(s, "y") && len(s) > 1 {
		c := s[len(s)-2]
		if c != 'a' && c != 'e' && c != 'i' && c != 'o' && c != 'u' {
			return s[:len(s)-1] + "ies"
		}
	}
	return s + "s"
}

// renderProviders generates React Context + Provider files for each provider in the app config.
func renderProviders(providers []config.ProviderConfig) ([]renderer.OutputFile, error) {
	var files []renderer.OutputFile
	for _, p := range providers {
		file, err := renderProvider(p)
		if err != nil {
			return nil, err
		}
		files = append(files, file)
	}
	return files, nil
}

func renderProvider(p config.ProviderConfig) (renderer.OutputFile, error) { //nolint:unparam // error kept for interface consistency
	id := p.ID
	typeName := toPascalCase(p.Datasource)
	providerName := toPascalCase(id) + "Provider"
	hookName := "use" + toPascalCase(id) + "Context"
	trackField := p.TrackField
	if trackField == "" {
		trackField = "id"
	}
	labelField := p.LabelField
	if labelField == "" {
		labelField = "name"
	}
	defaultVal := p.Default
	if defaultVal == "" {
		defaultVal = ""
	}

	resource := pluralize(strings.ToLower(p.Datasource))

	content := fmt.Sprintf(`// Generated by Sigil — do not edit manually
"use client";

import { createContext, useContext, useEffect, useState, type ReactNode } from "react";
import { fetchList } from "@/lib/api";

interface %s {
  %s: string;
  %s: string;
  [key: string]: unknown;
}

interface %sContextValue {
  current%sId: string;
  current%sName: string;
  set%sId: (id: string) => void;
  %s: %s[];
  isLoading: boolean;
}

const %sContext = createContext<%sContextValue>({
  current%sId: %q,
  current%sName: "",
  set%sId: () => {},
  %s: [],
  isLoading: true,
});

export function %s() {
  return useContext(%sContext);
}

export function %s({ children }: { children: ReactNode }) {
  const [items, setItems] = useState<%s[]>([]);
  const [currentId, setCurrentId] = useState(%q);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    fetchList<%s>(%q)
      .then((data) => {
        setItems(data);
        if (data.length > 0 && !currentId) setCurrentId(String(data[0].%s));
      })
      .catch(() => setItems([]))
      .finally(() => setIsLoading(false));
  }, []);

  const currentName = items.find((item) => String(item.%s) === currentId)?.%s ?? "";

  return (
    <%sContext value={{
      current%sId: currentId,
      current%sName: currentName,
      set%sId: setCurrentId,
      %s: items,
      isLoading,
    }}>
      {children}
    </%sContext>
  );
}
`,
		// Interface fields
		typeName, trackField, labelField,
		// Context value interface
		toPascalCase(id), toPascalCase(id), toPascalCase(id),
		toPascalCase(id),
		pluralize(toCamelCase(p.Datasource)), typeName,
		// Context default
		toPascalCase(id), toPascalCase(id),
		toPascalCase(id), defaultVal,
		toPascalCase(id),
		toPascalCase(id),
		pluralize(toCamelCase(p.Datasource)),
		// Hook
		hookName, toPascalCase(id),
		// Provider function
		providerName, typeName,
		defaultVal,
		// useEffect
		typeName, resource,
		trackField,
		// currentName
		trackField, labelField,
		// JSX
		toPascalCase(id),
		toPascalCase(id), toPascalCase(id), toPascalCase(id),
		pluralize(toCamelCase(p.Datasource)),
		toPascalCase(id),
	)

	fileName := fmt.Sprintf("lib/%s-context.tsx", toKebabCase(id))
	return renderer.OutputFile{
		Path:    fileName,
		Content: []byte(content),
	}, nil
}
