package reactshadcn

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/chrispian/sigil/internal/renderer"
)

// renderTheme generates Tailwind config and global CSS from theme tokens.
func renderTheme(theme *renderer.ThemeConfig) ([]renderer.OutputFile, error) {
	var files []renderer.OutputFile

	css, err := generateGlobalsCSS(theme)
	if err != nil {
		return nil, err
	}
	files = append(files, renderer.OutputFile{
		Path:    "globals.css",
		Content: css,
	})

	tailwind, err := generateTailwindConfig(theme)
	if err != nil {
		return nil, err
	}
	files = append(files, renderer.OutputFile{
		Path:    "tailwind.config.ts",
		Content: tailwind,
	})

	return files, nil
}

func generateGlobalsCSS(theme *renderer.ThemeConfig) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("/* globals.css — generated by Sigil, do not edit */\n")
	buf.WriteString("@tailwind base;\n")
	buf.WriteString("@tailwind components;\n")
	buf.WriteString("@tailwind utilities;\n\n")

	buf.WriteString("@layer base {\n")
	buf.WriteString("  :root {\n")

	// Write token categories in stable order
	categories := []string{"colors", "typography", "spacing", "radius", "shadows"}
	for _, cat := range categories {
		tokens, ok := theme.Tokens[cat]
		if !ok || len(tokens) == 0 {
			continue
		}

		label := strings.ToUpper(cat[:1]) + cat[1:]
		buf.WriteString(fmt.Sprintf("\n    /* %s */\n", label))

		keys := sortedKeys(tokens)
		for _, key := range keys {
			val := fmt.Sprintf("%v", tokens[key])
			cssVar := fmt.Sprintf("--sigil-%s", key)
			buf.WriteString(fmt.Sprintf("    %s: %s;\n", cssVar, val))
		}
	}

	buf.WriteString("  }\n")
	buf.WriteString("}\n")

	return buf.Bytes(), nil
}

func generateTailwindConfig(theme *renderer.ThemeConfig) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("// tailwind.config.ts — generated by Sigil, do not edit\n")
	buf.WriteString("import type { Config } from \"tailwindcss\";\n\n")
	buf.WriteString("const config: Config = {\n")
	buf.WriteString("  content: [\n")
	buf.WriteString("    \"./pages/**/*.{ts,tsx}\",\n")
	buf.WriteString("    \"./components/**/*.{ts,tsx}\",\n")
	buf.WriteString("    \"./app/**/*.{ts,tsx}\",\n")
	buf.WriteString("  ],\n")
	buf.WriteString("  theme: {\n")
	buf.WriteString("    extend: {\n")

	// Colors
	if colors, ok := theme.Tokens["colors"]; ok && len(colors) > 0 {
		buf.WriteString("      colors: {\n")
		buf.WriteString("        sigil: {\n")
		keys := sortedKeys(colors)
		for _, key := range keys {
			jsKey := key
			if strings.Contains(key, "-") {
				jsKey = fmt.Sprintf("\"%s\"", key)
			}
			buf.WriteString(fmt.Sprintf("          %s: \"rgb(var(--sigil-%s) / <alpha-value>)\",\n", jsKey, key))
		}
		buf.WriteString("        },\n")
		buf.WriteString("      },\n")
	}

	// Fonts
	if typo, ok := theme.Tokens["typography"]; ok {
		if _, ok := typo["font-sans"]; ok {
			buf.WriteString("      fontFamily: {\n")
			buf.WriteString("        sans: [\"var(--sigil-font-sans)\"],\n")
			if _, ok := typo["font-mono"]; ok {
				buf.WriteString("        mono: [\"var(--sigil-font-mono)\"],\n")
			}
			buf.WriteString("      },\n")
		}
	}

	// Border radius
	if radius, ok := theme.Tokens["radius"]; ok && len(radius) > 0 {
		buf.WriteString("      borderRadius: {\n")
		keys := sortedKeys(radius)
		for _, key := range keys {
			if key == "none" || key == "full" {
				continue
			}
			buf.WriteString(fmt.Sprintf("        \"sigil-%s\": \"var(--sigil-%s)\",\n", key, key))
		}
		buf.WriteString("      },\n")
	}

	buf.WriteString("    },\n")
	buf.WriteString("  },\n")
	buf.WriteString("  plugins: [],\n")
	buf.WriteString("};\n\n")
	buf.WriteString("export default config;\n")

	return buf.Bytes(), nil
}

func sortedKeys(m map[string]interface{}) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
