// se-settings.tsx
// Generated by Sigil — do not edit manually

"use client";

import { toast } from "sonner";
import { AlertTriangle, Camera, Eye, GitFork, Layers, Shapes, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Toaster } from "@/components/ui/sonner";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { FileDownloadButton } from "@/components/file-download-button";
import { YamlImportButton } from "@/components/yaml-import-button";

export default function SeSettings() {
  return (
    <>
    <div className="flex flex-col gap-5 p-6">
      <h1 className="text-2xl font-semibold tracking-tight text-foreground">Settings</h1>
      <Tabs defaultValue="general">
        <TabsList>
          <TabsTrigger value="general">General</TabsTrigger>
          <TabsTrigger value="import-export">Import / Export</TabsTrigger>
          <TabsTrigger value="about">About</TabsTrigger>
        </TabsList>
        <TabsContent value="general">
          <div className="flex flex-col gap-4">
            <Card>
              <CardHeader>
                <CardTitle>Database Statistics</CardTitle>
                <CardDescription>Current database contents</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                  <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                      <CardTitle className="text-sm font-medium">Repos</CardTitle>
                      <GitFork className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                      <div className="text-2xl font-bold">112</div>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                      <CardTitle className="text-sm font-medium">Dimensions</CardTitle>
                      <Layers className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                      <div className="text-2xl font-bold">18</div>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                      <CardTitle className="text-sm font-medium">Lenses</CardTitle>
                      <Eye className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                      <div className="text-2xl font-bold">9</div>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                      <CardTitle className="text-sm font-medium">Patterns</CardTitle>
                      <Shapes className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                      <div className="text-2xl font-bold">26</div>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                      <CardTitle className="text-sm font-medium">Findings</CardTitle>
                      <AlertTriangle className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                      <div className="text-2xl font-bold">43</div>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                      <CardTitle className="text-sm font-medium">Snapshots</CardTitle>
                      <Camera className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                      <div className="text-2xl font-bold">340</div>
                    </CardContent>
                  </Card>
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>
        <TabsContent value="import-export">
          <div className="flex flex-col gap-4">
            <Card>
              <CardHeader>
                <CardTitle>Import Data</CardTitle>
                <CardDescription>Import repos from YAML files</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex flex-row gap-3">
                  <YamlImportButton
                    endpoint="/api/repos/import"
                    label="Import Repos YAML"
                  />
                  <Button variant="outline" onClick={() => toast("CSV import coming soon")}>
                    <Upload className="mr-2 h-4 w-4" />
                    Import Scores CSV
                  </Button>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Export Data</CardTitle>
                <CardDescription>Export data for backup or sharing</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex flex-row gap-3">
                  <FileDownloadButton
                    label="Export Repos YAML"
                    icon="download"
                    url="/api/repos/export"
                    filename="repos-export.yaml"
                  />
                  <FileDownloadButton
                    label="Backup Database"
                    icon="database"
                    url="/api/db/backup"
                    filename="stack-explorer-backup.db"
                  />
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>
        <TabsContent value="about">
          <Card>
            <CardHeader>
              <CardTitle>Stack Explorer</CardTitle>
              <CardDescription>AI agent tooling research platform</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col gap-3">
                <p className="text-base">Version: 0.1.0</p>
                <p className="text-sm text-muted-foreground">Stack Explorer is a multi-audience analytics platform for understanding the AI agent and developer tooling landscape. It tracks, scores, compares, and surfaces insights across repos, frameworks, and ecosystems.</p>
                <Separator />
                <p className="text-sm text-muted-foreground">Built with Sigil — UI defined in YAML, generated as React/shadcn</p>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
    <Toaster />
    </>
  );
}
