// sigil-page-editor.tsx
// Generated by Sigil — do not edit manually

"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useSigilPage } from "@/hooks/use-sigilpage";

export default function SigilPageEditor() {
  const router = useRouter();
  const [yamlEditor, setYamlEditor] = useState("");

  const { data: sigilPage, isLoading: sigilPageLoading } = useSigilPage();

  if (sigilPageLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-row gap-0">
      <div className="flex flex-col gap-4 p-4">
        <h3 className="scroll-m-20 text-2xl font-semibold tracking-tight text-foreground">Page Config</h3>
        <form className="flex flex-col gap-4 max-w-lg">
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="id">Page ID</Label>
            <Input id="id" name="id" type="text" placeholder="my-page" required />
          </div>
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="title">Title</Label>
            <Input id="title" name="title" type="text" placeholder="Page Title" required />
          </div>
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="overlay">Overlay</Label>
            <Select name="overlay">
              <SelectTrigger>
                <SelectValue placeholder="Select..." />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="page">Page</SelectItem>
                <SelectItem value="modal">Modal</SelectItem>
                <SelectItem value="sheet">Sheet</SelectItem>
                <SelectItem value="drawer">Drawer</SelectItem>
                <SelectItem value="fullscreen">Fullscreen</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="module">Module</Label>
            <Input id="module" name="module" type="text" placeholder="module-name" />
          </div>
          <Button type="submit">Save</Button>
        </form>
      </div>
      <div className="flex flex-col gap-2 p-4">
        <div className="flex flex-row gap-4 justify-between items-center">
          <h3 className="scroll-m-20 text-2xl font-semibold tracking-tight text-foreground">YAML Editor</h3>
          <div className="flex flex-row gap-2">
            <Button variant="secondary" onClick={() => fetch("/api/sigil/validate", { method: "POST" })}>Validate</Button>
            <Button variant="secondary" onClick={() => router.push("/preview")}>Preview</Button>
          </div>
        </div>
        <div className="flex flex-col gap-1.5">
          <Input id="yaml-editor" type="text" placeholder="# Paste or edit YAML here" value={yamlEditor} onChange={(e) => setYamlEditor(e.target.value)} />
        </div>
      </div>
    </div>
    </>
  );
}
