// forge-users.tsx
// Generated by Sigil — do not edit manually

"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { Loader2, Search, UserPlus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Combobox } from "@/components/combobox";
import { DataTable } from "@/components/data-table";
import { useUser } from "@/hooks/use-user";

export default function ForgeUsers() {
  const router = useRouter();
  const [searchUser, setSearchUser] = useState("");

  const { data: user, isLoading: userLoading } = useUser();

  if (userLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-6 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <h1 className="text-2xl font-semibold tracking-tight text-foreground">Users</h1>
        <div className="flex flex-row gap-2 items-center">
          <Combobox
            placeholder="Filter by role..."
            searchPlaceholder="Search roles..."
            emptyMessage="No matching roles."
            options={[
              { value: "all", label: "All Roles" },
              { value: "owner", label: "Owner" },
              { value: "admin", label: "Admin" },
              { value: "member", label: "Member" },
              { value: "viewer", label: "Viewer" },
            ]}
          />
          <Button variant="default" onClick={() => router.push("/users")}>
            <UserPlus className="mr-2 h-4 w-4" />
            Invite User
          </Button>
        </div>
      </div>
      <div className="relative">
        <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
        <Input type="search" placeholder="Search users..." className="w-full pl-9 [&::-webkit-search-cancel-button]:hidden [&::-webkit-search-decoration]:hidden" value={searchUser} onChange={(e) => setSearchUser(e.target.value)} />
      </div>
      <Card className="border-0 shadow-none ring-0">
        <CardContent>
          <DataTable
            data={(user ?? [])
              .filter((item) => {
                if (!searchUser) return true;
                const q = searchUser.toLowerCase();
                return Object.values(item).some((v) => String(v).toLowerCase().includes(q));
              })}
            columns={[
              { accessorKey: "status", header: "Status" },
              { accessorKey: "name", header: "Name" },
              { accessorKey: "email", header: "Email" },
              { accessorKey: "role", header: "Role" },
              { accessorKey: "teams", header: "Teams" },
              { accessorKey: "lastActive", header: "Last Active" },
            ]}
            emptyMessage="No matching results found."
          />
        </CardContent>
      </Card>
    </div>
    </>
  );
}
