// forge-monitoring-detail.tsx
// Generated by Sigil — do not edit manually

"use client";

import { ChevronsUpDown } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from "@/components/ui/breadcrumb";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Separator } from "@/components/ui/separator";
import { Slider } from "@/components/ui/slider";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import { SigilChart } from "@/components/sigil-chart";

export default function ForgeMonitoringDetail() {
  return (
    <>
    <div className="flex flex-col gap-6 p-6">
      <Breadcrumb>
        <BreadcrumbList>
          <BreadcrumbItem>
            <BreadcrumbLink href="/monitoring">Monitoring</BreadcrumbLink>
          </BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>
            <BreadcrumbPage>API Latency</BreadcrumbPage>
          </BreadcrumbItem>
        </BreadcrumbList>
      </Breadcrumb>
      <div className="flex flex-row gap-4 justify-between items-center">
        <h2 className="scroll-m-20 text-3xl font-semibold tracking-tight text-foreground">API Latency</h2>
        <ToggleGroup variant="outline">
          <ToggleGroupItem value="1h">1H</ToggleGroupItem>
          <ToggleGroupItem value="6h">6H</ToggleGroupItem>
          <ToggleGroupItem value="24h">24H</ToggleGroupItem>
          <ToggleGroupItem value="7d">7D</ToggleGroupItem>
          <ToggleGroupItem value="30d">30D</ToggleGroupItem>
        </ToggleGroup>
      </div>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Card>
          <CardHeader>
            <CardTitle>P50</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-base">45ms</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>P95</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-base">120ms</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>P99</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-base">340ms</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Error Rate</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-base">0.12%</p>
          </CardContent>
        </Card>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <Card>
          <CardHeader>
            <CardTitle>Latency Over Time</CardTitle>
            <CardDescription>P50/P95/P99 — last 12 hours</CardDescription>
          </CardHeader>
          <CardContent>
            <SigilChart
              type="line"
              xKey="time"
              height={250}
              showGrid
              showLegend
              dataKeys={["p50", "p95", "p99"]}
              config={{
                p50: { label: "P50", color: "var(--chart-1)" },
                p95: { label: "P95", color: "var(--chart-2)" },
                p99: { label: "P99", color: "var(--chart-3)" },
              }}
              data={[
                {p50: 42, p95: 110, p99: 280, time: "00:00"},
                {p50: 38, p95: 105, p99: 260, time: "02:00"},
                {p50: 35, p95: 98, p99: 240, time: "04:00"},
                {p50: 40, p95: 115, p99: 290, time: "06:00"},
                {p50: 48, p95: 135, p99: 350, time: "08:00"},
                {p50: 55, p95: 160, p99: 420, time: "10:00"},
                {p50: 52, p95: 148, p99: 380, time: "12:00"},
                {p50: 58, p95: 170, p99: 450, time: "14:00"},
                {p50: 50, p95: 142, p99: 360, time: "16:00"},
                {p50: 46, p95: 128, p99: 320, time: "18:00"},
                {p50: 43, p95: 118, p99: 290, time: "20:00"},
                {p50: 40, p95: 108, p99: 270, time: "22:00"},
              ]}
            />
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Request Volume</CardTitle>
            <CardDescription>Requests per minute — last 12 hours</CardDescription>
          </CardHeader>
          <CardContent>
            <SigilChart
              type="bar"
              xKey="time"
              height={250}
              showGrid
              dataKeys={["requests"]}
              config={{
                requests: { label: "Requests/min", color: "var(--chart-1)" },
              }}
              data={[
                {requests: 120, time: "00:00"},
                {requests: 85, time: "02:00"},
                {requests: 60, time: "04:00"},
                {requests: 150, time: "06:00"},
                {requests: 420, time: "08:00"},
                {requests: 580, time: "10:00"},
                {requests: 510, time: "12:00"},
                {requests: 620, time: "14:00"},
                {requests: 480, time: "16:00"},
                {requests: 350, time: "18:00"},
                {requests: 220, time: "20:00"},
                {requests: 160, time: "22:00"},
              ]}
            />
          </CardContent>
        </Card>
      </div>
      <Collapsible>
        <div className="flex items-center justify-between">
          <h4 className="text-sm font-semibold">Alert Thresholds</h4>
          <CollapsibleTrigger>
            <ChevronsUpDown className="h-4 w-4" />
          </CollapsibleTrigger>
        </div>
        <CollapsibleContent>
          <div className="flex flex-col gap-4">
            <div className="flex flex-col gap-2">
              <Label htmlFor="p95-threshold">P95 Latency Threshold (ms)</Label>
              <Slider id="p95-threshold" defaultValue={[200]} min={50} max={500} step={10} />
            </div>
            <div className="flex flex-col gap-2">
              <Label htmlFor="p99-threshold">P99 Latency Threshold (ms)</Label>
              <Slider id="p99-threshold" defaultValue={[500]} min={100} max={1000} step={25} />
            </div>
            <div className="flex flex-col gap-2">
              <Label htmlFor="error-rate-threshold">Error Rate Threshold (%)</Label>
              <Slider id="error-rate-threshold" defaultValue={[1]} min={0} max={10} step={0.1} />
            </div>
          </div>
        </CollapsibleContent>
      </Collapsible>
      <Collapsible>
        <div className="flex items-center justify-between">
          <h4 className="text-sm font-semibold">Recent Alerts</h4>
          <CollapsibleTrigger>
            <ChevronsUpDown className="h-4 w-4" />
          </CollapsibleTrigger>
        </div>
        <CollapsibleContent>
          <div className="flex flex-col gap-2">
            <Alert variant="default">
              <AlertDescription>P95 latency exceeded 200ms threshold at 14:32 UTC</AlertDescription>
            </Alert>
            <Alert variant="default">
              <AlertDescription>P95 latency exceeded 200ms threshold at 09:15 UTC</AlertDescription>
            </Alert>
            <Alert variant="default">
              <AlertDescription>Error rate returned to normal at 08:45 UTC</AlertDescription>
            </Alert>
          </div>
        </CollapsibleContent>
      </Collapsible>
      <Collapsible>
        <div className="flex items-center justify-between">
          <h4 className="text-sm font-semibold">Endpoint Breakdown</h4>
          <CollapsibleTrigger>
            <ChevronsUpDown className="h-4 w-4" />
          </CollapsibleTrigger>
        </div>
        <CollapsibleContent>
          <div className="flex flex-col gap-3">
            <div className="flex flex-row gap-4 justify-between items-center">
              <p className="text-base">GET /api/deployments</p>
              <div className="flex flex-row gap-2 items-center">
                <Badge variant="outline" className="border-emerald-500/30 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">32ms</Badge>
                <Progress value={32} />
              </div>
            </div>
            <Separator />
            <div className="flex flex-row gap-4 justify-between items-center">
              <p className="text-base">POST /api/deployments</p>
              <div className="flex flex-row gap-2 items-center">
                <Badge variant="outline" className="border-amber-500/30 bg-amber-500/10 text-amber-600 dark:text-amber-400">156ms</Badge>
                <Progress value={65} />
              </div>
            </div>
            <Separator />
            <div className="flex flex-row gap-4 justify-between items-center">
              <p className="text-base">GET /api/assets</p>
              <div className="flex flex-row gap-2 items-center">
                <Badge variant="outline" className="border-emerald-500/30 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">45ms</Badge>
                <Progress value={38} />
              </div>
            </div>
          </div>
        </CollapsibleContent>
      </Collapsible>
    </div>
    </>
  );
}
