// se-gap-analysis.tsx
// Generated by Sigil — do not edit manually

"use client";

import { Suspense } from "react";

import { useSearchParams } from "next/navigation";
import { useState, useEffect } from "react";
import { toast } from "sonner";
import { postItem } from "@/lib/api";
import { Loader2, Plus } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Toaster } from "@/components/ui/sonner";
import { DataTable } from "@/components/data-table";
import { SigilChart } from "@/components/sigil-chart";
import { useComparisonSet } from "@/hooks/use-comparisonset";
import { useDimensionScore } from "@/hooks/use-dimensionscore";
import { useFinding } from "@/hooks/use-finding";
import { useRepo } from "@/hooks/use-repo";
import { useScorecard } from "@/hooks/use-scorecard";
import type { Finding } from "@/types/finding";

export default function SeGapAnalysisPage() {
  return (
    <Suspense>
      <SeGapAnalysis />
    </Suspense>
  );
}

function SeGapAnalysis() {
  const searchParams = useSearchParams();
  const [modalOpen, setModalOpen] = useState(false);
  const [sheetItem, setSheetItem] = useState<Finding | null>(null);
  const [formName, setFormName] = useState("");

  useEffect(() => {
    if (searchParams.get("action") === "create") setModalOpen(true);
  }, [searchParams]);

  const { data: comparisonSet, isLoading: comparisonSetLoading, refetch: refetchComparisons } = useComparisonSet();
  const { data: finding, isLoading: findingLoading } = useFinding();
  const { data: repo, isLoading: repoLoading } = useRepo();
  const { data: scorecard, isLoading: scorecardLoading } = useScorecard();
  const { data: dimensionScore, isLoading: dimensionScoreLoading } = useDimensionScore();

  const handleSave = async () => {
    try {
      await postItem("comparison-sets", { name: formName });
      toast.success("Comparison set created");
      setModalOpen(false);
      setFormName("");
      refetchComparisons();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to create comparison set");
    }
  };

  // Compute advantages and gaps from dimension scores (own vs reference)
  const { advantages, gaps } = (() => {
    const ownRepoIds = new Set((repo ?? []).filter((r) => r.is_own).map((r) => r.id));
    const scorecardRepoMap = new Map((scorecard ?? []).map((sc) => [sc.id, sc.repo_id]));
    const dimAccum: Record<string, { ownSum: number; ownCount: number; refSum: number; refCount: number }> = {};
    for (const ds of dimensionScore ?? []) {
      const dimName = ds.dimension_name ?? "Unknown";
      const repoId = scorecardRepoMap.get(ds.scorecard_id ?? "");
      const score = Number(ds.score ?? 0);
      if (!dimAccum[dimName]) dimAccum[dimName] = { ownSum: 0, ownCount: 0, refSum: 0, refCount: 0 };
      if (repoId && ownRepoIds.has(repoId)) {
        dimAccum[dimName].ownSum += score;
        dimAccum[dimName].ownCount++;
      } else {
        dimAccum[dimName].refSum += score;
        dimAccum[dimName].refCount++;
      }
    }
    const deltas = Object.entries(dimAccum).map(([dimension, v]) => {
      const ownAvg = v.ownCount ? v.ownSum / v.ownCount : 0;
      const refAvg = v.refCount ? v.refSum / v.refCount : 0;
      return { dimension, delta: Math.round((ownAvg - refAvg) * 10) / 10 };
    });
    return {
      advantages: deltas.filter((d) => d.delta > 0).sort((a, b) => b.delta - a.delta).map((d) => ({ dimension: d.dimension, delta: d.delta })),
      gaps: deltas.filter((d) => d.delta < 0).sort((a, b) => a.delta - b.delta).map((d) => ({ dimension: d.dimension, gap: Math.abs(d.delta) })),
    };
  })();

  if (comparisonSetLoading || findingLoading || repoLoading || scorecardLoading || dimensionScoreLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-5 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <div className="flex flex-col gap-1">
          <h1 className="text-2xl font-semibold tracking-tight text-foreground">Gap Analysis</h1>
          <p className="text-sm text-muted-foreground">Compare your projects against reference implementations</p>
        </div>
        <div className="flex flex-row gap-2">
          <Select>
            <SelectTrigger>
              <SelectValue placeholder="Select comparison set" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="own-vs-top">Own Projects vs Top Frameworks</SelectItem>
              <SelectItem value="go-vs-ts">Go Agents vs TypeScript Agents</SelectItem>
              <SelectItem value="oss-vs-commercial">Open Source vs Commercial</SelectItem>
            </SelectContent>
          </Select>
          <Dialog open={modalOpen} onOpenChange={setModalOpen}>
            <DialogTrigger render={<Button variant="default" />}>
              <Plus className="mr-2 h-4 w-4" />
              New Comparison
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Create Comparison Set</DialogTitle>
              </DialogHeader>
              <div className="flex flex-col gap-4 py-4">
                <div className="flex flex-col gap-1.5">
                  <Label htmlFor="name">Name</Label>
                  <Input id="name" name="name" type="text" placeholder="e.g., Own vs Top 10" required value={formName} onChange={(e) => setFormName(e.target.value)} />
                </div>
              </div>
              <DialogFooter>
                <Button variant="outline" onClick={() => setModalOpen(false)}>Cancel</Button>
                <Button onClick={handleSave}>Save</Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <Card>
          <CardHeader>
            <CardTitle>Advantages</CardTitle>
            <CardDescription>Dimensions where own projects outperform references</CardDescription>
          </CardHeader>
          <CardContent>
            <SigilChart
              type="bar"
              xKey="dimension"
              height={250}
              showGrid
              dataKeys={["delta"]}
              config={{
                delta: { label: "Advantage", color: "oklch(0.75 0.18 155)" },
              }}
              data={advantages.length > 0 ? advantages : [{ dimension: "No data", delta: 0 }]}
            />
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Gaps</CardTitle>
            <CardDescription>Dimensions where own projects trail references</CardDescription>
          </CardHeader>
          <CardContent>
            <SigilChart
              type="bar"
              xKey="dimension"
              height={250}
              showGrid
              dataKeys={["gap"]}
              config={{
                gap: { label: "Gap", color: "oklch(0.65 0.2 25)" },
              }}
              data={gaps.length > 0 ? gaps : [{ dimension: "No data", gap: 0 }]}
            />
          </CardContent>
        </Card>
      </div>
      <Card>
        <CardHeader>
          <CardTitle>Dimension Breakdown</CardTitle>
          <CardDescription>Side-by-side comparison — own projects vs reference average</CardDescription>
        </CardHeader>
        <CardContent>
          <DataTable
            data={comparisonSet ?? []}
            columns={[
              { accessorKey: "name", header: "Comparison Set" },
              { accessorKey: "subject_count", header: "Subjects" },
              { accessorKey: "reference_count", header: "References" },
            ]}
          />
        </CardContent>
      </Card>
      <Card>
        <CardHeader>
          <CardTitle>Gap Findings</CardTitle>
          <CardDescription>Findings generated from gap analysis</CardDescription>
        </CardHeader>
        <CardContent>
          <DataTable
            data={finding ?? []}
            columns={[
              { accessorKey: "title", header: "Title" },
              {
                accessorKey: "category",
                header: "Category",
                cell: ({ row }: { row: { getValue: (k: string) => unknown } }) => {
                  const v = String(row.getValue("category") ?? "");
                  const variants: Record<string, string> = { "gap": "danger", "strength": "success", "opportunity": "info" };
                  const variant = variants[v] ?? variants[v.toLowerCase()] ?? "default";
                  return <Badge variant={variant === "danger" ? "destructive" : variant === "success" || variant === "warning" || variant === "info" ? "outline" : "secondary"} className={
                    variant === "success" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-400" :
                    variant === "warning" ? "border-amber-500/30 bg-amber-500/10 text-amber-400" :
                    variant === "info" ? "border-blue-500/30 bg-blue-500/10 text-blue-400" :
                    variant === "danger" ? "" : ""
                  }>{v}</Badge>;
                },
              },
              {
                accessorKey: "severity",
                header: "Severity",
                cell: ({ row }: { row: { getValue: (k: string) => unknown } }) => {
                  const v = String(row.getValue("severity") ?? "");
                  const variants: Record<string, string> = { "high": "warning", "medium": "default", "low": "info", "critical": "danger" };
                  const variant = variants[v] ?? variants[v.toLowerCase()] ?? "default";
                  return <Badge variant={variant === "danger" ? "destructive" : variant === "success" || variant === "warning" || variant === "info" ? "outline" : "secondary"} className={
                    variant === "success" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-400" :
                    variant === "warning" ? "border-amber-500/30 bg-amber-500/10 text-amber-400" :
                    variant === "info" ? "border-blue-500/30 bg-blue-500/10 text-blue-400" :
                    variant === "danger" ? "" : ""
                  }>{v}</Badge>;
                },
              },
              { accessorKey: "repo_name", header: "Repo" },
            ]}
            onRowClick={(row) => setSheetItem(row as Finding)}
          />
        </CardContent>
      </Card>
    </div>
    <Sheet open={!!sheetItem} onOpenChange={(open) => !open && setSheetItem(null)}>
      <SheetContent side="right">
        <SheetHeader>
          <SheetTitle>{sheetItem?.title}</SheetTitle>
        </SheetHeader>
        {sheetItem && (
          <div className="flex flex-col gap-4 px-4 pt-4">
            <div className="flex flex-row gap-2">
              <Badge variant="outline">{sheetItem.category}</Badge>
              <Badge variant="outline">{sheetItem.severity}</Badge>
              <Badge variant="secondary">{sheetItem.status}</Badge>
            </div>
            <Separator />
            <div className="flex flex-col gap-1">
              <span className="text-xs text-muted-foreground uppercase tracking-wider">Repo</span>
              <span className="text-sm">{sheetItem.repo_name}</span>
            </div>
            <div className="flex flex-col gap-1">
              <span className="text-xs text-muted-foreground uppercase tracking-wider">Description</span>
              <p className="text-sm text-muted-foreground leading-relaxed">{sheetItem.description}</p>
            </div>
          </div>
        )}
      </SheetContent>
    </Sheet>
    <Toaster />
    </>
  );
}
