// se-gap-analysis.tsx
// Generated by Sigil — do not edit manually

"use client";

import { useState } from "react";
import { toast } from "sonner";
import { Loader2, Plus } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Toaster } from "@/components/ui/sonner";
import { DataTable } from "@/components/data-table";
import { GapAdvantageCharts } from "@/components/gap-advantage-charts";
import { useComparisonSet } from "@/hooks/use-comparisonset";
import { useDimensionScore } from "@/hooks/use-dimensionscore";
import { useFinding } from "@/hooks/use-finding";
import { useRepo } from "@/hooks/use-repo";
import { useScorecard } from "@/hooks/use-scorecard";
import { postItem, updateItem } from "@/lib/api";
import { Finding } from "@/types/finding";

export default function SeGapAnalysis() {
  const [modalOpen, setModalOpen] = useState(false);
  const [formName, setFormName] = useState("");
    const handleCreateComparisonSet = async () => {
    try {
      await postItem("comparisonsets", {
        name: formName,
      });
      toast.success("ComparisonSet created");
      setModalOpen(false);
      setFormName("");
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to create comparisonset");
    }
  };


  const [sheetItem, setSheetItem] = useState<Finding | null>(null);
  const [editing, setEditing] = useState(false);
  const [editCategory, setEditCategory] = useState("");
  const [editSeverity, setEditSeverity] = useState("");
  const [editStatus, setEditStatus] = useState("");
  const [editRepoName, setEditRepoName] = useState("");
  const [editDescription, setEditDescription] = useState("");
    const startEditing = () => {
    if (!sheetItem) return;
    setEditCategory(String((sheetItem as unknown as Record<string, unknown>).category ?? ""));
    setEditSeverity(String((sheetItem as unknown as Record<string, unknown>).severity ?? ""));
    setEditStatus(String((sheetItem as unknown as Record<string, unknown>).status ?? ""));
    setEditRepoName(String((sheetItem as unknown as Record<string, unknown>).repo_name ?? ""));
    setEditDescription(String((sheetItem as unknown as Record<string, unknown>).description ?? ""));
    setEditing(true);
  };


    const handleUpdate = async () => {
    if (!sheetItem) return;
    try {
      await updateItem("findings", (sheetItem as { id: string }).id, {
        category: editCategory,
        severity: editSeverity,
        status: editStatus,
        repo_name: editRepoName,
        description: editDescription,
      });
      toast.success("Finding updated");
      setEditing(false);
      setSheetItem(null);
      refetchFinding();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to update finding");
    }
  };



  const { data: comparisonSet, isLoading: comparisonSetLoading, refetch: refetchComparisonSet } = useComparisonSet();
  const { data: finding, isLoading: findingLoading, refetch: refetchFinding } = useFinding();
  const { data: repo, isLoading: repoLoading } = useRepo();
  const { data: scorecard, isLoading: scorecardLoading } = useScorecard();
  const { data: dimensionScore, isLoading: dimensionScoreLoading } = useDimensionScore();

  if (comparisonSetLoading || findingLoading || repoLoading || scorecardLoading || dimensionScoreLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-5 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <div className="flex flex-col gap-1">
          <h1 className="text-2xl font-semibold tracking-tight text-foreground">Gap Analysis</h1>
          <p className="text-sm text-muted-foreground">Compare your projects against reference implementations</p>
        </div>
        <div className="flex flex-row gap-2">
          <Select>
            <SelectTrigger>
              <SelectValue placeholder="Select comparison set" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="own-vs-top">Own Projects vs Top Frameworks</SelectItem>
              <SelectItem value="go-vs-ts">Go Agents vs TypeScript Agents</SelectItem>
              <SelectItem value="oss-vs-commercial">Open Source vs Commercial</SelectItem>
            </SelectContent>
          </Select>
          <Dialog open={modalOpen} onOpenChange={setModalOpen}>
            <DialogTrigger render={<Button variant="default" />}>
              <Plus className="mr-2 h-4 w-4" />
              New Comparison
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Create Comparison Set</DialogTitle>
              </DialogHeader>
              <div className="flex flex-col gap-4 py-4">
                <div className="flex flex-col gap-1.5">
                  <Label htmlFor="name">Name</Label>
                  <Input id="name" type="text" placeholder="e.g., Own vs Top 10" value={formName} onChange={(e) => setFormName(e.target.value)} />
                </div>
              </div>
              <DialogFooter>
                <Button variant="outline" onClick={() => setModalOpen(false)}>Cancel</Button>
                <Button onClick={handleCreateComparisonSet}>Save</Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>
      </div>
      <GapAdvantageCharts
        dimensionScores={dimensionScore}
        repos={repo}
        scorecards={scorecard}
      />
      <Card>
        <CardHeader>
          <CardTitle>Dimension Breakdown</CardTitle>
          <CardDescription>Side-by-side comparison — own projects vs reference average</CardDescription>
        </CardHeader>
        <CardContent>
          <DataTable
            data={comparisonSet ?? []}
            columns={[
              { accessorKey: "name", header: "Comparison Set" },
              { accessorKey: "subject_count", header: "Subjects" },
              { accessorKey: "reference_count", header: "References" },
            ]}
          />
        </CardContent>
      </Card>
      <Card>
        <CardHeader>
          <CardTitle>Gap Findings</CardTitle>
          <CardDescription>Findings generated from gap analysis</CardDescription>
        </CardHeader>
        <CardContent>
          <DataTable
            data={finding ?? []}
            columns={[
              { accessorKey: "title", header: "Title" },
              {
                accessorKey: "category",
                header: "Category",
                cell: ({ row }: { row: { getValue: (k: string) => unknown } }) => {
                  const v = String(row.getValue("category") ?? "");
                  const variants: Record<string, string> = { "strength": "success", "opportunity": "info", "gap": "danger" };
                  const variant = variants[v] ?? variants[v.toLowerCase()] ?? "default";
                  return <Badge variant={variant === "danger" ? "destructive" : variant === "success" || variant === "warning" || variant === "info" ? "outline" : "secondary"} className={
                    variant === "success" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-400" :
                    variant === "warning" ? "border-amber-500/30 bg-amber-500/10 text-amber-400" :
                    variant === "info" ? "border-blue-500/30 bg-blue-500/10 text-blue-400" :
                    variant === "danger" ? "" : ""
                  }>{v}</Badge>;
                },
              },
              {
                accessorKey: "severity",
                header: "Severity",
                cell: ({ row }: { row: { getValue: (k: string) => unknown } }) => {
                  const v = String(row.getValue("severity") ?? "");
                  const variants: Record<string, string> = { "low": "info", "critical": "danger", "high": "warning", "medium": "default" };
                  const variant = variants[v] ?? variants[v.toLowerCase()] ?? "default";
                  return <Badge variant={variant === "danger" ? "destructive" : variant === "success" || variant === "warning" || variant === "info" ? "outline" : "secondary"} className={
                    variant === "success" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-400" :
                    variant === "warning" ? "border-amber-500/30 bg-amber-500/10 text-amber-400" :
                    variant === "info" ? "border-blue-500/30 bg-blue-500/10 text-blue-400" :
                    variant === "danger" ? "" : ""
                  }>{v}</Badge>;
                },
              },
              { accessorKey: "repo_name", header: "Repo" },
            ]}
            onRowClick={(row) => setSheetItem(row as Finding)}
          />
        </CardContent>
      </Card>
    </div>
    <Sheet open={!!sheetItem} onOpenChange={(open) => { if (!open) { setSheetItem(null); setEditing(false); } }}>
      <SheetContent side="right">
        <SheetHeader>
          <SheetTitle>{(sheetItem as unknown as Record<string, unknown>)?.category as string}</SheetTitle>
        </SheetHeader>
        {sheetItem && !editing && (
          <div className="flex flex-col gap-4 px-4 pt-4">
            <div className="flex flex-row gap-2">
              <Button variant="outline" size="sm" onClick={startEditing}>Edit</Button>
            </div>
            <div>
              <div className="text-xs text-muted-foreground">Category</div>
              <div className="text-sm">{String((sheetItem as unknown as Record<string, unknown>)?.category ?? "")}</div>
            </div>
            <div>
              <div className="text-xs text-muted-foreground">Severity</div>
              <div className="text-sm">{String((sheetItem as unknown as Record<string, unknown>)?.severity ?? "")}</div>
            </div>
            <div>
              <div className="text-xs text-muted-foreground">Status</div>
              <div className="text-sm">{String((sheetItem as unknown as Record<string, unknown>)?.status ?? "")}</div>
            </div>
            <div>
              <div className="text-xs text-muted-foreground">Repo</div>
              <div className="text-sm">{String((sheetItem as unknown as Record<string, unknown>)?.repo_name ?? "")}</div>
            </div>
            <div>
              <div className="text-xs text-muted-foreground">Description</div>
              <div className="text-sm">{String((sheetItem as unknown as Record<string, unknown>)?.description ?? "")}</div>
            </div>
          </div>
        )}
        {sheetItem && editing && (
          <div className="flex flex-col gap-4 px-4 pt-4">
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="edit-category">Category</Label>
              <Input id="edit-category" type="text" value={editCategory} onChange={(e) => setEditCategory(e.target.value)} />
            </div>
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="edit-severity">Severity</Label>
              <Input id="edit-severity" type="text" value={editSeverity} onChange={(e) => setEditSeverity(e.target.value)} />
            </div>
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="edit-status">Status</Label>
              <Input id="edit-status" type="text" value={editStatus} onChange={(e) => setEditStatus(e.target.value)} />
            </div>
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="edit-repo_name">Repo</Label>
              <Input id="edit-repo_name" type="text" value={editRepoName} onChange={(e) => setEditRepoName(e.target.value)} />
            </div>
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="edit-description">Description</Label>
              <Input id="edit-description" type="text" value={editDescription} onChange={(e) => setEditDescription(e.target.value)} />
            </div>
            <div className="flex flex-row gap-2">
              <Button variant="outline" size="sm" onClick={() => setEditing(false)}>Cancel</Button>
              <Button size="sm" onClick={handleUpdate}>Save</Button>
            </div>
          </div>
        )}
      </SheetContent>
    </Sheet>
    <Toaster />
    </>
  );
}
