// forge-monitoring.tsx
// Generated by Sigil — do not edit manually

"use client";

import { useRouter } from "next/navigation";
import { AlertTriangle, Bell, XCircle } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";

export default function ForgeMonitoring() {
  const router = useRouter();

  return (
    <>
    <div className="flex flex-col gap-6 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight text-foreground">Monitoring</h1>
        <div className="flex flex-row gap-2">
          <Select>
            <SelectTrigger>
              <SelectValue placeholder="Last hour" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="1h">Last hour</SelectItem>
              <SelectItem value="6h">Last 6 hours</SelectItem>
              <SelectItem value="24h">Last 24 hours</SelectItem>
              <SelectItem value="7d">Last 7 days</SelectItem>
              <SelectItem value="30d">Last 30 days</SelectItem>
            </SelectContent>
          </Select>
          <Button variant="ghost" onClick={() => router.push("/alerts")}>
            <Bell className="mr-2 h-4 w-4" />
            Configure Alerts
          </Button>
        </div>
      </div>
      <div className="grid grid-cols-4 gap-4">
        <Card>
          <CardHeader>
            <CardTitle>CPU Usage</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-row gap-4 justify-between items-center">
              <div className="flex flex-col gap-1">
                <h2 className="scroll-m-20 text-3xl font-semibold tracking-tight text-foreground">73%</h2>
                <p className="text-base text-muted-foreground">avg across 12 servers</p>
              </div>
            </div>
            <Progress value={73} />
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Memory</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-row gap-4 justify-between items-center">
              <div className="flex flex-col gap-1">
                <h2 className="scroll-m-20 text-3xl font-semibold tracking-tight text-foreground">61%</h2>
                <p className="text-base text-muted-foreground">18.3 GB / 30 GB</p>
              </div>
            </div>
            <Progress value={61} />
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Disk I/O</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-row gap-4 justify-between items-center">
              <div className="flex flex-col gap-1">
                <h2 className="scroll-m-20 text-3xl font-semibold tracking-tight text-foreground">24%</h2>
                <p className="text-base text-muted-foreground">Read: 1.2 GB/s Write: 340 MB/s</p>
              </div>
            </div>
            <Progress value={24} />
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Network</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-row gap-4 justify-between items-center">
              <div className="flex flex-col gap-1">
                <h2 className="scroll-m-20 text-3xl font-semibold tracking-tight text-foreground">892 Mbps</h2>
                <p className="text-base text-muted-foreground">In: 540 Mbps Out: 352 Mbps</p>
              </div>
              <Badge variant="outline" className="border-blue-500/30 bg-blue-500/10 text-blue-600 dark:text-blue-400">Normal</Badge>
            </div>
          </CardContent>
        </Card>
      </div>
      <Card>
        <CardHeader>
          <CardTitle>Service Health</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex flex-col gap-3">
            <div className="flex flex-row gap-4 justify-between items-center">
              <div className="flex flex-col gap-0">
                <p className="text-base">api-gateway</p>
                <p className="text-base text-muted-foreground">api.forge.dev</p>
              </div>
              <div className="flex flex-row gap-2 items-center">
                <Badge variant="outline" className="border-emerald-500/30 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">Healthy</Badge>
                <p className="text-base text-muted-foreground">12ms</p>
              </div>
            </div>
            <Separator />
            <div className="flex flex-row gap-4 justify-between items-center">
              <div className="flex flex-col gap-0">
                <p className="text-base">auth-service</p>
                <p className="text-base text-muted-foreground">auth.forge.dev</p>
              </div>
              <div className="flex flex-row gap-2 items-center">
                <Badge variant="outline" className="border-emerald-500/30 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">Healthy</Badge>
                <p className="text-base text-muted-foreground">8ms</p>
              </div>
            </div>
            <Separator />
            <div className="flex flex-row gap-4 justify-between items-center">
              <div className="flex flex-col gap-0">
                <p className="text-base">worker-pool</p>
                <p className="text-base text-muted-foreground">workers.forge.dev</p>
              </div>
              <div className="flex flex-row gap-2 items-center">
                <Badge variant="outline" className="border-amber-500/30 bg-amber-500/10 text-amber-600 dark:text-amber-400">Degraded</Badge>
                <p className="text-base text-muted-foreground">340ms</p>
              </div>
            </div>
            <Separator />
            <div className="flex flex-row gap-4 justify-between items-center">
              <div className="flex flex-col gap-0">
                <p className="text-base">cdn-edge</p>
                <p className="text-base text-muted-foreground">cdn.forge.dev</p>
              </div>
              <div className="flex flex-row gap-2 items-center">
                <Badge variant="outline" className="border-emerald-500/30 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">Healthy</Badge>
                <p className="text-base text-muted-foreground">3ms</p>
              </div>
            </div>
            <Separator />
            <div className="flex flex-row gap-4 justify-between items-center">
              <div className="flex flex-col gap-0">
                <p className="text-base">database-primary</p>
                <p className="text-base text-muted-foreground">db.forge.dev:5432</p>
              </div>
              <div className="flex flex-row gap-2 items-center">
                <Badge variant="outline" className="border-emerald-500/30 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">Healthy</Badge>
                <p className="text-base text-muted-foreground">2ms</p>
              </div>
            </div>
            <Separator />
            <div className="flex flex-row gap-4 justify-between items-center">
              <div className="flex flex-col gap-0">
                <p className="text-base">database-replica</p>
                <p className="text-base text-muted-foreground">db-ro.forge.dev:5432</p>
              </div>
              <div className="flex flex-row gap-2 items-center">
                <Badge variant="destructive">Down</Badge>
                <p className="text-base text-muted-foreground">timeout</p>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
      <div className="flex flex-row gap-4">
        <Card>
          <CardHeader>
            <CardTitle>Recent Alerts</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-col gap-3">
              <div className="flex flex-row gap-3 items-center">
                <XCircle className="h-4 w-4" />
                <div className="flex flex-col gap-0">
                  <p className="text-base">Database replica connection timeout</p>
                  <p className="text-base text-muted-foreground">2 minutes ago</p>
                </div>
                <Badge variant="destructive">Critical</Badge>
              </div>
              <Separator />
              <div className="flex flex-row gap-3 items-center">
                <AlertTriangle className="h-4 w-4" />
                <div className="flex flex-col gap-0">
                  <p className="text-base">Worker pool response time exceeded 300ms</p>
                  <p className="text-base text-muted-foreground">15 minutes ago</p>
                </div>
                <Badge variant="outline" className="border-amber-500/30 bg-amber-500/10 text-amber-600 dark:text-amber-400">Warning</Badge>
              </div>
              <Separator />
              <div className="flex flex-row gap-3 items-center">
                <AlertTriangle className="h-4 w-4" />
                <div className="flex flex-col gap-0">
                  <p className="text-base">Disk usage above 80% on srv-03</p>
                  <p className="text-base text-muted-foreground">1 hour ago</p>
                </div>
                <Badge variant="outline" className="border-amber-500/30 bg-amber-500/10 text-amber-600 dark:text-amber-400">Warning</Badge>
              </div>
              <Separator />
              <div className="flex flex-row gap-3 items-center">
                <AlertTriangle className="h-4 w-4" />
                <div className="flex flex-col gap-0">
                  <p className="text-base">SSL certificate expires in 7 days</p>
                  <p className="text-base text-muted-foreground">3 hours ago</p>
                </div>
                <Badge variant="outline" className="border-blue-500/30 bg-blue-500/10 text-blue-600 dark:text-blue-400">Info</Badge>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Uptime (30 days)</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-col gap-3">
              <div className="flex flex-row gap-4 justify-between">
                <p className="text-base">api-gateway</p>
                <p className="text-base">99.99%</p>
              </div>
              <Progress value={99} />
              <div className="flex flex-row gap-4 justify-between">
                <p className="text-base">auth-service</p>
                <p className="text-base">99.97%</p>
              </div>
              <Progress value={99} />
              <div className="flex flex-row gap-4 justify-between">
                <p className="text-base">worker-pool</p>
                <p className="text-base">98.50%</p>
              </div>
              <Progress value={98} />
              <div className="flex flex-row gap-4 justify-between">
                <p className="text-base">cdn-edge</p>
                <p className="text-base">100%</p>
              </div>
              <Progress value={100} />
              <div className="flex flex-row gap-4 justify-between">
                <p className="text-base">database-primary</p>
                <p className="text-base">99.95%</p>
              </div>
              <Progress value={99} />
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
    </>
  );
}
