// forge-assets.tsx
// Generated by Sigil — do not edit manually

"use client";

import { useRouter } from "next/navigation";
import { Plus, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { DataTable } from "@/components/data-table";
import { useAsset } from "@/hooks/use-asset";

export default function ForgeAssets() {
  const router = useRouter();
  const { data: asset, isLoading: assetLoading } = useAsset();

  return (
    <div className="min-h-screen bg-background text-foreground font-sans">
    <div className="flex flex-col gap-6 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight text-foreground">Assets</h1>
        <div className="flex flex-row gap-2">
          <Select>
            <SelectTrigger>
              <SelectValue placeholder="All Providers" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Providers</SelectItem>
              <SelectItem value="aws">AWS</SelectItem>
              <SelectItem value="azure">Azure</SelectItem>
              <SelectItem value="gcp">GCP</SelectItem>
              <SelectItem value="hetzner">Hetzner</SelectItem>
              <SelectItem value="digitalocean">DigitalOcean</SelectItem>
              <SelectItem value="cloudflare">Cloudflare</SelectItem>
              <SelectItem value="custom">Custom</SelectItem>
            </SelectContent>
          </Select>
          <Select>
            <SelectTrigger>
              <SelectValue placeholder="All Types" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Types</SelectItem>
              <SelectItem value="server">Server</SelectItem>
              <SelectItem value="database">Database</SelectItem>
              <SelectItem value="bucket">Bucket</SelectItem>
              <SelectItem value="cdn">CDN</SelectItem>
              <SelectItem value="dns">DNS</SelectItem>
              <SelectItem value="load-balancer">Load Balancer</SelectItem>
              <SelectItem value="queue">Queue</SelectItem>
            </SelectContent>
          </Select>
          <Button variant="default" onClick={() => router.push("/forge-assets")}>
            <Plus className="mr-2 h-4 w-4" />
            Add Asset
          </Button>
        </div>
      </div>
      <div className="relative">
        <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
        <Input type="search" placeholder="Search assets..." className="w-full pl-9 [&::-webkit-search-cancel-button]:hidden [&::-webkit-search-decoration]:hidden" />
      </div>
      <Card className="border-0 shadow-none ring-0">
        <CardContent>
          <DataTable
            data={asset ?? []}
            columns={[
              { accessorKey: "status", header: "Status" },
              { accessorKey: "name", header: "Name" },
              { accessorKey: "type", header: "Type" },
              { accessorKey: "provider", header: "Provider" },
              { accessorKey: "region", header: "Region" },
              { accessorKey: "cost", header: "Cost" },
              { accessorKey: "updatedAt", header: "Last Updated" },
            ]}
          />
        </CardContent>
      </Card>
    </div>
    </div>
  );
}
