// sigil-themes.tsx
// Generated by Sigil — do not edit manually

"use client";

import { useState } from "react";
import { Loader2, Plus } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { DataTable } from "@/components/data-table";
import { useSigilTheme } from "@/hooks/use-sigiltheme";

export default function SigilThemes() {
  const [previewSampleInput, setPreviewSampleInput] = useState("");

  const { data: sigilTheme, isLoading: sigilThemeLoading } = useSigilTheme();

  if (sigilThemeLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-6 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight text-foreground">Themes</h1>
        <Button variant="default">
          <Plus className="mr-2 h-4 w-4" />
          New Theme
        </Button>
      </div>
      <div className="flex flex-row gap-6">
        <DataTable
          data={sigilTheme ?? []}
          columns={[
            { accessorKey: "name", header: "Name" },
            { accessorKey: "description", header: "Description" },
            { accessorKey: "extends", header: "Extends" },
          ]}
        />
        <div className="flex flex-col gap-4">
          <h3 className="scroll-m-20 text-2xl font-semibold tracking-tight text-foreground">Token Editor</h3>
          <form className="flex flex-col gap-4 max-w-lg">
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="background">Background</Label>
              <Input id="background" name="background" type="text" placeholder="9 9 11" />
            </div>
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="surface">Surface</Label>
              <Input id="surface" name="surface" type="text" placeholder="24 24 27" />
            </div>
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="accent">Accent</Label>
              <Input id="accent" name="accent" type="text" placeholder="79 70 229" />
            </div>
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="text-color">Text</Label>
              <Input id="text-color" name="text-color" type="text" placeholder="244 244 245" />
            </div>
            <Button type="submit">Update Tokens</Button>
          </form>
          <div className="flex flex-col gap-2">
            <h4 className="scroll-m-20 text-xl font-semibold tracking-tight text-foreground">Live Preview</h4>
            <Button variant="default">Sample Button</Button>
            <Badge variant="default">sample</Badge>
            <div className="flex flex-col gap-1.5">
              <Input id="preview-sample-input" type="text" placeholder="Sample input" value={previewSampleInput} onChange={(e) => setPreviewSampleInput(e.target.value)} />
            </div>
          </div>
        </div>
      </div>
    </div>
    </>
  );
}
