// task_handler.go
// Generated by Sigil — fill in query logic, do not edit structure.
package handlers

import (
	"encoding/json"
	"net/http"
)

// TaskHandler handles Task CRUD operations.
type TaskHandler struct {
	// TODO: Add your data store dependency
}

// NewTaskHandler creates a new TaskHandler.
func NewTaskHandler() *TaskHandler {
	return &TaskHandler{}
}

// List handles GET /api/tasks
func (h *TaskHandler) List(w http.ResponseWriter, r *http.Request) {
	// Query params: search, filter[field], sort, direction, page, pageSize
	// TODO: Query your data store
	// results, total, err := h.store.ListTasks(r.Context(), params)

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]interface{}{
		"data": []interface{}{},
		"meta": map[string]interface{}{
			"total":    0,
			"page":     1,
			"per_page": 25,
		},
	})
}

// Create handles POST /api/tasks
func (h *TaskHandler) Create(w http.ResponseWriter, r *http.Request) {
	var input struct {
		Title string `json:"title"`
		Description string `json:"description"`
		Status string `json:"status"`
		Assignee string `json:"assignee"`
		Priority string `json:"priority"`
	}
	if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
		http.Error(w, "invalid request body", http.StatusBadRequest)
		return
	}

	// TODO: Validate and create
	// result, err := h.store.CreateTask(r.Context(), input)

	w.WriteHeader(http.StatusCreated)
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]interface{}{"data": nil})
}

// Read handles GET /api/tasks/{id}
func (h *TaskHandler) Read(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	_ = id

	// TODO: Fetch by ID
	// result, err := h.store.GetTask(r.Context(), id)

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]interface{}{"data": nil})
}

// Update handles PUT /api/tasks/{id}
func (h *TaskHandler) Update(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	_ = id

	var input struct {
		Title string `json:"title"`
		Description string `json:"description"`
		Status string `json:"status"`
		Assignee string `json:"assignee"`
		Priority string `json:"priority"`
	}
	if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
		http.Error(w, "invalid request body", http.StatusBadRequest)
		return
	}

	// TODO: Validate and update
	// result, err := h.store.UpdateTask(r.Context(), id, input)

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]interface{}{"data": nil})
}

// Delete handles DELETE /api/tasks/{id}
func (h *TaskHandler) Delete(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	_ = id

	// TODO: Delete
	// err := h.store.DeleteTask(r.Context(), id)

	w.WriteHeader(http.StatusNoContent)
}

// RegisterRoutes registers Task routes on the given mux.
func (h *TaskHandler) RegisterRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /api/tasks", h.List)
	mux.HandleFunc("POST /api/tasks", h.Create)
	mux.HandleFunc("GET /api/tasks/{id}", h.Read)
	mux.HandleFunc("PUT /api/tasks/{id}", h.Update)
	mux.HandleFunc("DELETE /api/tasks/{id}", h.Delete)
}
