// forge-shell.tsx
// Generated by Sigil — do not edit manually

"use client";

import { Activity, BookOpen, Boxes, Clock, Hexagon, LayoutDashboard, MessageSquare, Puzzle, Rocket, ScrollText, Search, Server, Settings, Users } from "lucide-react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Separator } from "@/components/ui/separator";

export default function ForgeShell() {
  return (
    <>
    <div className="flex h-screen" id="root">
      <aside className="w-[240px] shrink-0 border-r border-border overflow-y-auto bg-muted/30">
        <div className="flex flex-col gap-2 p-4">
          <div className="flex flex-row gap-2 items-center">
            <Hexagon className="h-5 w-5" />
            <h3 className="scroll-m-20 text-2xl font-semibold tracking-tight text-foreground">Forge</h3>
          </div>
          <Separator />
          <nav className="flex flex-col gap-1" id="main-nav">
            <a href="/overview" className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium text-muted-foreground hover:bg-accent hover:text-accent-foreground transition-colors">
              <LayoutDashboard className="h-4 w-4" />
              Overview
            </a>
            <a href="/deployments" className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium text-muted-foreground hover:bg-accent hover:text-accent-foreground transition-colors">
              <Rocket className="h-4 w-4" />
              Deployments
            </a>
            <a href="/logs" className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium text-muted-foreground hover:bg-accent hover:text-accent-foreground transition-colors">
              <ScrollText className="h-4 w-4" />
              Logs
            </a>
            <a href="/monitoring" className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium text-muted-foreground hover:bg-accent hover:text-accent-foreground transition-colors">
              <Activity className="h-4 w-4" />
              Monitoring
            </a>
            <a href="/assets" className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium text-muted-foreground hover:bg-accent hover:text-accent-foreground transition-colors">
              <Server className="h-4 w-4" />
              Assets
            </a>
            <a href="/jobs" className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium text-muted-foreground hover:bg-accent hover:text-accent-foreground transition-colors">
              <Clock className="h-4 w-4" />
              Jobs
            </a>
          </nav>
          <Separator />
          <nav className="flex flex-col gap-1" id="secondary-nav">
            <a href="/workspaces" className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium text-muted-foreground hover:bg-accent hover:text-accent-foreground transition-colors">
              <Boxes className="h-4 w-4" />
              Workspaces
            </a>
            <a href="/users" className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium text-muted-foreground hover:bg-accent hover:text-accent-foreground transition-colors">
              <Users className="h-4 w-4" />
              Users
            </a>
            <a href="/integrations" className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium text-muted-foreground hover:bg-accent hover:text-accent-foreground transition-colors">
              <Puzzle className="h-4 w-4" />
              Integrations
            </a>
            <a href="/settings" className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium text-muted-foreground hover:bg-accent hover:text-accent-foreground transition-colors">
              <Settings className="h-4 w-4" />
              Settings
            </a>
          </nav>
          <div className="h-4" />
          <div className="flex flex-row gap-2 items-center">
            <Avatar className="h-8 w-8">
              <AvatarImage src="" alt="User" />
              <AvatarFallback>US</AvatarFallback>
            </Avatar>
            <p className="text-base text-muted-foreground">chrispian</p>
          </div>
        </div>
      </aside>
      <main className="flex-1 overflow-y-auto">
        <div className="flex flex-col gap-0">
          <div className="flex flex-row gap-4 justify-between items-center">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
              <Input type="search" placeholder="Search..." className="w-full pl-9 border-0 shadow-none focus-visible:ring-0 [&::-webkit-search-cancel-button]:hidden [&::-webkit-search-decoration]:hidden" />
            </div>
            <div className="flex flex-row gap-2 items-center">
              <Button variant="ghost">
                <MessageSquare className="mr-2 h-4 w-4" />
                Feedback
              </Button>
              <Button variant="ghost">
                <BookOpen className="mr-2 h-4 w-4" />
                Docs
              </Button>
              <DropdownMenu>
                <DropdownMenuTrigger className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium h-9 px-3 hover:bg-accent hover:text-accent-foreground">+</DropdownMenuTrigger>
                <DropdownMenuContent>
                  <DropdownMenuItem>New Deployment</DropdownMenuItem>
                  <DropdownMenuItem>New Asset</DropdownMenuItem>
                  <DropdownMenuItem>New Job</DropdownMenuItem>
                  <DropdownMenuItem>New Workspace</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </div>
          <Separator />
          <div className="flex flex-col gap-6 p-6">
            <p className="text-base text-muted-foreground">Select a page from the sidebar to get started.</p>
          </div>
        </div>
      </main>
    </div>
    </>
  );
}
