// types/comparisonset.ts
// Generated by Sigil — do not edit manually

export interface ComparisonSet {
  id: string;
  name: string;
  subject_count?: unknown;
  reference_count?: unknown;
}

export interface ComparisonSetInput {
  name: string;
  subject_count?: unknown;
  reference_count?: unknown;
}
