// types/deployment.ts
// Generated by Sigil — do not edit manually

export interface Deployment {
  id: string;
  name: string;
  status?: string;
  environment?: string;
  branch?: string;
  commit?: string;
  author?: string;
  duration?: string;
  createdAt?: string;
}

export interface DeploymentInput {
  name: string;
  status?: string;
  environment?: string;
  branch?: string;
  commit?: string;
  author?: string;
  duration?: string;
  createdAt?: string;
}
