// types/deploymentevent.ts
// Generated by Sigil — do not edit manually

export interface DeploymentEvent {
  id: string;
  title?: string;
  timestamp?: string;
  status?: string;
}

export interface DeploymentEventInput {
  title?: string;
  timestamp?: string;
  status?: string;
}
