// types/dimension.ts
// Generated by Sigil — do not edit manually

export interface Dimension {
  id: string;
  name: string;
  category?: string;
  weight?: unknown;
  description?: string;
}

export interface DimensionInput {
  name: string;
  category?: string;
  weight?: unknown;
  description?: string;
}
