// types/integration.ts
// Generated by Sigil — do not edit manually

export interface Integration {
  id: string;
  name: string;
  provider?: string;
  status?: string;
  connectedAt?: string;
}

export interface IntegrationInput {
  name: string;
  provider?: string;
  status?: string;
  connectedAt?: string;
}
