// types/repo.ts
// Generated by Sigil — do not edit manually

export interface Repo {
  id: string;
  name: string;
  url: string;
  description?: string;
  stack?: string;
  category?: string;
  is_own?: boolean;
  local_path?: string;
  score?: unknown;
  loc?: unknown;
  tags?: string;
}

export interface RepoInput {
  name: string;
  url: string;
  description?: string;
  stack?: string;
  category?: string;
  is_own?: boolean;
  local_path?: string;
  score?: unknown;
  loc?: unknown;
  tags?: string;
}
