// types/scheduledjob.ts
// Generated by Sigil — do not edit manually

export interface ScheduledJob {
  id: string;
  name: string;
  schedule: string;
  status?: string;
  lastRun?: string;
  nextRun?: string;
  runtime?: string;
  successRate?: string;
}

export interface ScheduledJobInput {
  name: string;
  schedule: string;
  status?: string;
  lastRun?: string;
  nextRun?: string;
  runtime?: string;
  successRate?: string;
}
