// types/scorecard.ts
// Generated by Sigil — do not edit manually

export interface Scorecard {
  id: string;
  repo_id?: string;
  repo_name?: string;
  lens_id?: string;
  lens_name?: string;
  overall?: unknown;
  scored_at?: string;
}

export interface ScorecardInput {
  repo_id?: string;
  repo_name?: string;
  lens_id?: string;
  lens_name?: string;
  overall?: unknown;
  scored_at?: string;
}
