// types/sigilpage.ts
// Generated by Sigil — do not edit manually

export interface SigilPage {
  id: string;
  title: string;
  overlay?: string;
  componentCount?: number;
}

export interface SigilPageInput {
  title: string;
  overlay?: string;
  componentCount?: number;
}
