// tailwind.config.ts — generated by Sigil, do not edit
import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/*.{ts,tsx}",
    "./src/pages/**/*.{ts,tsx}",
    "./src/components/**/*.{ts,tsx}",
    "./src/lib/**/*.{ts,tsx}",
    "./src/hooks/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "rgb(var(--background) / <alpha-value>)",
        foreground: "rgb(var(--foreground) / <alpha-value>)",
        card: {
          DEFAULT: "rgb(var(--card) / <alpha-value>)",
          foreground: "rgb(var(--card-foreground) / <alpha-value>)",
        },
        popover: {
          DEFAULT: "rgb(var(--popover) / <alpha-value>)",
          foreground: "rgb(var(--popover-foreground) / <alpha-value>)",
        },
        primary: {
          DEFAULT: "rgb(var(--primary) / <alpha-value>)",
          foreground: "rgb(var(--primary-foreground) / <alpha-value>)",
        },
        secondary: {
          DEFAULT: "rgb(var(--secondary) / <alpha-value>)",
          foreground: "rgb(var(--secondary-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "rgb(var(--muted) / <alpha-value>)",
          foreground: "rgb(var(--muted-foreground) / <alpha-value>)",
        },
        accent: {
          DEFAULT: "rgb(var(--accent) / <alpha-value>)",
          foreground: "rgb(var(--accent-foreground) / <alpha-value>)",
        },
        destructive: {
          DEFAULT: "rgb(var(--destructive) / <alpha-value>)",
          foreground: "rgb(var(--destructive-foreground) / <alpha-value>)",
        },
        border: "rgb(var(--border) / <alpha-value>)",
        input: "rgb(var(--input) / <alpha-value>)",
        ring: "rgb(var(--ring) / <alpha-value>)",
        sigil: {
          accent: "rgb(var(--sigil-accent) / <alpha-value>)",
          "accent-foreground": "rgb(var(--sigil-accent-foreground) / <alpha-value>)",
          "accent-hover": "rgb(var(--sigil-accent-hover) / <alpha-value>)",
          background: "rgb(var(--sigil-background) / <alpha-value>)",
          backlog: "rgb(var(--sigil-backlog) / <alpha-value>)",
          blocked: "rgb(var(--sigil-blocked) / <alpha-value>)",
          border: "rgb(var(--sigil-border) / <alpha-value>)",
          cancelled: "rgb(var(--sigil-cancelled) / <alpha-value>)",
          card: "rgb(var(--sigil-card) / <alpha-value>)",
          "card-foreground": "rgb(var(--sigil-card-foreground) / <alpha-value>)",
          danger: "rgb(var(--sigil-danger) / <alpha-value>)",
          "danger-foreground": "rgb(var(--sigil-danger-foreground) / <alpha-value>)",
          "danger-hover": "rgb(var(--sigil-danger-hover) / <alpha-value>)",
          doing: "rgb(var(--sigil-doing) / <alpha-value>)",
          done: "rgb(var(--sigil-done) / <alpha-value>)",
          foreground: "rgb(var(--sigil-foreground) / <alpha-value>)",
          info: "rgb(var(--sigil-info) / <alpha-value>)",
          input: "rgb(var(--sigil-input) / <alpha-value>)",
          muted: "rgb(var(--sigil-muted) / <alpha-value>)",
          "muted-foreground": "rgb(var(--sigil-muted-foreground) / <alpha-value>)",
          paused: "rgb(var(--sigil-paused) / <alpha-value>)",
          popover: "rgb(var(--sigil-popover) / <alpha-value>)",
          "popover-foreground": "rgb(var(--sigil-popover-foreground) / <alpha-value>)",
          primary: "rgb(var(--sigil-primary) / <alpha-value>)",
          "primary-foreground": "rgb(var(--sigil-primary-foreground) / <alpha-value>)",
          queued: "rgb(var(--sigil-queued) / <alpha-value>)",
          review: "rgb(var(--sigil-review) / <alpha-value>)",
          ring: "rgb(var(--sigil-ring) / <alpha-value>)",
          secondary: "rgb(var(--sigil-secondary) / <alpha-value>)",
          "secondary-foreground": "rgb(var(--sigil-secondary-foreground) / <alpha-value>)",
          success: "rgb(var(--sigil-success) / <alpha-value>)",
          surface: "rgb(var(--sigil-surface) / <alpha-value>)",
          "surface-2": "rgb(var(--sigil-surface-2) / <alpha-value>)",
          text: "rgb(var(--sigil-text) / <alpha-value>)",
          "text-muted": "rgb(var(--sigil-text-muted) / <alpha-value>)",
          todo: "rgb(var(--sigil-todo) / <alpha-value>)",
          warning: "rgb(var(--sigil-warning) / <alpha-value>)",
        },
      },
      fontFamily: {
        sans: ["var(--sigil-font-sans)"],
        mono: ["var(--sigil-font-mono)"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        "sigil-lg": "var(--sigil-lg)",
        "sigil-md": "var(--sigil-md)",
        "sigil-sm": "var(--sigil-sm)",
        "sigil-xl": "var(--sigil-xl)",
      },
    },
  },
  plugins: [],
};

export default config;
