// forge-workspaces.tsx
// Generated by Sigil — do not edit manually

"use client";

import { useRouter } from "next/navigation";
import { Plus, Search } from "lucide-react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { DataTable } from "@/components/data-table";
import { useWorkspace } from "@/hooks/use-workspace";

export default function ForgeWorkspaces() {
  const router = useRouter();
  const { data: workspace, isLoading: workspaceLoading } = useWorkspace();

  return (
    <div className="min-h-screen bg-background text-foreground font-sans">
    <div className="flex flex-col gap-6 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight text-foreground">Workspaces</h1>
        <div className="flex flex-row gap-2">
          <Select>
            <SelectTrigger>
              <SelectValue placeholder="All Plans" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Plans</SelectItem>
              <SelectItem value="free">Free</SelectItem>
              <SelectItem value="pro">Pro</SelectItem>
              <SelectItem value="enterprise">Enterprise</SelectItem>
            </SelectContent>
          </Select>
          <Button variant="default" onClick={() => router.push("/forge-workspaces")}>
            <Plus className="mr-2 h-4 w-4" />
            New Workspace
          </Button>
        </div>
      </div>
      <div className="relative">
        <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
        <Input type="search" placeholder="Search workspaces..." className="w-full pl-9 [&::-webkit-search-cancel-button]:hidden [&::-webkit-search-decoration]:hidden" />
      </div>
      <div className="grid grid-cols-3 gap-4">
        {workspace.map((item) => (
          <div key={item.name}>
            <Card>
              <CardHeader>
                <CardTitle>{item.name}</CardTitle>
                <CardDescription>{item.slug}</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex flex-row gap-4 justify-between items-center">
                  <div className="flex flex-row gap-2 items-center">
                    <Avatar>
                      <AvatarImage src="" alt={item.owner} />
                      <AvatarFallback>?</AvatarFallback>
                    </Avatar>
                    <p className="text-base">{item.owner}</p>
                  </div>
                  <div className="flex flex-row gap-2 items-center">
                    <Badge variant="outline" className="border-blue-500/30 bg-blue-500/10 text-blue-600 dark:text-blue-400">{item.plan}</Badge>
                    <p className="text-sm text-muted-foreground">{`${item.memberCount} members`}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        ))}
      </div>
      <Card className="border-0 shadow-none ring-0">
        <CardHeader>
          <CardTitle>All Workspaces</CardTitle>
        </CardHeader>
        <CardContent>
          <DataTable
            data={workspace ?? []}
            columns={[
              { accessorKey: "name", header: "Name" },
              { accessorKey: "slug", header: "Slug" },
              { accessorKey: "owner", header: "Owner" },
              { accessorKey: "plan", header: "Plan" },
              { accessorKey: "memberCount", header: "Members" },
              { accessorKey: "deploymentCount", header: "Deployments" },
              { accessorKey: "createdAt", header: "Created" },
            ]}
          />
        </CardContent>
      </Card>
    </div>
    </div>
  );
}
