// Generated by Sigil — do not edit manually
"use client";

const API_BASE = process.env.NEXT_PUBLIC_SE_API_URL ?? "http://localhost:8081";

interface ListResponse<T> {
  data: T[];
  meta: {
    total: number;
    page: number;
    pageSize: number;
    pageCount: number;
  };
}

interface ItemResponse<T> {
  data: T;
}

export async function fetchList<T>(
  resource: string,
  params?: Record<string, string | number | undefined>,
): Promise<T[]> {
  const url = new URL(`/api/${resource}`, API_BASE);
  if (params) {
    for (const [k, v] of Object.entries(params)) {
      if (v !== undefined && v !== "") url.searchParams.set(k, String(v));
    }
  }
  if (!url.searchParams.has("pageSize")) {
    url.searchParams.set("pageSize", "1000");
  }
  const res = await fetch(url.toString());
  if (!res.ok) throw new Error(`API ${res.status}: ${resource}`);
  const json: ListResponse<T> = await res.json();
  return json.data;
}

export async function fetchItem<T>(
  resource: string,
  id: string,
): Promise<T> {
  const res = await fetch(`${API_BASE}/api/${resource}/${id}`);
  if (!res.ok) throw new Error(`API ${res.status}: ${resource}/${id}`);
  const json: ItemResponse<T> = await res.json();
  return json.data;
}

export async function postItem<T>(
  resource: string,
  data: Record<string, unknown>,
): Promise<T> {
  const res = await fetch(`${API_BASE}/api/${resource}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(data),
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(text || `API ${res.status}: POST ${resource}`);
  }
  const json: ItemResponse<T> = await res.json();
  return json.data;
}

export async function updateItem<T>(
  resource: string,
  id: string,
  data: Record<string, unknown>,
): Promise<T> {
  const res = await fetch(`${API_BASE}/api/${resource}/${id}`, {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(data),
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(text || `API ${res.status}: PUT ${resource}/${id}`);
  }
  const json: ItemResponse<T> = await res.json();
  return json.data;
}

export async function deleteItem(
  resource: string,
  id: string,
): Promise<void> {
  const res = await fetch(`${API_BASE}/api/${resource}/${id}`, {
    method: "DELETE",
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(text || `API ${res.status}: DELETE ${resource}/${id}`);
  }
}
