// se-repos.tsx
// Generated by Sigil — do not edit manually

"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { toast } from "sonner";
import { Loader2, Plus, Search } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Toaster } from "@/components/ui/sonner";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { DataTable } from "@/components/data-table";
import { YamlImportButton } from "@/components/yaml-import-button";
import { useRepo } from "@/hooks/use-repo";
import { postItem } from "@/lib/api";

export default function SeRepos() {
  const router = useRouter();
  const [modalOpen, setModalOpen] = useState(false);
  const [formName, setFormName] = useState("");
  const [formUrl, setFormUrl] = useState("");
  const [formDescription, setFormDescription] = useState("");
  const [formCategory, setFormCategory] = useState("");
  const [formStack, setFormStack] = useState("");
  const [formIsOwn, setFormIsOwn] = useState(false);
    const handleCreateRepo = async () => {
    try {
      await postItem("repos", {
        name: formName,
        url: formUrl,
        description: formDescription,
        category: formCategory,
        stack: formStack,
        is_own: formIsOwn,
      });
      toast.success("Repo created");
      setModalOpen(false);
      setFormName("");
      setFormUrl("");
      setFormDescription("");
      setFormCategory("");
      setFormStack("");
      setFormIsOwn(false);
      refetchRepo();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to create repo");
    }
  };


  const [searchRepo, setSearchRepo] = useState("");
  const [filterRepoCategory, setFilterRepoCategory] = useState("all");
  const [filterRepoStack, setFilterRepoStack] = useState("all");

  const { data: repo, isLoading: repoLoading, refetch: refetchRepo } = useRepo();

  if (repoLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-5 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <div className="flex flex-col gap-1">
          <h1 className="text-2xl font-semibold tracking-tight text-foreground">Repositories</h1>
          <p className="text-sm text-muted-foreground">112 repos tracked across the AI agent landscape</p>
        </div>
        <div className="flex flex-row gap-2">
          <YamlImportButton
            endpoint="/api/repos/import"
            label="Import YAML"
          />
          <Dialog open={modalOpen} onOpenChange={setModalOpen}>
            <DialogTrigger render={<Button variant="default" />}>
              <Plus className="mr-2 h-4 w-4" />
              Add Repo
            </DialogTrigger>
            <DialogContent className="sm:max-w-lg">
              <DialogHeader>
                <DialogTitle>Add Repository</DialogTitle>
              </DialogHeader>
              <div className="flex flex-col gap-4 py-4">
                <div className="flex flex-col gap-1.5">
                  <Label htmlFor="name">Name</Label>
                  <Input id="name" type="text" placeholder="e.g., langchain" value={formName} onChange={(e) => setFormName(e.target.value)} />
                </div>
                <div className="flex flex-col gap-1.5">
                  <Label htmlFor="url">URL</Label>
                  <Input id="url" type="text" placeholder="https://github.com/org/repo" value={formUrl} onChange={(e) => setFormUrl(e.target.value)} />
                </div>
                <div className="flex flex-col gap-1.5">
                  <Label htmlFor="description">Description</Label>
                  <Textarea id="description" placeholder="" rows={2} value={formDescription} onChange={(e) => setFormDescription(e.target.value)} />
                </div>
                <div className="flex flex-col gap-1.5">
                  <Label htmlFor="category">Category</Label>
                  <Select value={formCategory} onValueChange={(v) => v && setFormCategory(v)}>
                    <SelectTrigger>
                      <SelectValue placeholder="Select..." />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="framework">Framework</SelectItem>
                      <SelectItem value="library">Library</SelectItem>
                      <SelectItem value="tool">Tool</SelectItem>
                      <SelectItem value="platform">Platform</SelectItem>
                      <SelectItem value="sdk">SDK</SelectItem>
                      <SelectItem value="runtime">Runtime</SelectItem>
                      <SelectItem value="infra">Infrastructure</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="flex flex-col gap-1.5">
                  <Label htmlFor="stack">Primary Stack</Label>
                  <Select value={formStack} onValueChange={(v) => v && setFormStack(v)}>
                    <SelectTrigger>
                      <SelectValue placeholder="Select..." />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="TypeScript">TypeScript</SelectItem>
                      <SelectItem value="Go">Go</SelectItem>
                      <SelectItem value="Rust">Rust</SelectItem>
                      <SelectItem value="Python">Python</SelectItem>
                      <SelectItem value="Java">Java</SelectItem>
                      <SelectItem value="Ruby">Ruby</SelectItem>
                      <SelectItem value="C#">C#</SelectItem>
                      <SelectItem value="Multi">Multi-language</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="flex flex-col gap-1.5">
                  <Label htmlFor="is_own">Own Project</Label>
                  <Switch id="is_own" checked={formIsOwn} onCheckedChange={(v) => setFormIsOwn(v)} />
                </div>
              </div>
              <DialogFooter>
                <Button variant="outline" onClick={() => setModalOpen(false)}>Cancel</Button>
                <Button onClick={handleCreateRepo}>Save</Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>
      </div>
      <div className="flex flex-row gap-3 items-center">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input type="search" placeholder="Search repos by name, description, or tags..." className="w-full pl-9 [&::-webkit-search-cancel-button]:hidden [&::-webkit-search-decoration]:hidden" value={searchRepo} onChange={(e) => setSearchRepo(e.target.value)} />
        </div>
        <Select onValueChange={(v) => setFilterRepoCategory(v as string)}>
          <SelectTrigger>
            <SelectValue placeholder="All Categories" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Categories</SelectItem>
            <SelectItem value="framework">Framework</SelectItem>
            <SelectItem value="library">Library</SelectItem>
            <SelectItem value="tool">Tool</SelectItem>
            <SelectItem value="platform">Platform</SelectItem>
            <SelectItem value="sdk">SDK</SelectItem>
          </SelectContent>
        </Select>
        <Select onValueChange={(v) => setFilterRepoStack(v as string)}>
          <SelectTrigger>
            <SelectValue placeholder="All Stacks" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Stacks</SelectItem>
            <SelectItem value="TypeScript">TypeScript</SelectItem>
            <SelectItem value="Go">Go</SelectItem>
            <SelectItem value="Rust">Rust</SelectItem>
            <SelectItem value="Python">Python</SelectItem>
          </SelectContent>
        </Select>
      </div>
      <Card>
        <CardHeader>
          <CardTitle>Repo Catalog</CardTitle>
          <CardDescription>Click a row to view details — multi-select for bulk actions</CardDescription>
        </CardHeader>
        <CardContent>
          <DataTable
            data={(repo ?? [])
              .filter((item) => filterRepoCategory === "all" || item.category === filterRepoCategory)
              .filter((item) => filterRepoStack === "all" || item.stack === filterRepoStack)
              .filter((item) => {
                if (!searchRepo) return true;
                const q = searchRepo.toLowerCase();
                return Object.values(item).some((v) => String(v).toLowerCase().includes(q));
              })}
            columns={[
              { accessorKey: "name", header: "Name" },
              {
                accessorKey: "category",
                header: "Category",
                cell: ({ row }: { row: { getValue: (k: string) => unknown } }) => {
                  const v = String(row.getValue("category") ?? "");
                  const variants: Record<string, string> = { "tool": "success", "platform": "warning", "sdk": "info", "runtime": "default", "infra": "warning", "framework": "info", "library": "default" };
                  const variant = variants[v] ?? variants[v.toLowerCase()] ?? "default";
                  return <Badge variant={variant === "danger" ? "destructive" : variant === "success" || variant === "warning" || variant === "info" ? "outline" : "secondary"} className={
                    variant === "success" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-400" :
                    variant === "warning" ? "border-amber-500/30 bg-amber-500/10 text-amber-400" :
                    variant === "info" ? "border-blue-500/30 bg-blue-500/10 text-blue-400" :
                    variant === "danger" ? "" : ""
                  }>{v}</Badge>;
                },
              },
              {
                accessorKey: "stack",
                header: "Stack",
                cell: ({ row }: { row: { getValue: (k: string) => unknown } }) => {
                  const v = String(row.getValue("stack") ?? "");
                  const variants: Record<string, string> = { "Go": "success", "Rust": "warning", "Python": "default", "Java": "danger", "TypeScript": "info" };
                  const variant = variants[v] ?? variants[v.toLowerCase()] ?? "default";
                  return <Badge variant={variant === "danger" ? "destructive" : variant === "success" || variant === "warning" || variant === "info" ? "outline" : "secondary"} className={
                    variant === "success" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-400" :
                    variant === "warning" ? "border-amber-500/30 bg-amber-500/10 text-amber-400" :
                    variant === "info" ? "border-blue-500/30 bg-blue-500/10 text-blue-400" :
                    variant === "danger" ? "" : ""
                  }>{v}</Badge>;
                },
              },
              { accessorKey: "score", header: "Score" },
              { accessorKey: "loc", header: "LoC" },
              { accessorKey: "tags", header: "Tags" },
            ]}
            emptyMessage="No matching results found."
            onRowClick={(row) => router.push(`/repo-detail/${(row as { id: string }).id}`)}
          />
        </CardContent>
      </Card>
    </div>
    <Toaster />
    </>
  );
}
