// forge-deployment-detail.tsx
// Generated by Sigil — do not edit manually

"use client";

import { useParams } from "next/navigation";
import { toast } from "sonner";
import { Loader2, RefreshCw, ScrollText, Trash2, Undo2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from "@/components/ui/breadcrumb";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Separator } from "@/components/ui/separator";
import { Toaster } from "@/components/ui/sonner";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useDeploymentById } from "@/hooks/use-deployment";
import { useDeploymentEvent } from "@/hooks/use-deploymentevent";

export default function ForgeDeploymentDetail() {
  const params = useParams();
  const { data: deployment, isLoading: deploymentLoading } = useDeploymentById(params.id as string);
  const { data: deploymentEvent, isLoading: deploymentEventLoading } = useDeploymentEvent();

  if (deploymentLoading || deploymentEventLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-6 p-6">
      <Breadcrumb>
        <BreadcrumbList>
          <BreadcrumbItem>
            <BreadcrumbLink href="/deployments">Deployments</BreadcrumbLink>
          </BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>
            <BreadcrumbPage>{deployment?.name}</BreadcrumbPage>
          </BreadcrumbItem>
        </BreadcrumbList>
      </Breadcrumb>
      <div className="flex flex-row gap-4 justify-between items-center">
        <div className="flex flex-row gap-3 items-center">
          <h2 className="scroll-m-20 text-3xl font-semibold tracking-tight text-foreground">{deployment?.name}</h2>
          <Badge variant="default">{deployment?.status}</Badge>
        </div>
        <div className="flex flex-row gap-2">
          <Button variant="default" onClick={() => fetch(`/api/deployments/${params.id}/redeploy`, { method: "POST" }).then(() => toast.success("Redeployment started"))}>
            <RefreshCw className="mr-2 h-4 w-4" />
            Redeploy
          </Button>
          <DropdownMenu>
            <DropdownMenuTrigger className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium h-9 px-3 hover:bg-accent hover:text-accent-foreground">...</DropdownMenuTrigger>
            <DropdownMenuContent>
              <DropdownMenuItem>
                <Undo2 className="mr-2 h-4 w-4" />
                Rollback
              </DropdownMenuItem>
              <DropdownMenuItem>
                <ScrollText className="mr-2 h-4 w-4" />
                View Logs
              </DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem>
                <Trash2 className="mr-2 h-4 w-4" />
                Delete
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </div>
      <Separator />
      <Tabs defaultValue="overview">
        <TabsList>
          <TabsTrigger value="overview">Overview</TabsTrigger>
          <TabsTrigger value="logs">Logs</TabsTrigger>
          <TabsTrigger value="domains">Domains</TabsTrigger>
        </TabsList>
        <TabsContent value="overview">
          <Card>
            <CardContent>
              <div className="space-y-4">
                <div>
                  <dt className="text-sm font-medium text-muted-foreground">Environment</dt>
                  <dd className="text-sm mt-1">{deployment?.environment}</dd>
                </div>
                <div>
                  <dt className="text-sm font-medium text-muted-foreground">Branch</dt>
                  <dd className="text-sm mt-1">{deployment?.branch}</dd>
                </div>
                <div>
                  <dt className="text-sm font-medium text-muted-foreground">Commit</dt>
                  <dd className="text-sm mt-1">{deployment?.commit}</dd>
                </div>
                <div>
                  <dt className="text-sm font-medium text-muted-foreground">Author</dt>
                  <dd className="text-sm mt-1">{deployment?.author}</dd>
                </div>
                <div>
                  <dt className="text-sm font-medium text-muted-foreground">Duration</dt>
                  <dd className="text-sm mt-1">{deployment?.duration}</dd>
                </div>
                <div>
                  <dt className="text-sm font-medium text-muted-foreground">Started</dt>
                  <dd className="text-sm mt-1">{deployment?.createdAt}</dd>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value="logs">
          <Card>
            <CardHeader>
              <CardTitle>Build Log</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {deploymentEvent?.map((item, i) => (
                  <div key={i} className="flex gap-4">
                    <div className="flex flex-col items-center">
                      <div className="h-2 w-2 rounded-full bg-primary" />
                      <div className="flex-1 w-px bg-border" />
                    </div>
                    <div className="pb-4">
                      <p className="text-sm font-medium">{item.title}</p>
                      <p className="text-xs text-muted-foreground">{item.timestamp}</p>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value="domains">
          <Card>
            <CardContent>
              <p className="text-base text-muted-foreground">Custom domains and aliases.</p>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
    <Toaster />
    </>
  );
}
