package gotempl

import (
	"strings"
	"testing"

	"github.com/hollis-labs/sigil/internal/config"
	"github.com/hollis-labs/sigil/internal/renderer"
)

func TestRenderSimplePage(t *testing.T) {
	ctx := &renderer.RenderContext{
		Page: &config.Page{
			ID:      "test-page",
			Title:   "Test Page",
			Overlay: "page",
			Layout: config.Component{
				ID:   "root",
				Type: "rows",
				Props: map[string]interface{}{
					"gap":     "4",
					"padding": "6",
				},
				Children: []config.Component{
					{
						ID:   "title",
						Type: "heading",
						Props: map[string]interface{}{
							"level": "2",
							"text":  "Hello World",
						},
					},
				},
			},
		},
	}

	files, err := renderPage(ctx)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(files) != 1 {
		t.Fatalf("expected 1 file, got %d", len(files))
	}

	file := files[0]
	if file.Path != "pages/test_page.templ" {
		t.Errorf("expected path 'pages/test_page.templ', got %q", file.Path)
	}

	content := string(file.Content)
	if !strings.Contains(content, "templ TestPage()") {
		t.Error("expected templ function declaration")
	}
	if !strings.Contains(content, "Generated by Sigil") {
		t.Error("expected generated header comment")
	}
	if !strings.Contains(content, "flex flex-col") {
		t.Error("expected rows rendered as flex-col")
	}
	if !strings.Contains(content, "Hello World") {
		t.Error("expected heading text")
	}
}

func TestRenderPageWithColumns(t *testing.T) {
	ctx := &renderer.RenderContext{
		Page: &config.Page{
			ID:      "col-page",
			Title:   "Columns Page",
			Overlay: "page",
			Layout: config.Component{
				ID:   "root",
				Type: "columns",
				Props: map[string]interface{}{
					"justify": "between",
					"align":   "center",
				},
				Children: []config.Component{
					{Type: "heading", Props: map[string]interface{}{"text": "Left"}},
					{Type: "button", Props: map[string]interface{}{"label": "Right", "variant": "primary"}},
				},
			},
		},
	}

	files, err := renderPage(ctx)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := string(files[0].Content)
	if !strings.Contains(content, "justify-between") {
		t.Error("expected justify-between class")
	}
	if !strings.Contains(content, "items-center") {
		t.Error("expected items-center class")
	}
	if !strings.Contains(content, "sigil-btn sigil-btn-primary") {
		t.Error("expected button with primary variant")
	}
}

func TestRenderPageWithActions(t *testing.T) {
	ctx := &renderer.RenderContext{
		Page: &config.Page{
			ID:      "action-page",
			Title:   "Action Page",
			Overlay: "page",
			Layout: config.Component{
				ID:   "root",
				Type: "rows",
				Children: []config.Component{
					{
						ID:   "nav-btn",
						Type: "button",
						Props: map[string]interface{}{
							"label":   "Go",
							"variant": "primary",
						},
						Actions: map[string]config.Action{
							"click": {
								Type: "navigate",
								URL:  "/dashboard",
							},
						},
					},
				},
			},
		},
	}

	files, err := renderPage(ctx)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := string(files[0].Content)
	if !strings.Contains(content, `hx-get="/dashboard"`) {
		t.Error("expected hx-get for navigate action")
	}
	if !strings.Contains(content, `hx-push-url="true"`) {
		t.Error("expected hx-push-url for navigate action")
	}
}

func TestRenderPageWithSearchBar(t *testing.T) {
	ctx := &renderer.RenderContext{
		Page: &config.Page{
			ID:      "search-page",
			Title:   "Search Page",
			Overlay: "page",
			Layout: config.Component{
				ID:   "root",
				Type: "rows",
				Children: []config.Component{
					{
						Type: "search-bar",
						Props: map[string]interface{}{
							"placeholder": "Search...",
							"datasource":  "Sprint",
							"debounce":    "300",
						},
					},
				},
			},
		},
	}

	files, err := renderPage(ctx)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := string(files[0].Content)
	if !strings.Contains(content, `type="search"`) {
		t.Error("expected search input type")
	}
	if !strings.Contains(content, `hx-get="/api/sprints"`) {
		t.Error("expected hx-get for datasource")
	}
	if !strings.Contains(content, `delay:300ms`) {
		t.Error("expected debounce delay")
	}
}

func TestRenderPageWithGrid(t *testing.T) {
	ctx := &renderer.RenderContext{
		Page: &config.Page{
			ID:      "grid-page",
			Title:   "Grid Page",
			Overlay: "page",
			Layout: config.Component{
				ID:   "root",
				Type: "grid",
				Props: map[string]interface{}{
					"columns": "3",
					"gap":     "4",
				},
			},
		},
	}

	files, err := renderPage(ctx)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := string(files[0].Content)
	if !strings.Contains(content, "grid grid-cols-3") {
		t.Error("expected grid classes")
	}
}

func TestRenderDataTable(t *testing.T) {
	ctx := &renderer.RenderContext{
		Page: &config.Page{
			ID:      "table-page",
			Title:   "Table Page",
			Overlay: "page",
			Layout: config.Component{
				ID:   "root",
				Type: "rows",
				Children: []config.Component{
					{
						Type: "data-table",
						Props: map[string]interface{}{
							"datasource": "Sprint",
							"columns": []interface{}{
								map[string]interface{}{"field": "name", "label": "Name", "sortable": true},
								map[string]interface{}{"field": "status", "label": "Status"},
							},
						},
					},
				},
			},
		},
	}

	files, err := renderPage(ctx)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := string(files[0].Content)
	if !strings.Contains(content, "sigil-data-table") {
		t.Error("expected data-table class")
	}
	if !strings.Contains(content, "<th") {
		t.Error("expected table header")
	}
	if !strings.Contains(content, "hx-trigger=\"load\"") {
		t.Error("expected HTMX load trigger")
	}
}

func TestToSnakeCase(t *testing.T) {
	tests := []struct {
		input, expected string
	}{
		{"sprint-dashboard", "sprint_dashboard"},
		{"login", "login"},
		{"my-cool-page", "my_cool_page"},
	}
	for _, tt := range tests {
		got := toSnakeCase(tt.input)
		if got != tt.expected {
			t.Errorf("toSnakeCase(%q) = %q, want %q", tt.input, got, tt.expected)
		}
	}
}

func TestToPascalCase(t *testing.T) {
	tests := []struct {
		input, expected string
	}{
		{"sprint-dashboard", "SprintDashboard"},
		{"login", "Login"},
		{"my_cool_page", "MyCoolPage"},
	}
	for _, tt := range tests {
		got := toPascalCase(tt.input)
		if got != tt.expected {
			t.Errorf("toPascalCase(%q) = %q, want %q", tt.input, got, tt.expected)
		}
	}
}

func TestRenderHTMXAttrs(t *testing.T) {
	tests := []struct {
		name     string
		actions  map[string]config.Action
		contains []string
	}{
		{
			name: "navigate with URL",
			actions: map[string]config.Action{
				"click": {Type: "navigate", URL: "/dashboard"},
			},
			contains: []string{`hx-get="/dashboard"`, `hx-push-url="true"`},
		},
		{
			name: "navigate with page",
			actions: map[string]config.Action{
				"click": {Type: "navigate", Page: "home"},
			},
			contains: []string{`hx-get="/ui/pages/home"`},
		},
		{
			name: "http POST",
			actions: map[string]config.Action{
				"click": {Type: "http", URL: "/api/sprints", Method: "POST"},
			},
			contains: []string{`hx-post="/api/sprints"`},
		},
		{
			name: "http DELETE",
			actions: map[string]config.Action{
				"click": {Type: "http", URL: "/api/sprints/1", Method: "DELETE"},
			},
			contains: []string{`hx-delete="/api/sprints/1"`},
		},
		{
			name: "confirm with nested",
			actions: map[string]config.Action{
				"click": {
					Type:    "confirm",
					Message: "Are you sure?",
					OnConfirm: &config.Action{
						Type: "http", URL: "/api/delete", Method: "DELETE",
					},
				},
			},
			contains: []string{`hx-confirm="Are you sure?"`, `hx-delete="/api/delete"`},
		},
		{
			name:     "empty actions",
			actions:  map[string]config.Action{},
			contains: []string{},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := renderHTMXAttrs(tt.actions)
			for _, expected := range tt.contains {
				if !strings.Contains(result, expected) {
					t.Errorf("expected %q in result %q", expected, result)
				}
			}
		})
	}
}

func TestRenderUnknownComponent(t *testing.T) {
	ctx := &renderer.RenderContext{
		Page: &config.Page{
			ID:      "unknown-page",
			Title:   "Unknown Page",
			Overlay: "page",
			Layout: config.Component{
				ID:   "root",
				Type: "rows",
				Children: []config.Component{
					{
						ID:   "custom",
						Type: "my-custom-widget",
					},
				},
			},
		},
	}

	files, err := renderPage(ctx)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := string(files[0].Content)
	if !strings.Contains(content, `data-component="my-custom-widget"`) {
		t.Error("expected data-component attribute for unknown type")
	}
}
