package gotempl

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/chrispian/sigil/internal/renderer"
)

// renderDataSourceStubs generates Go handler stub files for a datasource.
func renderDataSourceStubs(ds *renderer.DataSourceManifest) ([]renderer.OutputFile, error) {
	fileName := toSnakeCase(ds.Alias) + "_handler.go"
	handlerName := toPascalCase(ds.Alias) + "Handler"
	typeName := toPascalCase(ds.Alias)

	var buf bytes.Buffer

	// Header
	fmt.Fprintf(&buf, "// %s_handler.go\n", toSnakeCase(ds.Alias))
	buf.WriteString("// Generated by Sigil — fill in query logic, do not edit structure.\n")
	buf.WriteString("package handlers\n\n")

	// Imports
	buf.WriteString("import (\n")
	buf.WriteString("\t\"encoding/json\"\n")
	buf.WriteString("\t\"net/http\"\n")
	if needsTimeImport(ds.Fields) {
		buf.WriteString("\t\"time\"\n")
	}
	buf.WriteString(")\n\n")

	// Suppress unused import warnings
	if needsTimeImport(ds.Fields) {
		buf.WriteString("var _ time.Time\n\n")
	}

	// Handler struct
	fmt.Fprintf(&buf, "// %s handles %s CRUD operations.\n", handlerName, typeName)
	fmt.Fprintf(&buf, "type %s struct {\n", handlerName)
	buf.WriteString("\t// TODO: Add your data store dependency\n")
	buf.WriteString("}\n\n")

	// Constructor
	fmt.Fprintf(&buf, "// New%s creates a new %s.\n", handlerName, handlerName)
	fmt.Fprintf(&buf, "func New%s() *%s {\n", handlerName, handlerName)
	fmt.Fprintf(&buf, "\treturn &%s{}\n", handlerName)
	buf.WriteString("}\n\n")

	// List handler
	hasList := ds.HasCapability("search") || ds.HasCapability("filter") ||
		ds.HasCapability("sort") || ds.HasCapability("paginate") || ds.HasCapability("list")
	if hasList {
		listRoute := endpointRoute(ds.Endpoints, "list")
		fmt.Fprintf(&buf, "// List handles %s\n", listRoute)
		fmt.Fprintf(&buf, "func (h *%s) List(w http.ResponseWriter, r *http.Request) {\n", handlerName)
		buf.WriteString("\t// Query params: search, filter[field], sort, direction, page, pageSize\n")
		fmt.Fprintf(&buf, "\t// TODO: Query your data store\n")
		fmt.Fprintf(&buf, "\t// results, total, err := h.store.List%ss(r.Context(), params)\n\n", typeName)
		buf.WriteString("\tw.Header().Set(\"Content-Type\", \"application/json\")\n")
		buf.WriteString("\tjson.NewEncoder(w).Encode(map[string]interface{}{\n")
		buf.WriteString("\t\t\"data\": []interface{}{},\n")
		buf.WriteString("\t\t\"meta\": map[string]interface{}{\n")
		buf.WriteString("\t\t\t\"total\":    0,\n")
		buf.WriteString("\t\t\t\"page\":     1,\n")
		buf.WriteString("\t\t\t\"per_page\": 25,\n")
		buf.WriteString("\t\t},\n")
		buf.WriteString("\t})\n")
		buf.WriteString("}\n\n")
	}

	// Create handler
	if ds.HasCapability("create") {
		createRoute := endpointRoute(ds.Endpoints, "create")
		fmt.Fprintf(&buf, "// Create handles %s\n", createRoute)
		fmt.Fprintf(&buf, "func (h *%s) Create(w http.ResponseWriter, r *http.Request) {\n", handlerName)
		writeInputStruct(&buf, ds.Fields)
		buf.WriteString("\tif err := json.NewDecoder(r.Body).Decode(&input); err != nil {\n")
		buf.WriteString("\t\thttp.Error(w, \"invalid request body\", http.StatusBadRequest)\n")
		buf.WriteString("\t\treturn\n")
		buf.WriteString("\t}\n\n")
		buf.WriteString("\t// TODO: Validate and create\n")
		fmt.Fprintf(&buf, "\t// result, err := h.store.Create%s(r.Context(), input)\n\n", typeName)
		buf.WriteString("\tw.WriteHeader(http.StatusCreated)\n")
		buf.WriteString("\tw.Header().Set(\"Content-Type\", \"application/json\")\n")
		buf.WriteString("\tjson.NewEncoder(w).Encode(map[string]interface{}{\"data\": nil})\n")
		buf.WriteString("}\n\n")
	}

	// Read handler
	if _, ok := ds.Endpoints["read"]; ok {
		readRoute := endpointRoute(ds.Endpoints, "read")
		fmt.Fprintf(&buf, "// Read handles %s\n", readRoute)
		fmt.Fprintf(&buf, "func (h *%s) Read(w http.ResponseWriter, r *http.Request) {\n", handlerName)
		buf.WriteString("\tid := r.PathValue(\"id\")\n")
		buf.WriteString("\t_ = id\n\n")
		buf.WriteString("\t// TODO: Fetch by ID\n")
		fmt.Fprintf(&buf, "\t// result, err := h.store.Get%s(r.Context(), id)\n\n", typeName)
		buf.WriteString("\tw.Header().Set(\"Content-Type\", \"application/json\")\n")
		buf.WriteString("\tjson.NewEncoder(w).Encode(map[string]interface{}{\"data\": nil})\n")
		buf.WriteString("}\n\n")
	}

	// Update handler
	if ds.HasCapability("update") {
		updateRoute := endpointRoute(ds.Endpoints, "update")
		fmt.Fprintf(&buf, "// Update handles %s\n", updateRoute)
		fmt.Fprintf(&buf, "func (h *%s) Update(w http.ResponseWriter, r *http.Request) {\n", handlerName)
		buf.WriteString("\tid := r.PathValue(\"id\")\n")
		buf.WriteString("\t_ = id\n\n")
		writeInputStruct(&buf, ds.Fields)
		buf.WriteString("\tif err := json.NewDecoder(r.Body).Decode(&input); err != nil {\n")
		buf.WriteString("\t\thttp.Error(w, \"invalid request body\", http.StatusBadRequest)\n")
		buf.WriteString("\t\treturn\n")
		buf.WriteString("\t}\n\n")
		buf.WriteString("\t// TODO: Validate and update\n")
		fmt.Fprintf(&buf, "\t// result, err := h.store.Update%s(r.Context(), id, input)\n\n", typeName)
		buf.WriteString("\tw.Header().Set(\"Content-Type\", \"application/json\")\n")
		buf.WriteString("\tjson.NewEncoder(w).Encode(map[string]interface{}{\"data\": nil})\n")
		buf.WriteString("}\n\n")
	}

	// Delete handler
	if ds.HasCapability("delete") {
		deleteRoute := endpointRoute(ds.Endpoints, "delete")
		fmt.Fprintf(&buf, "// Delete handles %s\n", deleteRoute)
		fmt.Fprintf(&buf, "func (h *%s) Delete(w http.ResponseWriter, r *http.Request) {\n", handlerName)
		buf.WriteString("\tid := r.PathValue(\"id\")\n")
		buf.WriteString("\t_ = id\n\n")
		buf.WriteString("\t// TODO: Delete\n")
		fmt.Fprintf(&buf, "\t// err := h.store.Delete%s(r.Context(), id)\n\n", typeName)
		buf.WriteString("\tw.WriteHeader(http.StatusNoContent)\n")
		buf.WriteString("}\n\n")
	}

	// RegisterRoutes
	fmt.Fprintf(&buf, "// RegisterRoutes registers %s routes on the given mux.\n", typeName)
	fmt.Fprintf(&buf, "func (h *%s) RegisterRoutes(mux *http.ServeMux) {\n", handlerName)
	routeOrder := []string{"list", "create", "read", "update", "delete"}
	for _, key := range routeOrder {
		route, ok := ds.Endpoints[key]
		if !ok {
			continue
		}
		methodName := toPascalCase(key)
		fmt.Fprintf(&buf, "\tmux.HandleFunc(\"%s\", h.%s)\n", route, methodName)
	}
	buf.WriteString("}\n")

	return []renderer.OutputFile{
		{Path: "handlers/" + fileName, Content: buf.Bytes()},
	}, nil
}

func writeInputStruct(buf *bytes.Buffer, fields []renderer.DataSourceField) {
	buf.WriteString("\tvar input struct {\n")
	for _, f := range fields {
		if f.Primary || f.Readonly || f.Hidden {
			continue
		}
		goType := fieldGoType(f.Type)
		fieldName := toPascalCase(f.Name)
		buf.WriteString(fmt.Sprintf("\t\t%s %s `json:\"%s\"`\n", fieldName, goType, f.Name))
	}
	buf.WriteString("\t}\n")
}

func fieldGoType(fieldType string) string {
	switch fieldType {
	case "string", "text", "enum":
		return "string"
	case "integer":
		return "int64"
	case "float":
		return "float64"
	case "boolean":
		return "bool"
	case "date", "datetime":
		return "time.Time"
	case "json":
		return "json.RawMessage"
	default:
		return "interface{}"
	}
}

func needsTimeImport(fields []renderer.DataSourceField) bool {
	for _, f := range fields {
		if f.Primary || f.Readonly || f.Hidden {
			continue
		}
		if f.Type == "date" || f.Type == "datetime" {
			return true
		}
	}
	return false
}

func endpointRoute(endpoints map[string]string, key string) string {
	if ep, ok := endpoints[key]; ok {
		return ep
	}
	return strings.ToUpper(key) + " /api/unknown"
}
