package gotempl

import (
	"strings"
	"testing"

	"github.com/chrispian/sigil/internal/renderer"
)

func testDataSource() *renderer.DataSourceManifest {
	return &renderer.DataSourceManifest{
		Alias:       "Sprint",
		Description: "Sprint management",
		Capabilities: []string{
			"search", "filter", "sort", "paginate",
			"create", "update", "delete",
		},
		Fields: []renderer.DataSourceField{
			{Name: "id", Type: "integer", Primary: true, Hidden: true},
			{Name: "code", Type: "string", Required: true, Searchable: true},
			{Name: "title", Type: "string", Required: true, Searchable: true},
			{Name: "status", Type: "enum", Values: []string{"planning", "active", "completed"}},
			{Name: "start_date", Type: "date", Sortable: true},
			{Name: "created_at", Type: "datetime", Readonly: true},
		},
		Endpoints: map[string]string{
			"list":   "GET /api/sprints",
			"create": "POST /api/sprints",
			"read":   "GET /api/sprints/{id}",
			"update": "PUT /api/sprints/{id}",
			"delete": "DELETE /api/sprints/{id}",
		},
	}
}

func TestRenderDataSourceStubs(t *testing.T) {
	ds := testDataSource()
	files, err := renderDataSourceStubs(ds)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if len(files) != 1 {
		t.Fatalf("expected 1 file, got %d", len(files))
	}

	file := files[0]
	if file.Path != "handlers/sprint_handler.go" {
		t.Errorf("expected path 'handlers/sprint_handler.go', got %q", file.Path)
	}
}

func TestStubContent(t *testing.T) {
	ds := testDataSource()
	files, _ := renderDataSourceStubs(ds)
	content := string(files[0].Content)

	// Check header
	if !strings.Contains(content, "Generated by Sigil") {
		t.Error("expected generated header")
	}
	if !strings.Contains(content, "package handlers") {
		t.Error("expected package handlers")
	}

	// Check imports
	if !strings.Contains(content, `"encoding/json"`) {
		t.Error("expected json import")
	}
	if !strings.Contains(content, `"net/http"`) {
		t.Error("expected net/http import")
	}

	// Check handler struct
	if !strings.Contains(content, "type SprintHandler struct") {
		t.Error("expected SprintHandler struct")
	}
	if !strings.Contains(content, "func NewSprintHandler()") {
		t.Error("expected NewSprintHandler constructor")
	}
}

func TestStubCRUDMethods(t *testing.T) {
	ds := testDataSource()
	files, _ := renderDataSourceStubs(ds)
	content := string(files[0].Content)

	// Should have all CRUD methods
	methods := []string{
		"func (h *SprintHandler) List(",
		"func (h *SprintHandler) Create(",
		"func (h *SprintHandler) Read(",
		"func (h *SprintHandler) Update(",
		"func (h *SprintHandler) Delete(",
	}
	for _, m := range methods {
		if !strings.Contains(content, m) {
			t.Errorf("expected method %q", m)
		}
	}

	// Check route registration
	if !strings.Contains(content, "func (h *SprintHandler) RegisterRoutes(mux *http.ServeMux)") {
		t.Error("expected RegisterRoutes method")
	}
	if !strings.Contains(content, `"GET /api/sprints"`) {
		t.Error("expected list route")
	}
	if !strings.Contains(content, `"DELETE /api/sprints/{id}"`) {
		t.Error("expected delete route")
	}
}

func TestStubInputFields(t *testing.T) {
	ds := testDataSource()
	files, _ := renderDataSourceStubs(ds)
	content := string(files[0].Content)

	// Should include non-primary, non-readonly, non-hidden fields
	if !strings.Contains(content, `Code string`) {
		t.Error("expected Code field in input struct")
	}
	if !strings.Contains(content, `Title string`) {
		t.Error("expected Title field in input struct")
	}
	if !strings.Contains(content, `Status string`) {
		t.Error("expected Status field in input struct")
	}
	if !strings.Contains(content, `json:"start_date"`) {
		t.Error("expected start_date json tag")
	}

	// Should NOT include primary/readonly/hidden fields
	if strings.Contains(content, `Id int64`) {
		t.Error("unexpected Id field (primary, hidden)")
	}
	if strings.Contains(content, `CreatedAt`) {
		t.Error("unexpected CreatedAt field (readonly)")
	}
}

func TestStubTimeImport(t *testing.T) {
	ds := testDataSource()
	files, _ := renderDataSourceStubs(ds)
	content := string(files[0].Content)

	// Has date fields, should import time
	if !strings.Contains(content, `"time"`) {
		t.Error("expected time import for date fields")
	}
	if !strings.Contains(content, "time.Time") {
		t.Error("expected time.Time type for date fields")
	}
}

func TestStubLimitedCapabilities(t *testing.T) {
	ds := &renderer.DataSourceManifest{
		Alias:        "SprintStatus",
		Capabilities: []string{"list"},
		Fields: []renderer.DataSourceField{
			{Name: "value", Type: "string"},
			{Name: "label", Type: "string"},
		},
		Endpoints: map[string]string{
			"list": "GET /api/sprint-statuses",
		},
	}

	files, err := renderDataSourceStubs(ds)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := string(files[0].Content)

	// Should have List
	if !strings.Contains(content, "func (h *SprintStatusHandler) List(") {
		t.Error("expected List method")
	}

	// Should NOT have Create, Update, Delete
	if strings.Contains(content, "func (h *SprintStatusHandler) Create(") {
		t.Error("unexpected Create method")
	}
	if strings.Contains(content, "func (h *SprintStatusHandler) Update(") {
		t.Error("unexpected Update method")
	}
	if strings.Contains(content, "func (h *SprintStatusHandler) Delete(") {
		t.Error("unexpected Delete method")
	}
}

func TestStubNoTimeImport(t *testing.T) {
	ds := &renderer.DataSourceManifest{
		Alias:        "Tag",
		Capabilities: []string{"list", "create"},
		Fields: []renderer.DataSourceField{
			{Name: "name", Type: "string"},
		},
		Endpoints: map[string]string{
			"list":   "GET /api/tags",
			"create": "POST /api/tags",
		},
	}

	files, _ := renderDataSourceStubs(ds)
	content := string(files[0].Content)

	// No date fields, should not import time
	if strings.Contains(content, `"time"`) {
		t.Error("unexpected time import without date fields")
	}
}

func TestFieldGoType(t *testing.T) {
	tests := []struct {
		fieldType string
		expected  string
	}{
		{"string", "string"},
		{"text", "string"},
		{"enum", "string"},
		{"integer", "int64"},
		{"float", "float64"},
		{"boolean", "bool"},
		{"date", "time.Time"},
		{"datetime", "time.Time"},
		{"json", "json.RawMessage"},
		{"unknown", "interface{}"},
	}

	for _, tt := range tests {
		got := fieldGoType(tt.fieldType)
		if got != tt.expected {
			t.Errorf("fieldGoType(%q) = %q, want %q", tt.fieldType, got, tt.expected)
		}
	}
}
