package gotempl

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/hollis-labs/sigil/internal/renderer"
)

// renderThemeCSS generates theme.css and optional tailwind.sigil.cjs from theme tokens.
func renderThemeCSS(theme *renderer.ThemeConfig) ([]renderer.OutputFile, error) {
	var files []renderer.OutputFile

	css, err := generateCSS(theme)
	if err != nil {
		return nil, err
	}
	files = append(files, renderer.OutputFile{
		Path:    "theme.css",
		Content: css,
	})

	tailwind, err := generateTailwindPreset(theme)
	if err != nil {
		return nil, err
	}
	files = append(files, renderer.OutputFile{
		Path:    "tailwind.sigil.cjs",
		Content: tailwind,
	})

	return files, nil
}

func generateCSS(theme *renderer.ThemeConfig) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("/* theme.css — generated by Sigil, do not edit */\n")
	buf.WriteString(":root {\n")

	// Token categories in stable order, with optional prefix to avoid key collisions
	type catEntry struct {
		name   string
		prefix string
	}
	categories := []catEntry{
		{"colors", ""},
		{"typography", ""},
		{"spacing", ""},
		{"radius", ""},
		{"shadows", "shadow-"},
	}
	for _, cat := range categories {
		tokens, ok := theme.Tokens[cat.name]
		if !ok || len(tokens) == 0 {
			continue
		}

		label := strings.ToUpper(cat.name[:1]) + cat.name[1:]
		buf.WriteString(fmt.Sprintf("\n  /* %s */\n", label))

		keys := sortedKeys(tokens)
		for _, key := range keys {
			val := fmt.Sprintf("%v", tokens[key])
			cssVar := fmt.Sprintf("--sigil-%s%s", cat.prefix, key)
			buf.WriteString(fmt.Sprintf("  %s: %s;\n", cssVar, val))
		}
	}

	buf.WriteString("}\n")

	// Component utility classes from variants
	if len(theme.Variants) > 0 {
		buf.WriteString("\n/* Component classes */\n")
		generateComponentClasses(&buf, theme)
	}

	return buf.Bytes(), nil
}

func generateComponentClasses(buf *bytes.Buffer, theme *renderer.ThemeConfig) {
	compOrder := []string{"button", "badge", "input"}
	for _, comp := range compOrder {
		variants, ok := theme.Variants[comp]
		if !ok {
			continue
		}

		prefix := componentPrefix(comp)

		// Base class
		buf.WriteString(fmt.Sprintf(".%s {\n", prefix))
		buf.WriteString("  font-family: var(--sigil-font-sans);\n")
		buf.WriteString("  font-size: 0.875rem;\n")
		switch comp {
		case "button":
			buf.WriteString("  padding: 0.5rem 1rem;\n")
			buf.WriteString("  cursor: pointer;\n")
			buf.WriteString("  transition: background-color 150ms;\n")
			buf.WriteString("  border: none;\n")
			buf.WriteString("  border-radius: var(--sigil-radius-md);\n")
		case "badge":
			buf.WriteString("  padding: 0.125rem 0.5rem;\n")
			buf.WriteString("  border-radius: var(--sigil-radius-full, 9999px);\n")
			buf.WriteString("  font-size: 0.75rem;\n")
			buf.WriteString("  font-weight: 500;\n")
		case "input":
			buf.WriteString("  padding: 0.5rem 0.75rem;\n")
			buf.WriteString("  border-radius: var(--sigil-radius-md);\n")
			buf.WriteString("  border: 1px solid rgb(var(--sigil-border));\n")
			buf.WriteString("  background: rgb(var(--sigil-surface));\n")
			buf.WriteString("  color: rgb(var(--sigil-text));\n")
		}
		buf.WriteString("}\n")

		// Variant classes
		variantKeys := sortedStringKeys(variants)
		for _, varName := range variantKeys {
			varDef := variants[varName]
			varMap, ok := varDef.(map[string]interface{})
			if !ok {
				continue
			}

			className := fmt.Sprintf("%s-%s", prefix, varName)
			buf.WriteString(fmt.Sprintf(".%s {\n", className))

			if bg, ok := varMap["bg"]; ok {
				bgStr := fmt.Sprintf("%v", bg)
				if bgStr == "transparent" {
					buf.WriteString("  background: transparent;\n")
				} else {
					buf.WriteString(fmt.Sprintf("  background: rgb(var(--sigil-%s));\n", bgStr))
				}
			}
			if text, ok := varMap["text"]; ok {
				buf.WriteString(fmt.Sprintf("  color: rgb(var(--sigil-%v));\n", text))
			}
			if border, ok := varMap["border"]; ok {
				buf.WriteString(fmt.Sprintf("  border: 1px solid rgb(var(--sigil-%v));\n", border))
			}
			if radius, ok := varMap["radius"]; ok {
				buf.WriteString(fmt.Sprintf("  border-radius: var(--sigil-radius-%v);\n", radius))
			}

			buf.WriteString("}\n")

			// Hover state
			if hover, ok := varMap["hover"]; ok {
				buf.WriteString(fmt.Sprintf(".%s:hover {\n", className))
				hoverStr := fmt.Sprintf("%v", hover)
				if hoverStr == "transparent" {
					buf.WriteString("  background: transparent;\n")
				} else {
					buf.WriteString(fmt.Sprintf("  background: rgb(var(--sigil-%s));\n", hoverStr))
				}
				buf.WriteString("}\n")
			}
		}
	}

	// Generic utility classes
	buf.WriteString("\n/* Utility classes */\n")
	buf.WriteString(".sigil-label {\n  font-size: 0.875rem;\n  font-weight: 500;\n  color: rgb(var(--sigil-text));\n}\n")
	buf.WriteString(".sigil-separator {\n  border: none;\n  border-top: 1px solid rgb(var(--sigil-border));\n  margin: 0.5rem 0;\n}\n")
	buf.WriteString(".sigil-checkbox {\n  accent-color: rgb(var(--sigil-accent));\n}\n")
	buf.WriteString(".sigil-progress {\n  width: 100%;\n  accent-color: rgb(var(--sigil-accent));\n}\n")
	buf.WriteString(".sigil-form { max-width: 32rem; }\n")
	buf.WriteString(".sigil-data-table table { border-collapse: collapse; }\n")
	buf.WriteString(".sigil-data-table th, .sigil-data-table td {\n  padding: 0.5rem 1rem;\n  text-align: left;\n  border-bottom: 1px solid rgb(var(--sigil-border));\n}\n")
	buf.WriteString(".sigil-data-table th {\n  font-weight: 600;\n  color: rgb(var(--sigil-text-muted));\n  font-size: 0.75rem;\n  text-transform: uppercase;\n}\n")
}

func componentPrefix(comp string) string {
	switch comp {
	case "button":
		return "sigil-btn"
	case "badge":
		return "sigil-badge"
	case "input":
		return "sigil-input"
	default:
		return "sigil-" + comp
	}
}

func generateTailwindPreset(theme *renderer.ThemeConfig) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("// tailwind.sigil.cjs — generated by Sigil, do not edit\n")
	buf.WriteString("module.exports = {\n")
	buf.WriteString("  theme: {\n")
	buf.WriteString("    extend: {\n")

	// Colors
	if colors, ok := theme.Tokens["colors"]; ok && len(colors) > 0 {
		buf.WriteString("      colors: {\n")
		buf.WriteString("        sigil: {\n")
		keys := sortedKeys(colors)
		for _, key := range keys {
			jsKey := strings.ReplaceAll(key, "-", "")
			if strings.Contains(key, "-") {
				jsKey = fmt.Sprintf("'%s'", key)
			}
			buf.WriteString(fmt.Sprintf("          %s: 'rgb(var(--sigil-%s) / <alpha-value>)',\n", jsKey, key))
		}
		buf.WriteString("        },\n")
		buf.WriteString("      },\n")
	}

	// Fonts
	if typo, ok := theme.Tokens["typography"]; ok {
		if _, ok := typo["font-sans"]; ok {
			buf.WriteString("      fontFamily: {\n")
			buf.WriteString("        sans: ['var(--sigil-font-sans)'],\n")
			if _, ok := typo["font-mono"]; ok {
				buf.WriteString("        mono: ['var(--sigil-font-mono)'],\n")
			}
			buf.WriteString("      },\n")
		}
	}

	// Border radius
	if radius, ok := theme.Tokens["radius"]; ok && len(radius) > 0 {
		buf.WriteString("      borderRadius: {\n")
		keys := sortedKeys(radius)
		for _, key := range keys {
			jsKey := key
			if key == "none" || key == "full" {
				continue // Tailwind has these built-in
			}
			buf.WriteString(fmt.Sprintf("        'sigil-%s': 'var(--sigil-%s)',\n", jsKey, key))
		}
		buf.WriteString("      },\n")
	}

	buf.WriteString("    },\n")
	buf.WriteString("  },\n")
	buf.WriteString("};\n")

	return buf.Bytes(), nil
}

func sortedKeys(m map[string]interface{}) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func sortedStringKeys(m map[string]interface{}) []string {
	return sortedKeys(m)
}
