package gotempl

import (
	"strings"
	"testing"

	"github.com/chrispian/sigil/internal/renderer"
)

func testTheme() *renderer.ThemeConfig {
	return &renderer.ThemeConfig{
		Name:        "default",
		Description: "Default dark theme",
		Tokens: map[string]map[string]interface{}{
			"colors": {
				"background":   "9 9 11",
				"surface":      "24 24 27",
				"border":       "63 63 70",
				"text":         "244 244 245",
				"text-muted":   "161 161 170",
				"accent":       "16 185 129",
				"accent-hover": "5 150 105",
				"danger":       "239 68 68",
			},
			"typography": {
				"font-sans": "ui-sans-serif, system-ui, sans-serif",
				"font-mono": "ui-monospace, SFMono-Regular, Menlo, monospace",
			},
			"radius": {
				"sm":   "0.125rem",
				"md":   "0.375rem",
				"lg":   "0.5rem",
				"full": "9999px",
			},
			"shadows": {
				"sm": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
			},
		},
		Variants: map[string]map[string]interface{}{
			"button": {
				"primary": map[string]interface{}{
					"bg":     "accent",
					"text":   "background",
					"hover":  "accent-hover",
					"radius": "md",
				},
				"secondary": map[string]interface{}{
					"bg":     "surface",
					"text":   "text",
					"hover":  "border",
					"radius": "md",
				},
				"destructive": map[string]interface{}{
					"bg":    "danger",
					"text":  "background",
					"hover": "danger",
				},
			},
			"badge": {
				"default": map[string]interface{}{
					"bg":   "surface",
					"text": "text",
				},
			},
		},
	}
}

func TestRenderThemeCSS(t *testing.T) {
	theme := testTheme()
	files, err := renderThemeCSS(theme)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if len(files) != 2 {
		t.Fatalf("expected 2 files (theme.css + tailwind.sigil.cjs), got %d", len(files))
	}

	// Verify file paths
	paths := map[string]bool{}
	for _, f := range files {
		paths[f.Path] = true
	}
	if !paths["theme.css"] {
		t.Error("expected theme.css")
	}
	if !paths["tailwind.sigil.cjs"] {
		t.Error("expected tailwind.sigil.cjs")
	}
}

func TestGenerateCSSTokens(t *testing.T) {
	theme := testTheme()
	css, err := generateCSS(theme)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := string(css)

	// Check header
	if !strings.Contains(content, "generated by Sigil") {
		t.Error("expected generated header")
	}

	// Check :root declaration
	if !strings.Contains(content, ":root {") {
		t.Error("expected :root block")
	}

	// Check color tokens
	expectedTokens := []string{
		"--sigil-background: 9 9 11",
		"--sigil-text: 244 244 245",
		"--sigil-accent: 16 185 129",
		"--sigil-border: 63 63 70",
	}
	for _, token := range expectedTokens {
		if !strings.Contains(content, token) {
			t.Errorf("expected CSS token %q", token)
		}
	}

	// Check typography tokens
	if !strings.Contains(content, "--sigil-font-sans:") {
		t.Error("expected font-sans token")
	}

	// Check radius tokens
	if !strings.Contains(content, "--sigil-md: 0.375rem") {
		t.Error("expected radius-md token")
	}

	// Check shadows
	if !strings.Contains(content, "--sigil-sm:") {
		t.Error("expected shadow-sm token")
	}
}

func TestGenerateCSSComponentClasses(t *testing.T) {
	theme := testTheme()
	css, err := generateCSS(theme)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := string(css)

	// Check button base class
	if !strings.Contains(content, ".sigil-btn {") {
		t.Error("expected .sigil-btn base class")
	}

	// Check button variant classes
	if !strings.Contains(content, ".sigil-btn-primary {") {
		t.Error("expected .sigil-btn-primary class")
	}
	if !strings.Contains(content, "rgb(var(--sigil-accent))") {
		t.Error("expected accent color reference in primary button")
	}

	// Check hover states
	if !strings.Contains(content, ".sigil-btn-primary:hover {") {
		t.Error("expected .sigil-btn-primary:hover")
	}
	if !strings.Contains(content, "rgb(var(--sigil-accent-hover))") {
		t.Error("expected accent-hover reference in hover state")
	}

	// Check secondary variant
	if !strings.Contains(content, ".sigil-btn-secondary {") {
		t.Error("expected .sigil-btn-secondary class")
	}

	// Check badge class
	if !strings.Contains(content, ".sigil-badge {") {
		t.Error("expected .sigil-badge base class")
	}

	// Check utility classes
	if !strings.Contains(content, ".sigil-label {") {
		t.Error("expected .sigil-label utility class")
	}
	if !strings.Contains(content, ".sigil-separator {") {
		t.Error("expected .sigil-separator utility class")
	}
	if !strings.Contains(content, ".sigil-data-table") {
		t.Error("expected .sigil-data-table utility class")
	}
}

func TestGenerateTailwindPreset(t *testing.T) {
	theme := testTheme()
	preset, err := generateTailwindPreset(theme)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := string(preset)

	// Check header
	if !strings.Contains(content, "generated by Sigil") {
		t.Error("expected generated header")
	}

	// Check module.exports structure
	if !strings.Contains(content, "module.exports = {") {
		t.Error("expected module.exports")
	}

	// Check colors
	if !strings.Contains(content, "rgb(var(--sigil-background) / <alpha-value>)") {
		t.Error("expected Tailwind color with alpha support")
	}

	// Check fonts
	if !strings.Contains(content, "var(--sigil-font-sans)") {
		t.Error("expected font-sans reference")
	}
	if !strings.Contains(content, "var(--sigil-font-mono)") {
		t.Error("expected font-mono reference")
	}

	// Check border radius
	if !strings.Contains(content, "var(--sigil-md)") {
		t.Error("expected radius-md reference")
	}
}

func TestGenerateCSSNoVariants(t *testing.T) {
	theme := &renderer.ThemeConfig{
		Name: "minimal",
		Tokens: map[string]map[string]interface{}{
			"colors": {
				"background": "0 0 0",
				"text":       "255 255 255",
			},
		},
	}

	css, err := generateCSS(theme)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := string(css)
	if !strings.Contains(content, "--sigil-background: 0 0 0") {
		t.Error("expected background token")
	}
	// Should not have component classes section
	if strings.Contains(content, ".sigil-btn") {
		t.Error("unexpected component classes without variants")
	}
}
