// se-reports.tsx
// Generated by Sigil — do not edit manually

"use client";

import { useState } from "react";
import { toast } from "sonner";
import { Loader2, Plus, Search } from "lucide-react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Toaster } from "@/components/ui/sonner";
import { DataTable } from "@/components/data-table";
import { useReportConfig } from "@/hooks/use-reportconfig";
import { deleteItem, postItem } from "@/lib/api";
import { ReportConfig } from "@/types/reportconfig";

export default function SeReports() {
  const [modalOpen, setModalOpen] = useState(false);
  const [formName, setFormName] = useState("");
  const [formAudience, setFormAudience] = useState("");
  const [formLensId, setFormLensId] = useState("");
    const handleCreateReportConfig = async () => {
    try {
      await postItem("reportconfigs", {
        name: formName,
        audience: formAudience,
        lens_id: formLensId,
      });
      toast.success("ReportConfig created");
      setModalOpen(false);
      setFormName("");
      setFormAudience("");
      setFormLensId("");
      refetchReportConfig();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to create reportconfig");
    }
  };


  const [searchReportConfig, setSearchReportConfig] = useState("");
  const [sheetItem, setSheetItem] = useState<ReportConfig | null>(null);
    const handleDelete = async () => {
    if (!sheetItem) return;
    try {
      await deleteItem("reportconfigs", (sheetItem as { id: string }).id);
      toast.success("ReportConfig deleted");
      setSheetItem(null);
      refetchReportConfig();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to delete reportconfig");
    }
  };



  const { data: reportConfig, isLoading: reportConfigLoading, refetch: refetchReportConfig } = useReportConfig();

  if (reportConfigLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-5 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <div className="flex flex-col gap-1">
          <h1 className="text-2xl font-semibold tracking-tight text-foreground">Reports</h1>
          <p className="text-sm text-muted-foreground">Curated views combining a lens with filtered repos</p>
        </div>
        <Dialog open={modalOpen} onOpenChange={setModalOpen}>
          <DialogTrigger render={<Button variant="default" />}>
            <Plus className="mr-2 h-4 w-4" />
            Create Report
          </DialogTrigger>
          <DialogContent className="sm:max-w-lg">
            <DialogHeader>
              <DialogTitle>Create Report Config</DialogTitle>
            </DialogHeader>
            <div className="flex flex-col gap-4 py-4">
              <div className="flex flex-col gap-1.5">
                <Label htmlFor="name">Report Name</Label>
                <Input id="name" type="text" placeholder="e.g., Q1 Agent Framework Review" value={formName} onChange={(e) => setFormName(e.target.value)} />
              </div>
              <div className="flex flex-col gap-1.5">
                <Label htmlFor="audience">Audience</Label>
                <Select value={formAudience} onValueChange={(v) => v && setFormAudience(v)}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select..." />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="engineer">Engineer</SelectItem>
                    <SelectItem value="product">Product</SelectItem>
                    <SelectItem value="leadership">Leadership</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="flex flex-col gap-1.5">
                <Label htmlFor="lens_id">Lens</Label>
                <Select value={formLensId} onValueChange={(v) => v && setFormLensId(v)}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select..." />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="engineering">Engineering</SelectItem>
                    <SelectItem value="product">Product</SelectItem>
                    <SelectItem value="leadership">Leadership</SelectItem>
                    <SelectItem value="security">Security</SelectItem>
                    <SelectItem value="overall">Overall</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setModalOpen(false)}>Cancel</Button>
              <Button onClick={handleCreateReportConfig}>Save</Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
      <div className="relative">
        <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
        <Input type="search" placeholder="Search reports..." className="w-full pl-9 [&::-webkit-search-cancel-button]:hidden [&::-webkit-search-decoration]:hidden" value={searchReportConfig} onChange={(e) => setSearchReportConfig(e.target.value)} />
      </div>
      <Card>
        <CardHeader>
          <CardTitle>Report Configs</CardTitle>
          <CardDescription>Each report combines a lens with filtered repos for a curated view</CardDescription>
        </CardHeader>
        <CardContent>
          <DataTable
            data={(reportConfig ?? [])
              .filter((item) => {
                if (!searchReportConfig) return true;
                const q = searchReportConfig.toLowerCase();
                return Object.values(item).some((v) => String(v).toLowerCase().includes(q));
              })}
            columns={[
              { accessorKey: "name", header: "Name" },
              {
                accessorKey: "lens_name",
                header: "Lens",
                cell: ({ row }: { row: { getValue: (k: string) => unknown } }) => {
                  const v = String(row.getValue("lens_name") ?? "");
                  const variants: Record<string, string> = { "Leadership": "warning", "Engineering": "info", "Product": "default" };
                  const variant = variants[v] ?? variants[v.toLowerCase()] ?? "default";
                  return <Badge variant={variant === "danger" ? "destructive" : variant === "success" || variant === "warning" || variant === "info" ? "outline" : "secondary"} className={
                    variant === "success" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-400" :
                    variant === "warning" ? "border-amber-500/30 bg-amber-500/10 text-amber-400" :
                    variant === "info" ? "border-blue-500/30 bg-blue-500/10 text-blue-400" :
                    variant === "danger" ? "" : ""
                  }>{v}</Badge>;
                },
              },
              { accessorKey: "repo_count", header: "Repos" },
              {
                accessorKey: "audience",
                header: "Audience",
                cell: ({ row }: { row: { getValue: (k: string) => unknown } }) => {
                  const v = String(row.getValue("audience") ?? "");
                  const variants: Record<string, string> = { "engineer": "info", "product": "success", "leadership": "warning" };
                  const variant = variants[v] ?? variants[v.toLowerCase()] ?? "default";
                  return <Badge variant={variant === "danger" ? "destructive" : variant === "success" || variant === "warning" || variant === "info" ? "outline" : "secondary"} className={
                    variant === "success" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-400" :
                    variant === "warning" ? "border-amber-500/30 bg-amber-500/10 text-amber-400" :
                    variant === "info" ? "border-blue-500/30 bg-blue-500/10 text-blue-400" :
                    variant === "danger" ? "" : ""
                  }>{v}</Badge>;
                },
              },
            ]}
            emptyMessage="No matching results found."
            onRowClick={(row) => setSheetItem(row as ReportConfig)}
          />
        </CardContent>
      </Card>
    </div>
    <Sheet open={!!sheetItem} onOpenChange={(open) => { if (!open) { setSheetItem(null); } }}>
      <SheetContent side="right">
        <SheetHeader>
          <SheetTitle>{(sheetItem as unknown as Record<string, unknown>)?.name as string}</SheetTitle>
        </SheetHeader>
        {sheetItem && (
          <div className="flex flex-col gap-4 px-4 pt-4">
            <div className="flex flex-row gap-2">
              <AlertDialog>
                <AlertDialogTrigger render={<Button variant="destructive" size="sm" />}>Delete</AlertDialogTrigger>
                <AlertDialogContent>
                  <AlertDialogHeader>
                    <AlertDialogTitle>Delete reportconfig?</AlertDialogTitle>
                    <AlertDialogDescription>This action cannot be undone.</AlertDialogDescription>
                  </AlertDialogHeader>
                  <AlertDialogFooter>
                    <AlertDialogCancel>Cancel</AlertDialogCancel>
                    <AlertDialogAction onClick={handleDelete}>Delete</AlertDialogAction>
                  </AlertDialogFooter>
                </AlertDialogContent>
              </AlertDialog>
            </div>
            <div>
              <div className="text-xs text-muted-foreground">Name</div>
              <div className="text-sm">{String((sheetItem as unknown as Record<string, unknown>)?.name ?? "")}</div>
            </div>
            <div>
              <div className="text-xs text-muted-foreground">Audience</div>
              <div className="text-sm">{String((sheetItem as unknown as Record<string, unknown>)?.audience ?? "")}</div>
            </div>
          </div>
        )}
      </SheetContent>
    </Sheet>
    <Toaster />
    </>
  );
}
