// forge-monitoring-detail.tsx
// Generated by Sigil — do not edit manually

"use client";

import { ChevronsUpDown } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from "@/components/ui/breadcrumb";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { Progress } from "@/components/ui/progress";
import { Separator } from "@/components/ui/separator";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";

export default function ForgeMonitoringDetail() {
  return (
    <div className="min-h-screen bg-background text-foreground font-sans">
    <div className="flex flex-col gap-6 p-6">
      <Breadcrumb>
        <BreadcrumbList>
          <BreadcrumbItem>
            <BreadcrumbLink href="/forge-monitoring">Monitoring</BreadcrumbLink>
          </BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>
            <BreadcrumbPage>API Latency</BreadcrumbPage>
          </BreadcrumbItem>
        </BreadcrumbList>
      </Breadcrumb>
      <div className="flex flex-row gap-4 justify-between items-center">
        <h2 className="scroll-m-20 text-3xl font-semibold tracking-tight text-foreground">API Latency</h2>
        <ToggleGroup variant="outline">
          <ToggleGroupItem value="1h">1H</ToggleGroupItem>
          <ToggleGroupItem value="6h">6H</ToggleGroupItem>
          <ToggleGroupItem value="24h">24H</ToggleGroupItem>
          <ToggleGroupItem value="7d">7D</ToggleGroupItem>
          <ToggleGroupItem value="30d">30D</ToggleGroupItem>
        </ToggleGroup>
      </div>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Card>
          <CardHeader>
            <CardTitle>P50</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-base">45ms</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>P95</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-base">120ms</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>P99</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-base">340ms</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Error Rate</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-base">0.12%</p>
          </CardContent>
        </Card>
      </div>
      <Card>
        <CardHeader>
          <CardTitle>Latency Over Time</CardTitle>
          <CardDescription>Chart placeholder — would render a line chart in production.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex flex-col gap-2">
            <Progress value={45} />
            <Progress value={62} />
            <Progress value={38} />
            <Progress value={55} />
            <Progress value={71} />
          </div>
        </CardContent>
      </Card>
      <Collapsible>
        <div className="flex items-center justify-between">
          <h4 className="text-sm font-semibold">Recent Alerts</h4>
          <CollapsibleTrigger>
            <ChevronsUpDown className="h-4 w-4" />
          </CollapsibleTrigger>
        </div>
        <CollapsibleContent>
          <div className="flex flex-col gap-2">
            <Alert variant="default">
              <AlertDescription>P95 latency exceeded 200ms threshold at 14:32 UTC</AlertDescription>
            </Alert>
            <Alert variant="default">
              <AlertDescription>P95 latency exceeded 200ms threshold at 09:15 UTC</AlertDescription>
            </Alert>
            <Alert variant="default">
              <AlertDescription>Error rate returned to normal at 08:45 UTC</AlertDescription>
            </Alert>
          </div>
        </CollapsibleContent>
      </Collapsible>
      <Collapsible>
        <div className="flex items-center justify-between">
          <h4 className="text-sm font-semibold">Endpoint Breakdown</h4>
          <CollapsibleTrigger>
            <ChevronsUpDown className="h-4 w-4" />
          </CollapsibleTrigger>
        </div>
        <CollapsibleContent>
          <div className="flex flex-col gap-3">
            <div className="flex flex-row gap-4 justify-between items-center">
              <p className="text-base">GET /api/deployments</p>
              <div className="flex flex-row gap-2 items-center">
                <Badge variant="outline" className="border-emerald-500/30 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">32ms</Badge>
                <Progress value={32} />
              </div>
            </div>
            <Separator />
            <div className="flex flex-row gap-4 justify-between items-center">
              <p className="text-base">POST /api/deployments</p>
              <div className="flex flex-row gap-2 items-center">
                <Badge variant="outline" className="border-amber-500/30 bg-amber-500/10 text-amber-600 dark:text-amber-400">156ms</Badge>
                <Progress value={65} />
              </div>
            </div>
            <Separator />
            <div className="flex flex-row gap-4 justify-between items-center">
              <p className="text-base">GET /api/assets</p>
              <div className="flex flex-row gap-2 items-center">
                <Badge variant="outline" className="border-emerald-500/30 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">45ms</Badge>
                <Progress value={38} />
              </div>
            </div>
          </div>
        </CollapsibleContent>
      </Collapsible>
    </div>
    </div>
  );
}
