// se-findings.tsx
// Generated by Sigil — do not edit manually

"use client";

import { useState } from "react";
import { toast } from "sonner";
import { Loader2, Plus, Search } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Toaster } from "@/components/ui/sonner";
import { Textarea } from "@/components/ui/textarea";
import { DataTable } from "@/components/data-table";
import { useFinding } from "@/hooks/use-finding";
import { postItem, updateItem } from "@/lib/api";
import { Finding } from "@/types/finding";

export default function SeFindings() {
  const [modalOpen, setModalOpen] = useState(false);
  const [formTitle, setFormTitle] = useState("");
  const [formCategory, setFormCategory] = useState("");
  const [formSeverity, setFormSeverity] = useState("");
  const [formDescription, setFormDescription] = useState("");
    const handleCreateFinding = async () => {
    try {
      await postItem("findings", {
        title: formTitle,
        category: formCategory,
        severity: formSeverity,
        description: formDescription,
      });
      toast.success("Finding created");
      setModalOpen(false);
      setFormTitle("");
      setFormCategory("");
      setFormSeverity("");
      setFormDescription("");
      refetchFinding();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to create finding");
    }
  };


  const [searchFinding, setSearchFinding] = useState("");
  const [filterFindingCategory, setFilterFindingCategory] = useState("all");
  const [filterFindingSeverity, setFilterFindingSeverity] = useState("all");
  const [filterFindingStatus, setFilterFindingStatus] = useState("all");
  const [sheetItem, setSheetItem] = useState<Finding | null>(null);
  const [editing, setEditing] = useState(false);
  const [editTitle, setEditTitle] = useState("");
  const [editCategory, setEditCategory] = useState("");
  const [editSeverity, setEditSeverity] = useState("");
  const [editStatus, setEditStatus] = useState("");
  const [editDescription, setEditDescription] = useState("");
    const startEditing = () => {
    if (!sheetItem) return;
    setEditTitle(String((sheetItem as unknown as Record<string, unknown>).title ?? ""));
    setEditCategory(String((sheetItem as unknown as Record<string, unknown>).category ?? ""));
    setEditSeverity(String((sheetItem as unknown as Record<string, unknown>).severity ?? ""));
    setEditStatus(String((sheetItem as unknown as Record<string, unknown>).status ?? ""));
    setEditDescription(String((sheetItem as unknown as Record<string, unknown>).description ?? ""));
    setEditing(true);
  };


    const handleUpdate = async () => {
    if (!sheetItem) return;
    try {
      await updateItem("findings", (sheetItem as { id: string }).id, {
        title: editTitle,
        category: editCategory,
        severity: editSeverity,
        status: editStatus,
        description: editDescription,
      });
      toast.success("Finding updated");
      setEditing(false);
      setSheetItem(null);
      refetchFinding();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to update finding");
    }
  };



  const { data: finding, isLoading: findingLoading, refetch: refetchFinding } = useFinding();

  if (findingLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-5 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <div className="flex flex-col gap-1">
          <h1 className="text-2xl font-semibold tracking-tight text-foreground">Findings</h1>
          <p className="text-sm text-muted-foreground">Research observations — gaps, strengths, opportunities, and risks</p>
        </div>
        <Dialog open={modalOpen} onOpenChange={setModalOpen}>
          <DialogTrigger render={<Button variant="default" />}>
            <Plus className="mr-2 h-4 w-4" />
            Add Finding
          </DialogTrigger>
          <DialogContent className="sm:max-w-lg">
            <DialogHeader>
              <DialogTitle>Add Finding</DialogTitle>
            </DialogHeader>
            <div className="flex flex-col gap-4 py-4">
              <div className="flex flex-col gap-1.5">
                <Label htmlFor="title">Title</Label>
                <Input id="title" type="text" placeholder="e.g., Missing retry logic in error handling" value={formTitle} onChange={(e) => setFormTitle(e.target.value)} />
              </div>
              <div className="flex flex-col gap-1.5">
                <Label htmlFor="category">Category</Label>
                <Select value={formCategory} onValueChange={(v) => v && setFormCategory(v)}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select..." />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="gap">Gap</SelectItem>
                    <SelectItem value="strength">Strength</SelectItem>
                    <SelectItem value="opportunity">Opportunity</SelectItem>
                    <SelectItem value="risk">Risk</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="flex flex-col gap-1.5">
                <Label htmlFor="severity">Severity</Label>
                <Select value={formSeverity} onValueChange={(v) => v && setFormSeverity(v)}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select..." />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="critical">Critical</SelectItem>
                    <SelectItem value="high">High</SelectItem>
                    <SelectItem value="medium">Medium</SelectItem>
                    <SelectItem value="low">Low</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="flex flex-col gap-1.5">
                <Label htmlFor="description">Description</Label>
                <Textarea id="description" placeholder="" rows={4} value={formDescription} onChange={(e) => setFormDescription(e.target.value)} />
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setModalOpen(false)}>Cancel</Button>
              <Button onClick={handleCreateFinding}>Save</Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
      <div className="flex flex-row gap-3 items-center">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input type="search" placeholder="Search findings..." className="w-full pl-9 [&::-webkit-search-cancel-button]:hidden [&::-webkit-search-decoration]:hidden" value={searchFinding} onChange={(e) => setSearchFinding(e.target.value)} />
        </div>
        <Select onValueChange={(v) => setFilterFindingCategory(v as string)}>
          <SelectTrigger>
            <SelectValue placeholder="All Categories" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Categories</SelectItem>
            <SelectItem value="gap">Gap</SelectItem>
            <SelectItem value="strength">Strength</SelectItem>
            <SelectItem value="opportunity">Opportunity</SelectItem>
            <SelectItem value="risk">Risk</SelectItem>
          </SelectContent>
        </Select>
        <Select onValueChange={(v) => setFilterFindingSeverity(v as string)}>
          <SelectTrigger>
            <SelectValue placeholder="All Severities" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Severities</SelectItem>
            <SelectItem value="critical">Critical</SelectItem>
            <SelectItem value="high">High</SelectItem>
            <SelectItem value="medium">Medium</SelectItem>
            <SelectItem value="low">Low</SelectItem>
          </SelectContent>
        </Select>
        <Select onValueChange={(v) => setFilterFindingStatus(v as string)}>
          <SelectTrigger>
            <SelectValue placeholder="All Statuses" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Statuses</SelectItem>
            <SelectItem value="open">Open</SelectItem>
            <SelectItem value="acknowledged">Acknowledged</SelectItem>
            <SelectItem value="resolved">Resolved</SelectItem>
          </SelectContent>
        </Select>
      </div>
      <Card>
        <CardHeader>
          <CardTitle>All Findings</CardTitle>
          <CardDescription>Research observations sorted by severity — click to expand</CardDescription>
        </CardHeader>
        <CardContent>
          <DataTable
            data={(finding ?? [])
              .filter((item) => filterFindingCategory === "all" || item.category === filterFindingCategory)
              .filter((item) => filterFindingSeverity === "all" || item.severity === filterFindingSeverity)
              .filter((item) => filterFindingStatus === "all" || item.status === filterFindingStatus)
              .filter((item) => {
                if (!searchFinding) return true;
                const q = searchFinding.toLowerCase();
                return Object.values(item).some((v) => String(v).toLowerCase().includes(q));
              })}
            columns={[
              { accessorKey: "title", header: "Title" },
              { accessorKey: "repo_name", header: "Repo" },
              {
                accessorKey: "category",
                header: "Category",
                cell: ({ row }: { row: { getValue: (k: string) => unknown } }) => {
                  const v = String(row.getValue("category") ?? "");
                  const variants: Record<string, string> = { "opportunity": "info", "risk": "warning", "gap": "danger", "strength": "success" };
                  const variant = variants[v] ?? variants[v.toLowerCase()] ?? "default";
                  return <Badge variant={variant === "danger" ? "destructive" : variant === "success" || variant === "warning" || variant === "info" ? "outline" : "secondary"} className={
                    variant === "success" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-400" :
                    variant === "warning" ? "border-amber-500/30 bg-amber-500/10 text-amber-400" :
                    variant === "info" ? "border-blue-500/30 bg-blue-500/10 text-blue-400" :
                    variant === "danger" ? "" : ""
                  }>{v}</Badge>;
                },
              },
              {
                accessorKey: "severity",
                header: "Severity",
                cell: ({ row }: { row: { getValue: (k: string) => unknown } }) => {
                  const v = String(row.getValue("severity") ?? "");
                  const variants: Record<string, string> = { "low": "info", "critical": "danger", "high": "warning", "medium": "default" };
                  const variant = variants[v] ?? variants[v.toLowerCase()] ?? "default";
                  return <Badge variant={variant === "danger" ? "destructive" : variant === "success" || variant === "warning" || variant === "info" ? "outline" : "secondary"} className={
                    variant === "success" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-400" :
                    variant === "warning" ? "border-amber-500/30 bg-amber-500/10 text-amber-400" :
                    variant === "info" ? "border-blue-500/30 bg-blue-500/10 text-blue-400" :
                    variant === "danger" ? "" : ""
                  }>{v}</Badge>;
                },
              },
              {
                accessorKey: "status",
                header: "Status",
                cell: ({ row }: { row: { getValue: (k: string) => unknown } }) => {
                  const v = String(row.getValue("status") ?? "");
                  const variants: Record<string, string> = { "resolved": "success", "open": "danger", "acknowledged": "warning" };
                  const variant = variants[v] ?? variants[v.toLowerCase()] ?? "default";
                  return <Badge variant={variant === "danger" ? "destructive" : variant === "success" || variant === "warning" || variant === "info" ? "outline" : "secondary"} className={
                    variant === "success" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-400" :
                    variant === "warning" ? "border-amber-500/30 bg-amber-500/10 text-amber-400" :
                    variant === "info" ? "border-blue-500/30 bg-blue-500/10 text-blue-400" :
                    variant === "danger" ? "" : ""
                  }>{v}</Badge>;
                },
              },
            ]}
            emptyMessage="No matching results found."
            onRowClick={(row) => setSheetItem(row as Finding)}
          />
        </CardContent>
      </Card>
    </div>
    <Sheet open={!!sheetItem} onOpenChange={(open) => { if (!open) { setSheetItem(null); setEditing(false); } }}>
      <SheetContent side="right">
        <SheetHeader>
          <SheetTitle>{(sheetItem as unknown as Record<string, unknown>)?.title as string}</SheetTitle>
        </SheetHeader>
        {sheetItem && !editing && (
          <div className="flex flex-col gap-4 px-4 pt-4">
            <div className="flex flex-row gap-2">
              <Button variant="outline" size="sm" onClick={startEditing}>Edit</Button>
            </div>
            <div>
              <div className="text-xs text-muted-foreground">Title</div>
              <div className="text-sm">{String((sheetItem as unknown as Record<string, unknown>)?.title ?? "")}</div>
            </div>
            <div>
              <div className="text-xs text-muted-foreground">Category</div>
              <div className="text-sm">{String((sheetItem as unknown as Record<string, unknown>)?.category ?? "")}</div>
            </div>
            <div>
              <div className="text-xs text-muted-foreground">Severity</div>
              <div className="text-sm">{String((sheetItem as unknown as Record<string, unknown>)?.severity ?? "")}</div>
            </div>
            <div>
              <div className="text-xs text-muted-foreground">Status</div>
              <div className="text-sm">{String((sheetItem as unknown as Record<string, unknown>)?.status ?? "")}</div>
            </div>
            <div>
              <div className="text-xs text-muted-foreground">Description</div>
              <div className="text-sm">{String((sheetItem as unknown as Record<string, unknown>)?.description ?? "")}</div>
            </div>
          </div>
        )}
        {sheetItem && editing && (
          <div className="flex flex-col gap-4 px-4 pt-4">
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="edit-title">Title</Label>
              <Input id="edit-title" type="text" value={editTitle} onChange={(e) => setEditTitle(e.target.value)} />
            </div>
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="edit-category">Category</Label>
              <Select value={editCategory} onValueChange={(v) => v && setEditCategory(v)}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="gap">Gap</SelectItem>
                  <SelectItem value="strength">Strength</SelectItem>
                  <SelectItem value="opportunity">Opportunity</SelectItem>
                  <SelectItem value="risk">Risk</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="edit-severity">Severity</Label>
              <Select value={editSeverity} onValueChange={(v) => v && setEditSeverity(v)}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="critical">Critical</SelectItem>
                  <SelectItem value="high">High</SelectItem>
                  <SelectItem value="medium">Medium</SelectItem>
                  <SelectItem value="low">Low</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="edit-status">Status</Label>
              <Select value={editStatus} onValueChange={(v) => v && setEditStatus(v)}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="open">Open</SelectItem>
                  <SelectItem value="acknowledged">Acknowledged</SelectItem>
                  <SelectItem value="resolved">Resolved</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="edit-description">Description</Label>
              <Textarea id="edit-description" rows={4} value={editDescription} onChange={(e) => setEditDescription(e.target.value)} />
            </div>
            <div className="flex flex-row gap-2">
              <Button variant="outline" size="sm" onClick={() => setEditing(false)}>Cancel</Button>
              <Button size="sm" onClick={handleUpdate}>Save</Button>
            </div>
          </div>
        )}
      </SheetContent>
    </Sheet>
    <Toaster />
    </>
  );
}
