// types/snapshot.ts
// Generated by Sigil — do not edit manually

export interface Snapshot {
  id: string;
  repo_id?: string;
  captured_at?: string;
  stars?: unknown;
  forks?: unknown;
  loc?: unknown;
  files?: unknown;
  contributors?: unknown;
  commits_30d?: unknown;
  complexity_avg?: unknown;
}

export interface SnapshotInput {
  repo_id?: string;
  captured_at?: string;
  stars?: unknown;
  forks?: unknown;
  loc?: unknown;
  files?: unknown;
  contributors?: unknown;
  commits_30d?: unknown;
  complexity_avg?: unknown;
}
