// se-dashboard.tsx
// Generated by Sigil — do not edit manually

"use client";

import { useRouter } from "next/navigation";
import { useState, useRef, useCallback, useEffect } from "react";
import { toast } from "sonner";
import { postItem, fetchItem } from "@/lib/api";
import { AlertTriangle, BarChart3, CheckCircle2, Clock, FileText, GitCompare, GitFork, Layers, Loader2, Play, Shapes, XCircle } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Toaster } from "@/components/ui/sonner";
import { DataTable } from "@/components/data-table";
import { SigilChart } from "@/components/sigil-chart";
import { useDimension } from "@/hooks/use-dimension";
import { useDimensionScore } from "@/hooks/use-dimensionscore";
import { useFinding } from "@/hooks/use-finding";
import { usePattern } from "@/hooks/use-pattern";
import { useRepo } from "@/hooks/use-repo";
import { useScorecard } from "@/hooks/use-scorecard";
import { useScan } from "@/hooks/use-scan";
import type { Scan } from "@/types/scan";
import { useLensContext } from "@/lib/lens-context";

export default function SeDashboard() {
  const router = useRouter();
  const [scanning, setScanning] = useState(false);
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const { currentLensId, currentLensName } = useLensContext();

  const stopPolling = useCallback(() => {
    if (pollRef.current) {
      clearInterval(pollRef.current);
      pollRef.current = null;
    }
  }, []);

  useEffect(() => stopPolling, [stopPolling]);
  const { data: repo, isLoading: repoLoading } = useRepo();
  const { data: finding, isLoading: findingLoading } = useFinding();
  const { data: scorecard, isLoading: scorecardLoading } = useScorecard();
  const { data: dimension, isLoading: dimensionLoading } = useDimension();
  const { data: pattern, isLoading: patternLoading } = usePattern();
  const { data: dimensionScore, isLoading: dimensionScoreLoading } = useDimensionScore();
  const { data: scans, isLoading: scansLoading, refetch: refetchScans } = useScan();

  const lensFilteredScorecards = (scorecard ?? []).filter(
    (sc) => !currentLensId || sc.lens_id === currentLensId,
  );

  // Computed stats
  const totalRepos = (repo ?? []).length;
  const scoredRepos = new Set((scorecard ?? []).map((sc) => sc.repo_id)).size;
  const totalDimensions = (dimension ?? []).length;
  const totalPatterns = (pattern ?? []).length;
  const totalFindings = (finding ?? []).length;

  // Repos by Category (donut chart)
  const reposByCategory = Object.entries(
    (repo ?? []).reduce<Record<string, number>>((acc, r) => {
      const cat = String(r.category ?? "Other");
      acc[cat] = (acc[cat] ?? 0) + 1;
      return acc;
    }, {}),
  ).map(([category, count], i) => {
    const fills = ["oklch(0.623 0.214 259.815)", "oklch(0.6 0.118 184.704)", "oklch(0.828 0.189 84.429)", "oklch(0.769 0.188 70.08)", "oklch(0.646 0.222 41.116)", "oklch(0.55 0.02 0)", "oklch(0.7 0.15 200)", "oklch(0.65 0.2 320)"];
    return { category, count, fill: fills[i % fills.length] };
  });

  // Score Distribution (bar chart) — bucket scorecard overall scores
  const scoreDistribution = (() => {
    const buckets = [
      { range: "0-2", count: 0 },
      { range: "2-4", count: 0 },
      { range: "4-6", count: 0 },
      { range: "6-8", count: 0 },
      { range: "8-10", count: 0 },
    ];
    for (const sc of scorecard ?? []) {
      const score = Number(sc.overall ?? 0);
      const idx = Math.min(Math.floor(score / 2), 4);
      buckets[idx].count++;
    }
    return buckets;
  })();

  // Own vs Reference (bar chart) — average dimension scores by is_own
  const ownVsReference = (() => {
    const ownRepoIds = new Set((repo ?? []).filter((r) => r.is_own).map((r) => r.id));
    const scorecardRepoMap = new Map((scorecard ?? []).map((sc) => [sc.id, sc.repo_id]));
    const dimAccum: Record<string, { ownSum: number; ownCount: number; refSum: number; refCount: number }> = {};
    for (const ds of dimensionScore ?? []) {
      const dimName = ds.dimension_name ?? "Unknown";
      const repoId = scorecardRepoMap.get(ds.scorecard_id ?? "");
      const score = Number(ds.score ?? 0);
      if (!dimAccum[dimName]) dimAccum[dimName] = { ownSum: 0, ownCount: 0, refSum: 0, refCount: 0 };
      if (repoId && ownRepoIds.has(repoId)) {
        dimAccum[dimName].ownSum += score;
        dimAccum[dimName].ownCount++;
      } else {
        dimAccum[dimName].refSum += score;
        dimAccum[dimName].refCount++;
      }
    }
    return Object.entries(dimAccum)
      .map(([dimension, v]) => ({
        dimension,
        own: v.ownCount ? Math.round((v.ownSum / v.ownCount) * 10) / 10 : 0,
        reference: v.refCount ? Math.round((v.refSum / v.refCount) * 10) / 10 : 0,
      }))
      .slice(0, 6);
  })();

  if (repoLoading || findingLoading || scorecardLoading || dimensionLoading || patternLoading || dimensionScoreLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-6 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <div className="flex flex-col gap-1">
          <h1 className="text-2xl font-semibold tracking-tight text-foreground">Dashboard</h1>
          <p className="text-sm text-muted-foreground">AI agent tooling research landscape</p>
        </div>
        <div className="flex flex-row gap-2">
          <Select>
            <SelectTrigger>
              <SelectValue placeholder="Last 30 days" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="7d">Last 7 days</SelectItem>
              <SelectItem value="30d">Last 30 days</SelectItem>
              <SelectItem value="90d">Last 90 days</SelectItem>
              <SelectItem value="all">All time</SelectItem>
            </SelectContent>
          </Select>
          <Button variant="default" disabled={scanning} onClick={async () => {
            const repos = repo ?? [];
            if (!repos.length) { toast.error("No repos to scan"); return; }
            setScanning(true);
            try {
              const results = await Promise.allSettled(
                repos.map((r) => postItem<Scan>("scans", { repo_id: r.id, blueprint: "se-repo-scan" }))
              );
              const succeeded = results.filter((r) => r.status === "fulfilled").length;
              const failed = results.length - succeeded;
              toast.success(`Queued ${succeeded} scan${succeeded !== 1 ? "s" : ""}${failed ? ` (${failed} failed)` : ""}`);
              refetchScans();
              // Poll the last successful scan for completion
              const lastOk = [...results].reverse().find((r) => r.status === "fulfilled");
              if (lastOk && lastOk.status === "fulfilled") {
                const scanId = lastOk.value.id;
                pollRef.current = setInterval(async () => {
                  try {
                    const updated = await fetchItem<Scan>("scans", scanId);
                    if (updated.status === "completed" || updated.status === "failed") {
                      stopPolling();
                      setScanning(false);
                      if (updated.status === "completed") toast.success("Scans completed");
                      else toast.error(updated.error_message || "Scan failed");
                      refetchScans();
                    }
                  } catch {
                    stopPolling();
                    setScanning(false);
                  }
                }, 3000);
              } else {
                setScanning(false);
              }
            } catch (e) {
              toast.error(e instanceof Error ? e.message : "Failed to start scans");
              setScanning(false);
            }
          }}>
            {scanning ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Play className="mr-2 h-4 w-4" />}
            {scanning ? "Scanning…" : "Run Scan"}
          </Button>
        </div>
      </div>
      <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Repos</CardTitle>
            <GitFork className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{totalRepos}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Scored</CardTitle>
            <BarChart3 className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{scoredRepos}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Dimensions</CardTitle>
            <Layers className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{totalDimensions}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Patterns</CardTitle>
            <Shapes className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{totalPatterns}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Findings</CardTitle>
            <AlertTriangle className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{totalFindings}</div>
          </CardContent>
        </Card>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
        <Card>
          <CardHeader>
            <CardTitle>Repos by Category</CardTitle>
            <CardDescription>Distribution across repo types</CardDescription>
          </CardHeader>
          <CardContent>
            <SigilChart
              type="donut"
              xKey="category"
              height={250}
              showLegend
              dataKeys={["count"]}
              config={{
                count: { label: "Repos", color: "var(--chart-1)" },
              }}
              data={reposByCategory}
            />
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Score Distribution</CardTitle>
            <CardDescription>Repos by overall score range</CardDescription>
          </CardHeader>
          <CardContent>
            <SigilChart
              type="bar"
              xKey="range"
              height={250}
              showGrid
              dataKeys={["count"]}
              config={{
                count: { label: "Repos", color: "var(--chart-1)" },
              }}
              data={scoreDistribution}
            />
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Own Projects vs References</CardTitle>
            <CardDescription>Average scores by dimension</CardDescription>
          </CardHeader>
          <CardContent>
            <SigilChart
              type="bar"
              xKey="dimension"
              height={250}
              showGrid
              showLegend
              dataKeys={["own", "reference"]}
              config={{
                own: { label: "Own Projects", color: "oklch(0.623 0.214 259.815)" },
                reference: { label: "Reference Avg", color: "oklch(0.55 0.02 0)" },
              }}
              data={ownVsReference}
            />
          </CardContent>
        </Card>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <Card>
          <CardHeader>
            <CardTitle>Top Scored Repos</CardTitle>
            <CardDescription>Highest overall scores in {currentLensName || "selected"} lens</CardDescription>
          </CardHeader>
          <CardContent>
            <DataTable
              data={lensFilteredScorecards}
              columns={[
                { accessorKey: "repo_name", header: "Repo" },
                { accessorKey: "overall", header: "Score" },
                {
                  accessorKey: "lens_name",
                  header: "Lens",
                  cell: ({ row }: { row: { getValue: (k: string) => unknown } }) => {
                    const v = String(row.getValue("lens_name") ?? "");
                    const variants: Record<string, string> = { "Engineering": "info", "Product": "default", "Leadership": "warning", "Security": "danger", "Community": "success", "Overall": "default", "Innovation": "success", "Adoption": "warning", "Maintainability": "info" };
                    const variant = variants[v] ?? variants[v.toLowerCase()] ?? "default";
                    return <Badge variant={variant === "danger" ? "destructive" : variant === "success" || variant === "warning" || variant === "info" ? "outline" : "secondary"} className={
                      variant === "success" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-400" :
                      variant === "warning" ? "border-amber-500/30 bg-amber-500/10 text-amber-400" :
                      variant === "info" ? "border-blue-500/30 bg-blue-500/10 text-blue-400" :
                      variant === "danger" ? "" : ""
                    }>{v}</Badge>;
                  },
                },
              ]}
            />
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Recent Findings</CardTitle>
            <CardDescription>Latest research observations</CardDescription>
          </CardHeader>
          <CardContent>
            <DataTable
              data={finding ?? []}
              columns={[
                { accessorKey: "title", header: "Title" },
                { accessorKey: "repo_name", header: "Repo" },
                {
                  accessorKey: "category",
                  header: "Category",
                  cell: ({ row }: { row: { getValue: (k: string) => unknown } }) => {
                    const v = String(row.getValue("category") ?? "");
                    const variants: Record<string, string> = { "risk": "warning", "gap": "danger", "strength": "success", "opportunity": "info" };
                    const variant = variants[v] ?? variants[v.toLowerCase()] ?? "default";
                    return <Badge variant={variant === "danger" ? "destructive" : variant === "success" || variant === "warning" || variant === "info" ? "outline" : "secondary"} className={
                      variant === "success" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-400" :
                      variant === "warning" ? "border-amber-500/30 bg-amber-500/10 text-amber-400" :
                      variant === "info" ? "border-blue-500/30 bg-blue-500/10 text-blue-400" :
                      variant === "danger" ? "" : ""
                    }>{v}</Badge>;
                  },
                },
                {
                  accessorKey: "severity",
                  header: "Severity",
                  cell: ({ row }: { row: { getValue: (k: string) => unknown } }) => {
                    const v = String(row.getValue("severity") ?? "");
                    const variants: Record<string, string> = { "critical": "danger", "high": "warning", "medium": "default", "low": "info" };
                    const variant = variants[v] ?? variants[v.toLowerCase()] ?? "default";
                    return <Badge variant={variant === "danger" ? "destructive" : variant === "success" || variant === "warning" || variant === "info" ? "outline" : "secondary"} className={
                      variant === "success" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-400" :
                      variant === "warning" ? "border-amber-500/30 bg-amber-500/10 text-amber-400" :
                      variant === "info" ? "border-blue-500/30 bg-blue-500/10 text-blue-400" :
                      variant === "danger" ? "" : ""
                    }>{v}</Badge>;
                  },
                },
              ]}
              onRowClick={() => router.push("/findings")}
            />
          </CardContent>
        </Card>
      </div>
      <div className="flex flex-row gap-3">
        <Button variant="outline" onClick={() => router.push("/repos?action=create")}>
          <GitFork className="mr-2 h-4 w-4" />
          Add Repo
        </Button>
        <Button variant="outline" onClick={() => router.push("/reports?action=create")}>
          <FileText className="mr-2 h-4 w-4" />
          Generate Report
        </Button>
        <Button variant="outline" onClick={() => router.push("/gap-analysis?action=create")}>
          <GitCompare className="mr-2 h-4 w-4" />
          New Comparison
        </Button>
      </div>
      <Card>
        <CardHeader>
          <CardTitle>Scan History</CardTitle>
          <CardDescription>Recent scan jobs</CardDescription>
        </CardHeader>
        <CardContent>
          {scansLoading ? (
            <div className="flex items-center justify-center py-6">
              <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
            </div>
          ) : (
            <DataTable
              data={(scans ?? []).slice(0, 10)}
              columns={[
                {
                  accessorKey: "status",
                  header: "Status",
                  cell: ({ row }: { row: { getValue: (k: string) => unknown } }) => {
                    const status = String(row.getValue("status") ?? "");
                    const icons: Record<string, React.ReactNode> = {
                      pending: <Clock className="h-4 w-4 text-muted-foreground" />,
                      running: <Loader2 className="h-4 w-4 animate-spin text-blue-400" />,
                      completed: <CheckCircle2 className="h-4 w-4 text-emerald-400" />,
                      failed: <XCircle className="h-4 w-4 text-red-400" />,
                    };
                    return (
                      <div className="flex items-center gap-2">
                        {icons[status] ?? null}
                        <Badge
                          variant={status === "failed" ? "destructive" : status === "completed" ? "outline" : "secondary"}
                          className={
                            status === "completed" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-400" :
                            status === "running" ? "border-blue-500/30 bg-blue-500/10 text-blue-400" : ""
                          }
                        >
                          {status}
                        </Badge>
                      </div>
                    );
                  },
                },
                { accessorKey: "repo_name", header: "Repo" },
                { accessorKey: "blueprint", header: "Blueprint" },
                {
                  accessorKey: "created_at",
                  header: "Started",
                  cell: ({ row }: { row: { getValue: (k: string) => unknown } }) => {
                    const v = row.getValue("created_at");
                    if (!v) return "—";
                    const d = new Date(String(v));
                    return d.toLocaleString(undefined, { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" });
                  },
                },
                {
                  accessorKey: "finished_at",
                  header: "Finished",
                  cell: ({ row }: { row: { getValue: (k: string) => unknown } }) => {
                    const v = row.getValue("finished_at");
                    if (!v) return "—";
                    const d = new Date(String(v));
                    return d.toLocaleString(undefined, { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" });
                  },
                },
              ]}
              emptyMessage="No scans yet. Click Run Scan to start one."
            />
          )}
        </CardContent>
      </Card>
    </div>
    <Toaster />
    </>
  );
}
