// se-dashboard.tsx
// Generated by Sigil — do not edit manually

"use client";

import { useRouter } from "next/navigation";
import { AlertTriangle, BarChart3, FileText, GitCompare, GitFork, Layers, Loader2, Shapes } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { DataTable } from "@/components/data-table";
import { OwnVsReferenceChart } from "@/components/own-vs-reference-chart";
import { ReposByCategoryChart } from "@/components/repos-by-category-chart";
import { ScanRunner } from "@/components/scan-runner";
import { ScoreDistributionChart } from "@/components/score-distribution-chart";
import { useDimension } from "@/hooks/use-dimension";
import { useDimensionScore } from "@/hooks/use-dimensionscore";
import { useFinding } from "@/hooks/use-finding";
import { usePattern } from "@/hooks/use-pattern";
import { useRepo } from "@/hooks/use-repo";
import { useScorecard } from "@/hooks/use-scorecard";

export default function SeDashboard() {
  const router = useRouter();
  const { data: repo, isLoading: repoLoading } = useRepo();
  const { data: finding, isLoading: findingLoading } = useFinding();
  const { data: scorecard, isLoading: scorecardLoading } = useScorecard();
  const { data: dimension, isLoading: dimensionLoading } = useDimension();
  const { data: pattern, isLoading: patternLoading } = usePattern();
  const { data: dimensionScore, isLoading: dimensionScoreLoading } = useDimensionScore();

  if (repoLoading || findingLoading || scorecardLoading || dimensionLoading || patternLoading || dimensionScoreLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-6 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <div className="flex flex-col gap-1">
          <h1 className="text-2xl font-semibold tracking-tight text-foreground">Dashboard</h1>
          <p className="text-sm text-muted-foreground">AI agent tooling research landscape</p>
        </div>
        <div className="flex flex-row gap-2">
          <Select>
            <SelectTrigger>
              <SelectValue placeholder="Last 30 days" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="7d">Last 7 days</SelectItem>
              <SelectItem value="30d">Last 30 days</SelectItem>
              <SelectItem value="90d">Last 90 days</SelectItem>
              <SelectItem value="all">All time</SelectItem>
            </SelectContent>
          </Select>
          <ScanRunner
            repos={repo}
          />
        </div>
      </div>
      <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Repos</CardTitle>
            <GitFork className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{`{{repo.length}}`}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Scored</CardTitle>
            <BarChart3 className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{`{{scoredRepos}}`}</div>
            <p className="text-xs text-emerald-500">Trending up</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Dimensions</CardTitle>
            <Layers className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{`{{dimension.length}}`}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Patterns</CardTitle>
            <Shapes className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{`{{pattern.length}}`}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Findings</CardTitle>
            <AlertTriangle className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{`{{finding.length}}`}</div>
            <p className="text-xs text-emerald-500">Trending up</p>
          </CardContent>
        </Card>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
        <ReposByCategoryChart
          repos={repo}
        />
        <ScoreDistributionChart
          scorecards={scorecard}
        />
        <OwnVsReferenceChart
          repos={repo}
          scorecards={scorecard}
          dimensionScores={dimensionScore}
        />
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <Card>
          <CardHeader>
            <CardTitle>Top Scored Repos</CardTitle>
            <CardDescription>Highest overall scores in current lens</CardDescription>
          </CardHeader>
          <CardContent>
            <DataTable
              data={scorecard ?? []}
              columns={[
                { accessorKey: "repo_name", header: "Repo" },
                { accessorKey: "overall", header: "Score" },
                {
                  accessorKey: "lens_name",
                  header: "Lens",
                  cell: ({ row }: { row: { getValue: (k: string) => unknown } }) => {
                    const v = String(row.getValue("lens_name") ?? "");
                    const variants: Record<string, string> = { "Product": "default", "Leadership": "warning", "Security": "danger", "Community": "success", "Maintainability": "info", "Engineering": "info", "Overall": "default", "Innovation": "success", "Adoption": "warning" };
                    const variant = variants[v] ?? variants[v.toLowerCase()] ?? "default";
                    return <Badge variant={variant === "danger" ? "destructive" : variant === "success" || variant === "warning" || variant === "info" ? "outline" : "secondary"} className={
                      variant === "success" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-400" :
                      variant === "warning" ? "border-amber-500/30 bg-amber-500/10 text-amber-400" :
                      variant === "info" ? "border-blue-500/30 bg-blue-500/10 text-blue-400" :
                      variant === "danger" ? "" : ""
                    }>{v}</Badge>;
                  },
                },
              ]}
            />
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Recent Findings</CardTitle>
            <CardDescription>Latest research observations</CardDescription>
          </CardHeader>
          <CardContent>
            <DataTable
              data={finding ?? []}
              columns={[
                { accessorKey: "title", header: "Title" },
                { accessorKey: "repo_name", header: "Repo" },
                {
                  accessorKey: "category",
                  header: "Category",
                  cell: ({ row }: { row: { getValue: (k: string) => unknown } }) => {
                    const v = String(row.getValue("category") ?? "");
                    const variants: Record<string, string> = { "gap": "danger", "strength": "success", "opportunity": "info", "risk": "warning" };
                    const variant = variants[v] ?? variants[v.toLowerCase()] ?? "default";
                    return <Badge variant={variant === "danger" ? "destructive" : variant === "success" || variant === "warning" || variant === "info" ? "outline" : "secondary"} className={
                      variant === "success" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-400" :
                      variant === "warning" ? "border-amber-500/30 bg-amber-500/10 text-amber-400" :
                      variant === "info" ? "border-blue-500/30 bg-blue-500/10 text-blue-400" :
                      variant === "danger" ? "" : ""
                    }>{v}</Badge>;
                  },
                },
                {
                  accessorKey: "severity",
                  header: "Severity",
                  cell: ({ row }: { row: { getValue: (k: string) => unknown } }) => {
                    const v = String(row.getValue("severity") ?? "");
                    const variants: Record<string, string> = { "critical": "danger", "high": "warning", "medium": "default", "low": "info" };
                    const variant = variants[v] ?? variants[v.toLowerCase()] ?? "default";
                    return <Badge variant={variant === "danger" ? "destructive" : variant === "success" || variant === "warning" || variant === "info" ? "outline" : "secondary"} className={
                      variant === "success" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-400" :
                      variant === "warning" ? "border-amber-500/30 bg-amber-500/10 text-amber-400" :
                      variant === "info" ? "border-blue-500/30 bg-blue-500/10 text-blue-400" :
                      variant === "danger" ? "" : ""
                    }>{v}</Badge>;
                  },
                },
              ]}
              onRowClick={() => router.push("/findings")}
            />
          </CardContent>
        </Card>
      </div>
      <div className="flex flex-row gap-3">
        <Button variant="outline" onClick={() => router.push("/repos")}>
          <GitFork className="mr-2 h-4 w-4" />
          Add Repo
        </Button>
        <Button variant="outline" onClick={() => router.push("/reports")}>
          <FileText className="mr-2 h-4 w-4" />
          Generate Report
        </Button>
        <Button variant="outline" onClick={() => router.push("/gap-analysis")}>
          <GitCompare className="mr-2 h-4 w-4" />
          New Comparison
        </Button>
      </div>
    </div>
    </>
  );
}
