// forge-deployments.tsx
// Generated by Sigil — do not edit manually

"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { toast } from "sonner";
import { ArrowUpCircle, Eye, Loader2, Rocket, Search, Trash2, Undo2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { ContextMenu, ContextMenuContent, ContextMenuItem, ContextMenuSeparator, ContextMenuTrigger } from "@/components/ui/context-menu";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Toaster } from "@/components/ui/sonner";
import { DataTable } from "@/components/data-table";
import { useDeployment } from "@/hooks/use-deployment";

export default function ForgeDeployments() {
  const router = useRouter();
  const [filterDeploymentEnvironment, setFilterDeploymentEnvironment] = useState("all");
  const [searchDeployment, setSearchDeployment] = useState("");

  const { data: deployment, isLoading: deploymentLoading } = useDeployment();

  if (deploymentLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-6 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <h1 className="text-2xl font-semibold tracking-tight text-foreground">Deployments</h1>
        <div className="flex flex-row gap-2">
          <Select onValueChange={(v) => setFilterDeploymentEnvironment(v as string)}>
            <SelectTrigger>
              <SelectValue placeholder="All Environments" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All</SelectItem>
              <SelectItem value="production">Production</SelectItem>
              <SelectItem value="staging">Staging</SelectItem>
              <SelectItem value="preview">Preview</SelectItem>
            </SelectContent>
          </Select>
          <Button variant="default" onClick={() => router.push("/deployments")}>
            <Rocket className="mr-2 h-4 w-4" />
            Deploy
          </Button>
        </div>
      </div>
      <div className="relative">
        <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
        <Input type="search" placeholder="Search deployments..." className="w-full pl-9 [&::-webkit-search-cancel-button]:hidden [&::-webkit-search-decoration]:hidden" value={searchDeployment} onChange={(e) => setSearchDeployment(e.target.value)} />
      </div>
      <ContextMenu>
        <ContextMenuTrigger>
          <Card className="border-0 shadow-none ring-0">
            <CardContent>
              <DataTable
                data={(deployment ?? [])
                  .filter((item) => filterDeploymentEnvironment === "all" || item.environment === filterDeploymentEnvironment)
                  .filter((item) => {
                    if (!searchDeployment) return true;
                    const q = searchDeployment.toLowerCase();
                    return Object.values(item).some((v) => String(v).toLowerCase().includes(q));
                  })}
                columns={[
                  {
                    accessorKey: "status",
                    header: "Status",
                    cell: ({ row }: { row: { getValue: (k: string) => unknown } }) => {
                      const v = String(row.getValue("status") ?? "");
                      const variants: Record<string, string> = { "deploying": "info", "building": "default", "failed": "danger", "cancelled": "warning", "ready": "success" };
                      const variant = variants[v] ?? variants[v.toLowerCase()] ?? "default";
                      return <Badge variant={variant === "danger" ? "destructive" : variant === "success" || variant === "warning" || variant === "info" ? "outline" : "secondary"} className={
                        variant === "success" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-400" :
                        variant === "warning" ? "border-amber-500/30 bg-amber-500/10 text-amber-400" :
                        variant === "info" ? "border-blue-500/30 bg-blue-500/10 text-blue-400" :
                        variant === "danger" ? "" : ""
                      }>{v}</Badge>;
                    },
                  },
                  { accessorKey: "name", header: "Name" },
                  {
                    accessorKey: "environment",
                    header: "Environment",
                    cell: ({ row }: { row: { getValue: (k: string) => unknown } }) => {
                      const v = String(row.getValue("environment") ?? "");
                      const variants: Record<string, string> = { "production": "danger", "staging": "warning", "preview": "default" };
                      const variant = variants[v] ?? variants[v.toLowerCase()] ?? "default";
                      return <Badge variant={variant === "danger" ? "destructive" : variant === "success" || variant === "warning" || variant === "info" ? "outline" : "secondary"} className={
                        variant === "success" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-400" :
                        variant === "warning" ? "border-amber-500/30 bg-amber-500/10 text-amber-400" :
                        variant === "info" ? "border-blue-500/30 bg-blue-500/10 text-blue-400" :
                        variant === "danger" ? "" : ""
                      }>{v}</Badge>;
                    },
                  },
                  { accessorKey: "branch", header: "Branch" },
                  { accessorKey: "author", header: "Author" },
                  { accessorKey: "duration", header: "Duration" },
                  { accessorKey: "createdAt", header: "Created" },
                ]}
                emptyMessage="No matching results found."
                onRowClick={(row) => router.push(`/deployment-detail/${(row as { id: string }).id}`)}
              />
            </CardContent>
          </Card>
        </ContextMenuTrigger>
        <ContextMenuContent>
          <ContextMenuItem onSelect={() => router.push("/deployment-detail")}><span className="flex items-center gap-2"><Eye className="h-4 w-4" />View Details</span></ContextMenuItem>
          <ContextMenuItem onSelect={() => toast("Deployment promoted to production")}><span className="flex items-center gap-2"><ArrowUpCircle className="h-4 w-4" />Promote to Production</span></ContextMenuItem>
          <ContextMenuItem onSelect={() => toast("Rollback initiated")}><span className="flex items-center gap-2"><Undo2 className="h-4 w-4" />Rollback</span></ContextMenuItem>
          <ContextMenuSeparator />
          <ContextMenuItem className="text-destructive focus:text-destructive" onSelect={() => toast("Deployment deleted")}><span className="flex items-center gap-2"><Trash2 className="h-4 w-4" />Delete Deployment</span></ContextMenuItem>
        </ContextMenuContent>
      </ContextMenu>
    </div>
    <Toaster />
    </>
  );
}
