// clockwork-templates.tsx
// Generated by Sigil — do not edit manually

import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Loader2, Plus, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { DataTable } from "@/components/data-table";
import { useTemplate } from "@/hooks/use-template";

export default function ClockworkTemplates() {
  const navigate = useNavigate();
  const [filterTemplateArchiveStatus, setFilterTemplateArchiveStatus] = useState("all");
  const [searchTemplate, setSearchTemplate] = useState("");

  const { data: template, isLoading: templateLoading } = useTemplate();

  if (templateLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-6 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <h1 className="text-2xl font-semibold tracking-tight text-foreground">Templates</h1>
        <div className="flex flex-row gap-2">
          <Select onValueChange={(v) => setFilterTemplateArchiveStatus(v as string)}>
            <SelectTrigger>
              <SelectValue placeholder="Show Active" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="active">Active</SelectItem>
              <SelectItem value="archived">Archived</SelectItem>
              <SelectItem value="all">All</SelectItem>
            </SelectContent>
          </Select>
          <Button variant="default" onClick={() => navigate("/template-editor")}>
            <Plus className="mr-2 h-4 w-4" />
            New Template
          </Button>
        </div>
      </div>
      <div className="relative">
        <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
        <Input type="search" placeholder="Search templates..." className="w-full pl-9 [&::-webkit-search-cancel-button]:hidden [&::-webkit-search-decoration]:hidden" value={searchTemplate} onChange={(e) => setSearchTemplate(e.target.value)} />
      </div>
      <DataTable
        data={(template ?? [])
          .filter((item) => filterTemplateArchiveStatus === "all" || item.archive_status === filterTemplateArchiveStatus)
          .filter((item) => {
            if (!searchTemplate) return true;
            const q = searchTemplate.toLowerCase();
            return Object.values(item).some((v) => String(v).toLowerCase().includes(q));
          })}
        columns={[
          { accessorKey: "name", header: "Name" },
          { accessorKey: "version", header: "Version" },
          { accessorKey: "kind", header: "Kind" },
          { accessorKey: "auto_execute", header: "Auto-Execute" },
          { accessorKey: "status", header: "Status" },
          { accessorKey: "updated_at", header: "Updated" },
        ]}
        emptyMessage="No matching results found."
      />
    </div>
    </>
  );
}
