// clockwork-dashboard.tsx
// Generated by Sigil — do not edit manually

import { useNavigate } from "react-router-dom";
import { Activity, AlertCircle, DollarSign, Loader2, Play } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { DataTable } from "@/components/data-table";
import { ScopeManager } from "@/components/scope-manager";
import { SigilChart } from "@/components/sigil-chart";
import { useRun } from "@/hooks/use-run";
import { useTask } from "@/hooks/use-task";

export default function ClockworkDashboard() {
  const navigate = useNavigate();
  const { data: run, isLoading: runLoading } = useRun();
  const { data: task, isLoading: taskLoading } = useTask();

  if (runLoading || taskLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-6 p-6">
      <Tabs defaultValue="activity">
        <TabsList>
          <TabsTrigger value="activity">Activity</TabsTrigger>
          <TabsTrigger value="mission-control">Mission Control</TabsTrigger>
          <TabsTrigger value="usage">Usage</TabsTrigger>
        </TabsList>
        <TabsContent value="activity">
          <div className="flex flex-row gap-4">
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">Runs Today</CardTitle>
                <Activity className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{`{{Run.runs_today}}`}</div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">Active</CardTitle>
                <Play className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{`{{Run.active}}`}</div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">Errors</CardTitle>
                <AlertCircle className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{`{{Run.errors}}`}</div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">Total Cost</CardTitle>
                <DollarSign className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{`{{Run.total_cost}}`}</div>
              </CardContent>
            </Card>
          </div>
          <SigilChart
            type="bar"
            xKey="date"
            height={250}
            showGrid
            dataKeys={["runs"]}
            config={{
              runs: { label: "runs", color: "var(--chart-1)" },
            }}
            data={run ?? []}
          />
          <SigilChart
            type="area"
            xKey="timestamp"
            height={200}
            showGrid
            dataKeys={["throughput"]}
            config={{
              throughput: { label: "throughput", color: "var(--chart-1)" },
            }}
            data={run ?? []}
          />
          <DataTable
            data={run ?? []}
            columns={[
              { accessorKey: "id", header: "ID" },
              { accessorKey: "task_title", header: "Task" },
              { accessorKey: "status", header: "Status" },
              { accessorKey: "duration", header: "Duration" },
              { accessorKey: "cost", header: "Cost" },
              { accessorKey: "started_at", header: "Started" },
            ]}
            onRowClick={() => navigate("/forge-run-detail")}
          />
        </TabsContent>
        <TabsContent value="mission-control">
          <div className="flex flex-row gap-4">
            <SigilChart
              type="area"
              xKey="date"
              height={300}
              showGrid
              showLegend
              dataKeys={["runs"]}
              config={{
                runs: { label: "Runs", color: "primary" },
              }}
              data={run ?? []}
            />
            <SigilChart
              type="pie"
              xKey="status"
              height={300}
              showLegend
              dataKeys={["count"]}
              config={{
                count: { label: "count", color: "var(--chart-1)" },
              }}
              data={run ?? []}
            />
            <SigilChart
              type="bar"
              xKey="model"
              height={300}
              showGrid
              showLegend
              stacked
              dataKeys={["tokens"]}
              config={{
                tokens: { label: "tokens", color: "var(--chart-1)" },
              }}
              data={run ?? []}
            />
          </div>
          <div className="flex flex-col gap-4">
            <h3 className="text-lg font-semibold tracking-tight text-foreground">Task Pipeline</h3>
            <ScopeManager
              datasource="Task"
              mode="assign"
            />
          </div>
        </TabsContent>
        <TabsContent value="usage">
          <SigilChart
            type="bar"
            xKey="date"
            height={300}
            showGrid
            showLegend
            dataKeys={["cost"]}
            config={{
              cost: { label: "cost", color: "var(--chart-1)" },
            }}
            data={run ?? []}
          />
          <div className="flex flex-row gap-4">
            <SigilChart
              type="donut"
              xKey="provider"
              height={250}
              showLegend
              dataKeys={["cost"]}
              config={{
                cost: { label: "cost", color: "var(--chart-1)" },
              }}
              data={run ?? []}
            />
            <DataTable
              data={run ?? []}
              columns={[
                { accessorKey: "provider", header: "Provider" },
                { accessorKey: "run_count", header: "Runs" },
                { accessorKey: "cost", header: "Cost" },
                { accessorKey: "tokens", header: "Tokens" },
              ]}
            />
          </div>
        </TabsContent>
      </Tabs>
    </div>
    </>
  );
}
