// clockwork-models.tsx
// Generated by Sigil — do not edit manually

import { Loader2 } from "lucide-react";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { DataTable } from "@/components/data-table";
import { useModel } from "@/hooks/use-model";

export default function ClockworkModels() {
  const { data: model, isLoading: modelLoading } = useModel();

  if (modelLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-6 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <h1 className="text-2xl font-semibold tracking-tight text-foreground">Models</h1>
      </div>
      <div className="flex flex-row gap-4 items-center">
        <Select>
          <SelectTrigger>
            <SelectValue placeholder="All Providers" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="anthropic">Anthropic</SelectItem>
            <SelectItem value="openai">OpenAI</SelectItem>
            <SelectItem value="google">Google</SelectItem>
            <SelectItem value="meta">Meta</SelectItem>
            <SelectItem value="mistral">Mistral</SelectItem>
            <SelectItem value="amazon">Amazon</SelectItem>
          </SelectContent>
        </Select>
      </div>
      <DataTable
        data={model ?? []}
        columns={[
          { accessorKey: "provider", header: "Provider" },
          { accessorKey: "model_id", header: "Model ID" },
          { accessorKey: "family", header: "Family" },
          { accessorKey: "input_cost", header: "Input Cost" },
          { accessorKey: "output_cost", header: "Output Cost" },
          { accessorKey: "context_window", header: "Context Window" },
          { accessorKey: "capabilities", header: "Capabilities" },
        ]}
      />
    </div>
    </>
  );
}
