// clockwork-sprints.tsx
// Generated by Sigil — do not edit manually

import { useState } from "react";
import { toast } from "sonner";
import { Loader2, Plus, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Toaster } from "@/components/ui/sonner";
import { DataTable } from "@/components/data-table";
import { useProject } from "@/hooks/use-project";
import { useSprint } from "@/hooks/use-sprint";
import { postItem } from "@/lib/api";

export default function ClockworkSprints() {
  const [modalOpen, setModalOpen] = useState(false);
  const [formName, setFormName] = useState("");
  const [formGoal, setFormGoal] = useState("");
  const [formStatus, setFormStatus] = useState("");
  const [formProjectId, setFormProjectId] = useState("");
  const [formStartDate, setFormStartDate] = useState("");
  const [formEndDate, setFormEndDate] = useState("");
  const [formCostBudget, setFormCostBudget] = useState("");
    const handleCreateSprint = async () => {
    try {
      await postItem("sprints", {
        name: formName,
        goal: formGoal,
        status: formStatus,
        project_id: formProjectId,
        start_date: formStartDate,
        end_date: formEndDate,
        cost_budget: formCostBudget,
      });
      toast.success("Sprint created");
      setModalOpen(false);
      setFormName("");
      setFormGoal("");
      setFormStatus("");
      setFormProjectId("");
      setFormStartDate("");
      setFormEndDate("");
      setFormCostBudget("");
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to create sprint");
    }
  };


  const [searchSprint, setSearchSprint] = useState("");

  const { data: sprint, isLoading: sprintLoading, refetch: refetchSprint } = useSprint();
  const { data: project, isLoading: projectLoading } = useProject();

  if (sprintLoading || projectLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-6 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <h1 className="text-2xl font-semibold tracking-tight text-foreground">Sprints</h1>
        <Dialog open={modalOpen} onOpenChange={setModalOpen}>
          <DialogTrigger render={<Button variant="default" />}>
            <Plus className="mr-2 h-4 w-4" />
            New Sprint
          </DialogTrigger>
          <DialogContent className="sm:max-w-lg">
            <DialogHeader>
              <DialogTitle>New Sprint</DialogTitle>
            </DialogHeader>
            <div className="flex flex-col gap-4 py-4">
              <div className="flex flex-col gap-1.5">
                <Label htmlFor="name">Name</Label>
                <Input id="name" type="text" placeholder="Sprint 1" value={formName} onChange={(e) => setFormName(e.target.value)} />
              </div>
              <div className="flex flex-col gap-1.5">
                <Label htmlFor="goal">Goal</Label>
                <Input id="goal" type="text" placeholder="Sprint goal description" value={formGoal} onChange={(e) => setFormGoal(e.target.value)} />
              </div>
              <div className="flex flex-col gap-1.5">
                <Label htmlFor="status">Status</Label>
                <Select value={formStatus} onValueChange={(v) => v && setFormStatus(v)}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select..." />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="planning">Planning</SelectItem>
                    <SelectItem value="active">Active</SelectItem>
                    <SelectItem value="completed">Completed</SelectItem>
                    <SelectItem value="cancelled">Cancelled</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="flex flex-col gap-1.5">
                <Label htmlFor="project_id">Project</Label>
                <Select value={formProjectId} onValueChange={(v) => v && setFormProjectId(v)}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select..." />
                  </SelectTrigger>
                  <SelectContent>
                  </SelectContent>
                </Select>
              </div>
              <div className="flex flex-col gap-1.5">
                <Label htmlFor="start_date">Start Date</Label>
                <Input id="start_date" type="date" placeholder="" value={formStartDate} onChange={(e) => setFormStartDate(e.target.value)} />
              </div>
              <div className="flex flex-col gap-1.5">
                <Label htmlFor="end_date">End Date</Label>
                <Input id="end_date" type="date" placeholder="" value={formEndDate} onChange={(e) => setFormEndDate(e.target.value)} />
              </div>
              <div className="flex flex-col gap-1.5">
                <Label htmlFor="cost_budget">Cost Budget</Label>
                <Input id="cost_budget" type="number" placeholder="0.00" value={formCostBudget} onChange={(e) => setFormCostBudget(e.target.value)} />
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setModalOpen(false)}>Cancel</Button>
              <Button onClick={handleCreateSprint}>Save</Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
      <div className="relative">
        <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
        <Input type="search" placeholder="Search sprints..." className="w-full pl-9 [&::-webkit-search-cancel-button]:hidden [&::-webkit-search-decoration]:hidden" value={searchSprint} onChange={(e) => setSearchSprint(e.target.value)} />
      </div>
      <DataTable
        data={(sprint ?? [])
          .filter((item) => {
            if (!searchSprint) return true;
            const q = searchSprint.toLowerCase();
            return Object.values(item).some((v) => String(v).toLowerCase().includes(q));
          })}
        columns={[
          { accessorKey: "name", header: "Name" },
          { accessorKey: "goal", header: "Goal" },
          { accessorKey: "status", header: "Status" },
          { accessorKey: "project_name", header: "Project" },
          { accessorKey: "date_range", header: "Dates" },
          { accessorKey: "cost_budget", header: "Cost Budget" },
          { accessorKey: "cost_spent", header: "Spent" },
        ]}
        emptyMessage="No matching results found."
      />
    </div>
    <Toaster />
    </>
  );
}
