// clockwork-plan-detail.tsx
// Generated by Sigil — do not edit manually

import { useNavigate, useParams } from "react-router-dom";
import { ArrowRight, BarChart3, CheckCircle, List, Loader2, Pencil, Play, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { DataTable } from "@/components/data-table";
import { usePlanById } from "@/hooks/use-plan";
import { useTask } from "@/hooks/use-task";

export default function ClockworkPlanDetail() {
  const navigate = useNavigate();
  const params = useParams();
  const { data: plan, isLoading: planLoading } = usePlanById(params.id as string);
  const { data: task, isLoading: taskLoading } = useTask();

  if (planLoading || taskLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-6 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <div className="flex flex-row gap-4 items-center">
          <h1 className="text-2xl font-semibold tracking-tight text-foreground">{`{{plan.name}}`}</h1>
          <p className="text-sm text-muted-foreground">{`{{plan.description}}`}</p>
        </div>
        <Button variant="secondary" onClick={() => navigate("/plan-editor")}>
          <Pencil className="mr-2 h-4 w-4" />
          Edit Plan
        </Button>
      </div>
      <div className="flex flex-row gap-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Tasks</CardTitle>
            <List className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{`{{plan.stats.total}}`}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Completed</CardTitle>
            <CheckCircle className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{`{{plan.stats.completed}}`}</div>
            <p className="text-xs text-emerald-500">Trending up</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">In Progress</CardTitle>
            <Play className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{`{{plan.stats.in_progress}}`}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Progress</CardTitle>
            <BarChart3 className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{`{{plan.stats.progress}}%`}</div>
          </CardContent>
        </Card>
      </div>
      <div className="flex flex-col gap-4">
        <h2 className="text-xl font-semibold tracking-tight text-foreground">Phases</h2>
        <Tabs defaultValue="0">
          <TabsList>
            <TabsTrigger value="0">Phase 1</TabsTrigger>
            <TabsTrigger value="1">Phase 2</TabsTrigger>
          </TabsList>
          <TabsContent value="0">
            <div className="flex flex-col gap-4">
              <Card>
                <CardContent>
                  <p className="text-sm text-muted-foreground">{`{{plan.phases.0.description}}`}</p>
                  <div className="flex flex-row gap-4">
                    <Card>
                      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">Tasks</CardTitle>
                      </CardHeader>
                      <CardContent>
                        <div className="text-2xl font-bold">{`{{plan.phases.0.task_count}}`}</div>
                      </CardContent>
                    </Card>
                    <Card>
                      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">Done</CardTitle>
                      </CardHeader>
                      <CardContent>
                        <div className="text-2xl font-bold">{`{{plan.phases.0.done_count}}`}</div>
                        <p className="text-xs text-emerald-500">Trending up</p>
                      </CardContent>
                    </Card>
                    <Card>
                      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">Blocked</CardTitle>
                      </CardHeader>
                      <CardContent>
                        <div className="text-2xl font-bold">{`{{plan.phases.0.blocked_count}}`}</div>
                      </CardContent>
                    </Card>
                  </div>
                  <Progress value={Number(`{{plan.phases.0.progress}}`) || 0} />
                </CardContent>
              </Card>
            </div>
          </TabsContent>
          <TabsContent value="1">
            <div className="flex flex-col gap-4">
              <p className="text-sm text-muted-foreground">{`{{plan.phases.1.description}}`}</p>
              <div className="flex flex-row gap-4">
                <Card>
                  <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                    <CardTitle className="text-sm font-medium">Tasks</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="text-2xl font-bold">{`{{plan.phases.1.task_count}}`}</div>
                  </CardContent>
                </Card>
                <Card>
                  <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                    <CardTitle className="text-sm font-medium">Done</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="text-2xl font-bold">{`{{plan.phases.1.done_count}}`}</div>
                    <p className="text-xs text-emerald-500">Trending up</p>
                  </CardContent>
                </Card>
                <Card>
                  <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                    <CardTitle className="text-sm font-medium">Blocked</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="text-2xl font-bold">{`{{plan.phases.1.blocked_count}}`}</div>
                  </CardContent>
                </Card>
              </div>
              <Progress value={Number(`{{plan.phases.1.progress}}`) || 0} />
            </div>
          </TabsContent>
        </Tabs>
      </div>
      <div className="flex flex-row gap-4 justify-between items-center">
        <h2 className="text-xl font-semibold tracking-tight text-foreground">Phase Tasks</h2>
        <Select>
          <SelectTrigger>
            <SelectValue placeholder="Filter by status" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All</SelectItem>
            <SelectItem value="open">Open</SelectItem>
            <SelectItem value="in_progress">In Progress</SelectItem>
            <SelectItem value="in_review">In Review</SelectItem>
            <SelectItem value="done">Done</SelectItem>
          </SelectContent>
        </Select>
      </div>
      <DataTable
        data={task ?? []}
        columns={[
          { accessorKey: "id", header: "ID" },
          { accessorKey: "title", header: "Title" },
          { accessorKey: "status", header: "Status" },
          { accessorKey: "priority", header: "Priority" },
          { accessorKey: "assignee", header: "Assignee" },
          { accessorKey: "phase", header: "Phase" },
          { accessorKey: "updated_at", header: "Updated" },
        ]}
        onRowClick={() => navigate("/task-detail")}
      />
      <div className="flex flex-row gap-3">
        <Button variant="default" onClick={() => fetch(`/api/clockwork/plans/{{plan.id}}/transition`, { method: "POST" })}>
          <ArrowRight className="mr-2 h-4 w-4" />
          Transition Phase
        </Button>
        <Button variant="destructive" onClick={() => { if (window.confirm("Are you sure you want to cancel this plan?")) { /* action */ } }}>
          <XCircle className="mr-2 h-4 w-4" />
          Cancel Plan
        </Button>
      </div>
    </div>
    </>
  );
}
