// clockwork-collections.tsx
// Generated by Sigil — do not edit manually

import { useState } from "react";
import { toast } from "sonner";
import { Loader2, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Toaster } from "@/components/ui/sonner";
import { Textarea } from "@/components/ui/textarea";
import { KanbanBoard } from "@/components/kanban-board";
import { useCollection } from "@/hooks/use-collection";
import { useTask } from "@/hooks/use-task";
import { postItem } from "@/lib/api";

export default function ClockworkCollections() {
  const [modalOpen, setModalOpen] = useState(false);
  const [formName, setFormName] = useState("");
  const [formDescription, setFormDescription] = useState("");
    const handleCreateCollection = async () => {
    try {
      await postItem("collections", {
        name: formName,
        description: formDescription,
      });
      toast.success("Collection created");
      setModalOpen(false);
      setFormName("");
      setFormDescription("");
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to create collection");
    }
  };



  const { data: collection, isLoading: collectionLoading, refetch: refetchCollection } = useCollection();
  const { data: task, isLoading: taskLoading } = useTask();

  if (collectionLoading || taskLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-6 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <h1 className="text-2xl font-semibold tracking-tight text-foreground">Collections</h1>
        <Dialog open={modalOpen} onOpenChange={setModalOpen}>
          <DialogTrigger render={<Button variant="default" />}>
            <Plus className="mr-2 h-4 w-4" />
            New Collection
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>New Collection</DialogTitle>
            </DialogHeader>
            <div className="flex flex-col gap-4 py-4">
              <div className="flex flex-col gap-1.5">
                <Label htmlFor="name">Name</Label>
                <Input id="name" type="text" placeholder="" value={formName} onChange={(e) => setFormName(e.target.value)} />
              </div>
              <div className="flex flex-col gap-1.5">
                <Label htmlFor="description">Description</Label>
                <Textarea id="description" placeholder="" rows={3} value={formDescription} onChange={(e) => setFormDescription(e.target.value)} />
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setModalOpen(false)}>Cancel</Button>
              <Button onClick={handleCreateCollection}>Save</Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
      <KanbanBoard
        cards={[]}
        inbox={[]}
        draggable
        columns={[{"id":"inbox","status":"inbox","title":"Inbox"},{"id":"active","status":"active","title":"Active"},{"id":"archived","status":"archived","title":"Archived"}]}
      />
    </div>
    <Toaster />
    </>
  );
}
