// clockwork-task-detail.tsx
// Generated by Sigil — do not edit manually

import { useNavigate, useParams } from "react-router-dom";
import { Loader2, Pencil } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ActivityPanel } from "@/components/activity-panel";
import { ArtifactCard } from "@/components/artifact-card";
import { CommentList } from "@/components/comment-list";
import { StatusBadge } from "@/components/status-badge";
import { useArtifact } from "@/hooks/use-artifact";
import { useCheckpoint } from "@/hooks/use-checkpoint";
import { useComment } from "@/hooks/use-comment";
import { useRun } from "@/hooks/use-run";
import { useTaskById } from "@/hooks/use-task";

export default function ClockworkTaskDetail() {
  const navigate = useNavigate();
  const params = useParams();
  const { data: task, isLoading: taskLoading } = useTaskById(params.id as string);
  const { data: run, isLoading: runLoading } = useRun();
  const { data: artifact, isLoading: artifactLoading } = useArtifact();
  const { data: comment, isLoading: commentLoading } = useComment();
  const { data: checkpoint, isLoading: checkpointLoading } = useCheckpoint();

  if (taskLoading || runLoading || artifactLoading || commentLoading || checkpointLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-6 p-6">
      <div className="flex flex-col gap-2">
        <p className="text-base">{`{{Task.blocked_reason}}`}</p>
      </div>
      <div className="flex flex-row gap-4 justify-between items-center">
        <StatusBadge
          status={task?.status}
          size="lg"
        />
        <h2 className="text-xl font-semibold tracking-tight text-foreground">{`{{Task.title}}`}</h2>
        <Button variant="outline" onClick={() => navigate("/task-editor")}>
          <Pencil className="mr-2 h-4 w-4" />
          Edit
        </Button>
      </div>
      <Tabs defaultValue="details">
        <TabsList>
          <TabsTrigger value="details">Details</TabsTrigger>
          <TabsTrigger value="comments">Comments</TabsTrigger>
          <TabsTrigger value="artifacts">Artifacts</TabsTrigger>
          <TabsTrigger value="subtodos">Subtodos</TabsTrigger>
          <TabsTrigger value="logs">Logs</TabsTrigger>
          <TabsTrigger value="debug">Debug</TabsTrigger>
        </TabsList>
        <TabsContent value="details">
          <div className="space-y-4">
            <div>
              <dt className="text-sm font-medium text-muted-foreground">ID</dt>
              <dd className="text-sm mt-1">{String(task?.id ?? "")}</dd>
            </div>
            <div>
              <dt className="text-sm font-medium text-muted-foreground">Title</dt>
              <dd className="text-sm mt-1">{String(task?.title ?? "")}</dd>
            </div>
            <div>
              <dt className="text-sm font-medium text-muted-foreground">Description</dt>
              <dd className="text-sm mt-1">{String(task?.description ?? "")}</dd>
            </div>
            <div>
              <dt className="text-sm font-medium text-muted-foreground">Status</dt>
              <dd className="text-sm mt-1">{String(task?.status ?? "")}</dd>
            </div>
            <div>
              <dt className="text-sm font-medium text-muted-foreground">Priority</dt>
              <dd className="text-sm mt-1">{String(task?.priority ?? "")}</dd>
            </div>
            <div>
              <dt className="text-sm font-medium text-muted-foreground">Assignee</dt>
              <dd className="text-sm mt-1">{String(task?.assignee ?? "")}</dd>
            </div>
            <div>
              <dt className="text-sm font-medium text-muted-foreground">Tags</dt>
              <dd className="text-sm mt-1">{String(task?.tags ?? "")}</dd>
            </div>
            <div>
              <dt className="text-sm font-medium text-muted-foreground">Collection</dt>
              <dd className="text-sm mt-1">{String(task?.collection_id ?? "")}</dd>
            </div>
            <div>
              <dt className="text-sm font-medium text-muted-foreground">Created</dt>
              <dd className="text-sm mt-1">{String(task?.created_at ?? "")}</dd>
            </div>
            <div>
              <dt className="text-sm font-medium text-muted-foreground">Updated</dt>
              <dd className="text-sm mt-1">{String(task?.updated_at ?? "")}</dd>
            </div>
          </div>
        </TabsContent>
        <TabsContent value="comments">
          <CommentList
            datasource="Comment"
            taskField="task_id"
          />
        </TabsContent>
        <TabsContent value="artifacts">
          <div className="flex flex-col gap-4">
            <div className="flex flex-row gap-4">
              <ArtifactCard
                datasource="Artifact"
                taskField="task_id"
              />
            </div>
          </div>
        </TabsContent>
        <TabsContent value="subtodos">
          <div className="flex flex-col gap-2">
            <div className="flex flex-row gap-3 items-center">
              <div className="flex items-center space-x-2">
                <Checkbox id="checkbox" />
                <Label htmlFor="checkbox"></Label>
              </div>
              <p className="text-base"></p>
            </div>
          </div>
        </TabsContent>
        <TabsContent value="logs">
          <ActivityPanel
            taskField="task_id"
            datasource="Run"
          />
        </TabsContent>
        <TabsContent value="debug">
          <p className="text-base">{`{{Task | json}}`}</p>
        </TabsContent>
      </Tabs>
    </div>
    </>
  );
}
