// clockwork-checkpoints.tsx
// Generated by Sigil — do not edit manually

import { useState } from "react";
import { toast } from "sonner";
import { CheckCircle, Loader2, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Toaster } from "@/components/ui/sonner";
import { CheckpointCard } from "@/components/checkpoint-card";
import { SummaryCards } from "@/components/summary-cards";
import { useCheckpoint } from "@/hooks/use-checkpoint";
import { useTask } from "@/hooks/use-task";
import { postItem } from "@/lib/api";

export default function ClockworkCheckpoints() {
  const [filterCheckpointKind, setFilterCheckpointKind] = useState("all");
  const [modalOpen, setModalOpen] = useState(false);
  const [formResponse, setFormResponse] = useState("");
  const [formNotes, setFormNotes] = useState("");
    const handleCreateCheckpoint = async () => {
    try {
      await postItem("checkpoints", {
        response: formResponse,
        notes: formNotes,
      });
      toast.success("Checkpoint created");
      setModalOpen(false);
      setFormResponse("");
      setFormNotes("");
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to create checkpoint");
    }
  };



  const { data: checkpoint, isLoading: checkpointLoading } = useCheckpoint();
  const { data: task, isLoading: taskLoading } = useTask();

  if (checkpointLoading || taskLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-6 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <h1 className="text-2xl font-semibold tracking-tight text-foreground">Checkpoints</h1>
        <div className="flex flex-row gap-2">
          <Select onValueChange={(v) => setFilterCheckpointKind(v as string)}>
            <SelectTrigger>
              <SelectValue placeholder="All Types" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All</SelectItem>
              <SelectItem value="approval">Approval</SelectItem>
              <SelectItem value="review">Review</SelectItem>
              <SelectItem value="decision">Decision</SelectItem>
            </SelectContent>
          </Select>
          <Select>
            <SelectTrigger>
              <SelectValue placeholder="All Statuses" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All</SelectItem>
              <SelectItem value="pending">Pending</SelectItem>
              <SelectItem value="resolved">Resolved</SelectItem>
              <SelectItem value="cancelled">Cancelled</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>
      <SummaryCards
        datasource="Checkpoint"
        cards={[{"field":"status","filter":"pending","icon":"alert-circle","id":"pending-count","label":"Pending","variant":"warning"},{"field":"affected_tasks","icon":"list","id":"affected-tasks","label":"Affected Tasks","variant":"info"},{"field":"age","icon":"clock","id":"oldest-age","label":"Oldest","variant":"default"},{"field":"kind","icon":"layers","id":"type-diversity","label":"Types","variant":"primary"}]}
      />
      <div className="flex flex-col md:flex-row">
        <div className="md:w-auto" style={{flexBasis: "40%"}}>
          <div className="flex flex-col gap-3">
            <div className="divide-y">
              {checkpoint && checkpoint.length > 0 ? checkpoint.map((item: NonNullable<typeof checkpoint>[number], i: number) => (
                <div key={i} className="py-3">
                  <CheckpointCard
                    datasource="Checkpoint"
                    showDetail={false}
                    variant="default"
                  />
                </div>
              )) : <p className="text-sm text-muted-foreground py-3">No checkpoints found</p>}
            </div>
          </div>
        </div>
        <div className="h-px md:h-auto md:w-px bg-border" />
        <div className="flex-1">
          <div className="flex flex-col gap-4">
            <h2 className="text-xl font-semibold tracking-tight text-foreground">Checkpoint Detail</h2>
            <Card>
              <CardHeader>
                <CardTitle>Payload</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div>
                    <dt className="text-sm font-medium text-muted-foreground">ID</dt>
                    <dd className="text-sm mt-1">{String((Array.isArray(checkpoint) ? checkpoint[0] : checkpoint)?.id ?? "")}</dd>
                  </div>
                  <div>
                    <dt className="text-sm font-medium text-muted-foreground">Kind</dt>
                    <dd className="text-sm mt-1">{String((Array.isArray(checkpoint) ? checkpoint[0] : checkpoint)?.kind ?? "")}</dd>
                  </div>
                  <div>
                    <dt className="text-sm font-medium text-muted-foreground">Status</dt>
                    <dd className="text-sm mt-1">{String((Array.isArray(checkpoint) ? checkpoint[0] : checkpoint)?.status ?? "")}</dd>
                  </div>
                  <div>
                    <dt className="text-sm font-medium text-muted-foreground">Task</dt>
                    <dd className="text-sm mt-1">{String((Array.isArray(checkpoint) ? checkpoint[0] : checkpoint)?.task_id ?? "")}</dd>
                  </div>
                  <div>
                    <dt className="text-sm font-medium text-muted-foreground">Created</dt>
                    <dd className="text-sm mt-1">{String((Array.isArray(checkpoint) ? checkpoint[0] : checkpoint)?.created_at ?? "")}</dd>
                  </div>
                  <div>
                    <dt className="text-sm font-medium text-muted-foreground">Expires</dt>
                    <dd className="text-sm mt-1">{String((Array.isArray(checkpoint) ? checkpoint[0] : checkpoint)?.expires_at ?? "")}</dd>
                  </div>
                  <div>
                    <dt className="text-sm font-medium text-muted-foreground">Requester</dt>
                    <dd className="text-sm mt-1">{String((Array.isArray(checkpoint) ? checkpoint[0] : checkpoint)?.requester ?? "")}</dd>
                  </div>
                  <div>
                    <dt className="text-sm font-medium text-muted-foreground">Context</dt>
                    <dd className="text-sm mt-1">{String((Array.isArray(checkpoint) ? checkpoint[0] : checkpoint)?.context ?? "")}</dd>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Data</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div>
                    <dt className="text-sm font-medium text-muted-foreground">Payload</dt>
                    <dd className="text-sm mt-1">{String((Array.isArray(checkpoint) ? checkpoint[0] : checkpoint)?.payload ?? "")}</dd>
                  </div>
                  <div>
                    <dt className="text-sm font-medium text-muted-foreground">Notes</dt>
                    <dd className="text-sm mt-1">{String((Array.isArray(checkpoint) ? checkpoint[0] : checkpoint)?.notes ?? "")}</dd>
                  </div>
                </div>
              </CardContent>
            </Card>
            <div className="flex flex-row gap-3">
              <Dialog open={modalOpen} onOpenChange={setModalOpen}>
                <DialogTrigger render={<Button variant="default" />}>
                  <CheckCircle className="mr-2 h-4 w-4" />
                  Respond
                </DialogTrigger>
                <DialogContent>
                  <DialogHeader>
                    <DialogTitle>Respond to Checkpoint</DialogTitle>
                  </DialogHeader>
                  <div className="flex flex-col gap-4 py-4">
                    <div className="flex flex-col gap-1.5">
                      <Label htmlFor="response">Response</Label>
                      <Select value={formResponse} onValueChange={(v) => v && setFormResponse(v)}>
                        <SelectTrigger>
                          <SelectValue placeholder="Select..." />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="approve">Approve</SelectItem>
                          <SelectItem value="reject">Reject</SelectItem>
                          <SelectItem value="revise">Request Revision</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                    <div className="flex flex-col gap-1.5">
                      <Label htmlFor="notes">Notes</Label>
                      <Input id="notes" type="text" placeholder="Optional notes" value={formNotes} onChange={(e) => setFormNotes(e.target.value)} />
                    </div>
                  </div>
                  <DialogFooter>
                    <Button variant="outline" onClick={() => setModalOpen(false)}>Cancel</Button>
                    <Button onClick={handleCreateCheckpoint}>Save</Button>
                  </DialogFooter>
                </DialogContent>
              </Dialog>
              <Button variant="destructive" onClick={() => { if (window.confirm("Cancel this checkpoint?")) { /* action */ } }}>
                <XCircle className="mr-2 h-4 w-4" />
                Cancel
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <Toaster />
    </>
  );
}
