// clockwork-plans.tsx
// Generated by Sigil — do not edit manually

import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Loader2, Plus, Search } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { usePlan } from "@/hooks/use-plan";

export default function ClockworkPlans() {
  const navigate = useNavigate();
  const [searchPlan, setSearchPlan] = useState("");

  const { data: plan, isLoading: planLoading, refetch: refetchPlan } = usePlan();

  if (planLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-6 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <h1 className="text-2xl font-semibold tracking-tight text-foreground">Plans</h1>
        <Button variant="default" onClick={() => navigate("/plan-editor")}>
          <Plus className="mr-2 h-4 w-4" />
          New Plan
        </Button>
      </div>
      <div className="relative">
        <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
        <Input type="search" placeholder="Search plans..." className="w-full pl-9 [&::-webkit-search-cancel-button]:hidden [&::-webkit-search-decoration]:hidden" value={searchPlan} onChange={(e) => setSearchPlan(e.target.value)} />
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
        {(plan ?? []).map((item: NonNullable<typeof plan>[number]) => (
          <div key={String(item.name ?? "")}>
            <Card>
              <CardHeader>
                <CardTitle>{String(item.name ?? "")}</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="flex flex-col gap-3">
                  <div className="flex flex-row gap-4 justify-between items-center">
                    <Badge variant="default">{String(item.status ?? "")}</Badge>
                    <p className="text-sm text-muted-foreground">{`${item.phase_count} phases`}</p>
                  </div>
                  <div className="flex flex-row gap-4 justify-between">
                    <p className="text-base">Progress</p>
                    <p className="text-sm text-muted-foreground">{`${item.progress}%`}</p>
                  </div>
                  <Progress value={Number(item.progress) || 0} />
                  <p className="text-sm text-muted-foreground">{String(item.description ?? "")}</p>
                </div>
              </CardContent>
            </Card>
          </div>
        ))}
      </div>
    </div>
    </>
  );
}
