// forge-logs.tsx
// Generated by Sigil — do not edit manually

"use client";

import { useState } from "react";
import { CalendarIcon, ChevronLeft, ChevronRight, Loader2, Search } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Calendar } from "@/components/ui/calendar";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { DataTable } from "@/components/data-table";
import { useLogEntry } from "@/hooks/use-logentry";

export default function ForgeLogs() {
  const [logStartDate, setLogStartDate] = useState<Date | undefined>();
  const [logEndDate, setLogEndDate] = useState<Date | undefined>();
  const [filterLogEntryLevel, setFilterLogEntryLevel] = useState("all");
  const [searchLogEntry, setSearchLogEntry] = useState("");

  const { data: logEntry, isLoading: logEntryLoading } = useLogEntry();

  if (logEntryLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <>
    <div className="flex flex-col gap-6 p-6">
      <div className="flex flex-row gap-4 justify-between items-center">
        <h1 className="text-2xl font-semibold tracking-tight text-foreground">Logs</h1>
        <div className="flex flex-row gap-2 items-center">
          <Popover>
            <PopoverTrigger render={<Button variant="outline" className="w-[240px] justify-start text-left font-normal" />}>
              <CalendarIcon className="mr-2 h-4 w-4" />
              {logStartDate ? logStartDate.toLocaleDateString() : <span className="text-muted-foreground">Start date</span>}
            </PopoverTrigger>
            <PopoverContent className="w-auto p-0">
              <Calendar mode="single" selected={logStartDate} onSelect={setLogStartDate} />
            </PopoverContent>
          </Popover>
          <Popover>
            <PopoverTrigger render={<Button variant="outline" className="w-[240px] justify-start text-left font-normal" />}>
              <CalendarIcon className="mr-2 h-4 w-4" />
              {logEndDate ? logEndDate.toLocaleDateString() : <span className="text-muted-foreground">End date</span>}
            </PopoverTrigger>
            <PopoverContent className="w-auto p-0">
              <Calendar mode="single" selected={logEndDate} onSelect={setLogEndDate} />
            </PopoverContent>
          </Popover>
          <Select onValueChange={(v) => setFilterLogEntryLevel(v as string)}>
            <SelectTrigger>
              <SelectValue placeholder="All Levels" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Levels</SelectItem>
              <SelectItem value="debug">Debug</SelectItem>
              <SelectItem value="info">Info</SelectItem>
              <SelectItem value="warn">Warn</SelectItem>
              <SelectItem value="error">Error</SelectItem>
              <SelectItem value="fatal">Fatal</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>
      <div className="relative">
        <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
        <Input type="search" placeholder="Search logs..." className="w-full pl-9 [&::-webkit-search-cancel-button]:hidden [&::-webkit-search-decoration]:hidden" value={searchLogEntry} onChange={(e) => setSearchLogEntry(e.target.value)} />
      </div>
      <ScrollArea className="h-[calc(100vh - 200px)]">
        <Card className="border-0 shadow-none ring-0">
          <CardContent>
            <DataTable
              data={(logEntry ?? [])
                .filter((item) => filterLogEntryLevel === "all" || item.level === filterLogEntryLevel)
                .filter((item) => {
                  if (!searchLogEntry) return true;
                  const q = searchLogEntry.toLowerCase();
                  return Object.values(item).some((v) => String(v).toLowerCase().includes(q));
                })}
              columns={[
                { accessorKey: "timestamp", header: "Timestamp" },
                {
                  accessorKey: "level",
                  header: "Level",
                  cell: ({ row }: { row: { getValue: (k: string) => unknown } }) => {
                    const v = String(row.getValue("level") ?? "");
                    const variants: Record<string, string> = { "fatal": "danger", "error": "danger", "warn": "warning", "info": "info", "debug": "default" };
                    const variant = variants[v] ?? variants[v.toLowerCase()] ?? "default";
                    return <Badge variant={variant === "danger" ? "destructive" : variant === "success" || variant === "warning" || variant === "info" ? "outline" : "secondary"} className={
                      variant === "success" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-400" :
                      variant === "warning" ? "border-amber-500/30 bg-amber-500/10 text-amber-400" :
                      variant === "info" ? "border-blue-500/30 bg-blue-500/10 text-blue-400" :
                      variant === "danger" ? "" : ""
                    }>{v}</Badge>;
                  },
                },
                { accessorKey: "service", header: "Service" },
                { accessorKey: "message", header: "Message" },
                { accessorKey: "source", header: "Source" },
              ]}
              emptyMessage="No matching results found."
            />
          </CardContent>
        </Card>
      </ScrollArea>
      <div className="flex items-center justify-center gap-2">
        <Button variant="outline" size="icon" disabled><ChevronLeft className="h-4 w-4" /></Button>
        <span className="text-sm text-muted-foreground">Page 1</span>
        <Button variant="outline" size="icon"><ChevronRight className="h-4 w-4" /></Button>
      </div>
    </div>
    </>
  );
}
