// types/asset.ts
// Generated by Sigil — do not edit manually

export interface Asset {
  id: string;
  name: string;
  type?: string;
  provider?: string;
  status?: string;
  region?: string;
  cost?: string;
  updatedAt?: string;
}

export interface AssetInput {
  name: string;
  type?: string;
  provider?: string;
  status?: string;
  region?: string;
  cost?: string;
  updatedAt?: string;
}
