// types/logentry.ts
// Generated by Sigil — do not edit manually

export interface LogEntry {
  id: string;
  timestamp?: string;
  level?: string;
  service?: string;
  message?: string;
  source?: string;
}

export interface LogEntryInput {
  timestamp?: string;
  level?: string;
  service?: string;
  message?: string;
  source?: string;
}
