// types/sigilcomponent.ts
// Generated by Sigil — do not edit manually

export interface SigilComponent {
  type: string;
  category?: string;
  description?: string;
  propsCount?: number;
}

export interface SigilComponentInput {
  category?: string;
  description?: string;
  propsCount?: number;
}
