// types/user.ts
// Generated by Sigil — do not edit manually

export interface User {
  id: string;
  name: string;
  email: string;
  role?: string;
  status?: string;
  lastActive?: string;
  teams?: string;
}

export interface UserInput {
  name: string;
  email: string;
  role?: string;
  status?: string;
  lastActive?: string;
  teams?: string;
}
